### ISSUE TITLE
Page not found - Motivation.html for shell-novice

### ISSUE THREAD

**Issue by anelda** [swcarpentry/shell-novice#100]
Error 404 when navigating from http://swcarpentry.github.io/shell-novice/ to http://swcarpentry.github.io/shell-novice/motivation.html by clicking on "Motivation"

**Comment by wking** [comment]
On Wed, Mar 11, 2015 at 03:21:06AM -0700, Anelda van der Walt wrote:
> Error 404 when navigating from
> http://swcarpentry.github.io/shell-novice/ to
> http://swcarpentry.github.io/shell-novice/motivation.html by
> clicking on "Motivation"

Duplicate of #47?

**Comment by r-gaia-cs** [comment]
@wking Yes.

**Comment by anelda** [comment]
Oops, sorry!  Should have checked existing issues. So we learn.  Do I have to close this issue or how does it work?

**Comment by wking** [comment]
On Wed, Mar 11, 2015 at 01:56:07PM -0700, Anelda van der Walt wrote:
> Oops, sorry!  Should have checked existing issues. So we learn.  Do
> I have to close this issue or how does it work?

You can close it if you like, or leave it to a maintainer to close it
in case they've also forgotten about the issue ;).

If you have some time, you could also submit a PR with a proposed
motivation.md (sample content here [1]).

[1]: https://raw.githubusercontent.com/swcarpentry/lesson-template/gh-pages/motivation.md

**Comment by ChristinaLK** [comment]
Haha, I'll leave this open as a gentle reminder to self.

**Comment by anelda** [comment]
I've created a draft motivation.md.  Very new to Github etc - hope this is useful :-)

**Comment by r-gaia-cs** [comment]
@anelda Thanks for the draft of `motivation.md`.

> Very new to Github etc - hope this is useful :-)

Any contribution is useful.

You can mention pull request/issue writing `#` follow by the number of the pull request/issue, e.g. the draft of `motivation.md` from @anelda can be find at #107.

Few free to ask any question about Git/GitHub to us as an issue or email to discuss@lists.software-carpentry.org.

**Comment by anelda** [comment]
Thank you @r-gaia-cs - you reminded me again to join the mailing list :-) have done so now.

**Comment by ChristinaLK** [comment]
Thanks for the contribution @anelda !
