### ISSUE TITLE
wc Clarification

### ISSUE THREAD

**Issue by luissv7** [swcarpentry/shell-novice#1002]
In the pipes and filters section, I find the section on wc confusing.  "it counts the number of lines, words, and characters in files (from left to right, in that order)."

As a new user, I would have no idea what exactly is a "line". Is a blank line at the end of my text file a "line"? I would have the same question about what is a word. Is a sequence of numbers a "word"? 

Is it a good idea to introduce the man pages at this point?

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by kdillmcfarland** [comment]
Do you think a diagram like the following would be beneficial?
[cubane_wc_annotation.pdf](https://github.com/swcarpentry/shell-novice/files/3465208/cubane_wc_annotation.pdf)

And/or additional wording such as: 
...it counts the number of lines, words, and characters in files (from left to right, in that order). In the file being processed by wc, lines must be separated by hard returns or paragraph breaks and words by spaces or tabs.

**Comment by gcapes** [comment]
Thanks for the issue @luissv7 

Let's focus on the learning objectives for the episode - the `wc` command is really a prop used to generate some data. The data are then used to learn about pipes and filters. While the details of `wc` aren't covered, I think covering that level of detail would be more of a distraction for most people (extraneous load).

In the situation where a learner wants to know whether numbers are treated differently to letters, and whether a empty line is considered to be a line, I think this is what the red sticky note is for.  The instructor can then either demonstrate some examples or take people through the manual.

**Comment by luissv7** [comment]
Hi @kdillmcfarland, I think @gcapes has a good point. Perhaps it is better to just use the sticky notes and go into details if the learner wants to know more about it. I do like the diagram though!
