### ISSUE TITLE
extra comma in the example command of Pipe Construction?

### ISSUE THREAD

**Issue by mimishu** [swcarpentry/shell-novice#1007]
Hi there, in reviewing the lessons, I noticed that on http://swcarpentry.github.io/shell-novice/04-pipefilter/index.html under Pipe Construction, in the first example command:

$ cut -d , -f 2 animals.txt

There is an extra space in between "-d" and ","? All the other command examples across the lessons don't have such extra spaces. I think having this extra space here is confusing and suggest its removal.

I hope this helps! Best, Shu (shu.liu@uci.edu)

**Comment by gcapes** [comment]
Hi @mimishu,
Perhaps it could do with some minor rewording, but does this help?

> The cut command is used to remove or “cut out” certain sections of each line in the file. The optional -d flag is used to define the delimiter. A delimiter is a character that is used to separate each line of text into columns. The default delimiter is Tab, meaning that the cut command will automatically assume that values in different columns will be separated by a tab. The -f flag is used to specify the field (column) to cut out. The command above uses the -d option to split each line by comma, and the -f option to print the second field in each line, to give the following output:

**Comment by mimishu** [comment]
O! Got cha! The comma is totally needed here. Thank you for helping me understand this example better!

**Comment by gdevenyi** [comment]
Thanks for letting is know it was unclear :)

**Comment by gcapes** [comment]
@mimishu 
No worries! Thanks for the issue
