### ISSUE TITLE
repeated wording that should be removed

### ISSUE THREAD

**Issue by mimishu** [swcarpentry/shell-novice#1008]
Hi there, in reviewing the lessons I noticed that on http://swcarpentry.github.io/shell-novice/06-script/index.html under List Unique Species, in the very last paragraph right above Solution:

"Write a shell script called species.sh that takes any number of filenames as command-line arguments, **and uses and uses** a variation of the above command to print a list of the unique species appearing in each of those files separately."

"and uses" (bolded) are repeated twice. I suggest fixing this very minor error.

Hope this helps! Best, Shu (shu.liu@uci.edu)

**Comment by gcapes** [comment]
Well spotted, thanks! A PR to fix this would be welcome.
