### ISSUE TITLE
Unix Shell setup suggestion - Video link and instructions on set up could be helpful

### ISSUE THREAD

**Issue by dharanisontam** [swcarpentry/shell-novice#1010]
This suggestion is especially with respect to Windows machines. 

We recently set up the software carpentry webpage for our upcoming SWC session. I like that there were step by step instructions for the attendees on how to install Git Bash, nano and Anaconda to get ready for the workshop. There are also video tutorials which are quite helpful.

However, I notice that on the Unix Shell lesson setup page, it says: "If you are attending a Software Carpentry workshop session, it is likely you have already received instructions on how to install Git for Windows."

I believe that for people who are learning by themselves, the step-by-step instructions on setup could be quite useful. I suggest to include the video tutorials and the instructions on this page as well. I hope that makes sense.

**Comment by gcapes** [comment]
Good suggestion, thanks!

**Comment by sheraaronhurt** [comment]
great idea

**Comment by T0T4R4** [comment]
What do you mean ? Installation of those is as easy as downloading it from the website, running the installer. We certainly must assume that students have a certain level of computer knowledge - and they generally do have enough to install games on their PCs :)
There is a maintenance cost involved in producing teaching material particularly videos. Student will find plenty of resources on YouTube, as most of us do.

**Comment by gcapes** [comment]
I guess the point is that the instructions in the shell lesson could be shorter and clearer. I am in favour of improving the text instructions - I don't see the need for a video.

I think we should remove the stuff about accessing a remote machine using ssh. It doesn't apply to most learners, and the instructions given can't be complete enough anyway - they'll  need to be provided by the host if they're using a remote machine.

**Comment by wirawan0** [comment]
Following up Gerard's comment about ssh. Do we have some kind of statistics from the workshops we have done worldwide--how many are using what kind of installation? In particular, how many workshops are using ssh to connect to a Linux/UNIX computer? The instruction about remote computer should probably be shifted to the "For advanced users".

In response to @T0T4R4, I'd say: the "Git for WIndows" setup may not be as straightforward to people who are not familiar with the choices presented in the installer. For example GIt for Windows is offering "vim" as the default editor. But this would be a tough choice for most learners.

In fact I just opened issue #1086 to ask whether Git for WIndows instructions on the "workshop-template" are important enough to also be mentioned in "shell-novice" setup instructions.

Wirawan

**Comment by casepie** [comment]
I would agree with Wirawan0 and suggest moving the remote computer (ssh) information to "For Advanced users".  I would additionally suggest, if you want to leave a statement in the mainline instructions about remote ssh, it be much simpler and refer to the advanced instructions.  For instance, "More advanced learners may wish to use a remote machine and SSH instead of a local Git for Windows install, for information on this, see the section for advanced users."  This would let them know it's an option, and where to find more info, but it also lets most learners know right up front that it's advanced, and not required.

**Comment by sheraaronhurt** [comment]
this is great or maybe change this
