### ISSUE TITLE
Clarification of longest.sh script solution

### ISSUE THREAD

**Issue by SoftwareMonk** [swcarpentry/shell-novice#1014]
In [the 6th episode, Shell Scripts](https://swcarpentry.github.io/shell-novice/06-script/index.html#find-the-longest-file-with-a-given-extension), the solution to `longest.sh` doesn't provide an explanation on why it works. I think the ending of the script (`tail -n 2 | head -n 1`) might be confusing to some so it might be nice to explain that we use that set of commands instead of just `tail -n 1`. Some people may forget that `wc` shows a total at the end.

**Comment by gcapes** [comment]
Yes, this could benefit from a breakdown of the solution. I usually find asking learners to run the first command, then build up the pipeline by adding add one pipe at a time helps to clarify what is happening.
