### ISSUE TITLE
Objectives in episode 4: Pipes and Filters: `<` character

### ISSUE THREAD

**Issue by kairstenfay** [swcarpentry/shell-novice#1015]
In the Pipes and Filters episode of the Unix Shell intro material, there is an objective listed that is not covered in the actual material. 

At the bottom of [the lesson page](http://swcarpentry.github.io/shell-novice/04-pipefilter/index.html), under Key Notes, the following is listed:
* `<` operator redirects input to a command

The same objective is also listed on [the reference page](http://swcarpentry.github.io/shell-novice/reference/).

If you do a Control-F (find) on the page, you will see that the `<` character is not mentioned in the lesson plan. All the other commands/characters in the objectives are mentioned many times. It seems this `<` command is either a typo or was neglected to be written into the lesson.

**Comment by gcapes** [comment]
Thanks for the issue! This material was removed a while ago... I guess the objectives were overlooked.

A PR to remove these objectives would be welcomed!

**Comment by gcapes** [comment]
Fixed in #1016
