### ISSUE TITLE
wrong comment in shell script example sorted.sh

### ISSUE THREAD

**Issue by godmar** [swcarpentry/shell-novice#1018]
In [lesson 6](https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/06-script.md) it says:

```
# Sort filenames by their length.
# Usage: bash sorted.sh one_or_more_filenames
wc -l "$@" | sort -n
```

This is incorrect.  It should read:
```
# Sort files by the number of lines.
# Usage: bash sorted.sh one_or_more_filenames
wc -l "$@" | sort -n
```

It is not the length of the filenames that is used as the sort criteria, rather, it is the number of lines in the file to which the filenames refer.  The word 'their' is referring to the files, not the filenames.  The length of a filename is the number of characters in the name, not the number of lines in the file that is denoted by that filename.

**Comment by gcapes** [comment]
Thanks for the issue.  A PR would be welcome!

**Comment by godmar** [comment]
Sorry, I have to decline.  It's a small fix that is best done by the maintainers themselves and does not justify the overhead of a PR.

**Comment by gcapes** [comment]
A PR would still be welcome (from anyone) :)

**Comment by gcapes** [comment]
`wc -c` reports the number of bytes, so the *size* of a file. https://en.wikipedia.org/wiki/File_size

I can't find anything online (other than the java-specific https://www.tutorialspoint.com/java/io/file_length.htm) which supports your usage of file length = file size.
