### ISSUE TITLE
Setup is in the wrong order

### ISSUE THREAD

**Issue by Denubis** [swcarpentry/shell-novice#1022]
I recently had my class (non-workshop) all try to setup for this lesson. Many ran into issues with the instructions in the setup page of this lesson (not the setup of the workshop template). Step 3 of the instructions presumes they've set up a shell, which is the following section.

Perhaps this page could use some scaffolding or rearrangement, in case people are trying to deploy git shell or terminal for the first time without reference to the workshop template.

**Comment by gdevenyi** [comment]
Hi,

Can you please link to what you're referring to. Thanks.

**Comment by Denubis** [comment]
Hi @gdevenyi 

http://swcarpentry.github.io/shell-novice/setup.html has

>You need to download some files to follow this lesson:
> Download data-shell.zip and move the file to your Desktop.
> Unzip/extract the file (ask your instructor if you need help with this step). You should end up with a new folder called data-shell on your Desktop.
> Open a terminal and type cd, then press the Enter key. That last step will make sure you start with your home folder as your working directory.

At the top. But presumes they've already got a terminal working. If this is where they're looking for setup instructions instead of workshop-template, that is not the case. Most of my students reported confusion at this point.

**Comment by colinmorris** [comment]
Presumably the information they needed at that point was the stuff in the "Where to type commands: How to open a new shell" callout box. Maybe we could add some text to step 3 saying something like "If you're not sure how to open a terminal, see the section below"? I think it might also be more readable if we convert that content from a callout box to an actual section - in my opinion, it's too long (and too important) for a callout box.
