### ISSUE TITLE
auditing the lesson for demotivating use of j (just) word

### ISSUE THREAD

**Issue by nancyrouleurs** [swcarpentry/shell-novice#1023]
According to the teaching tips and the train-the-trainer workshop, it is recommended that we should avoid using the 'J' (just) word. However, from the lesson materials, there are a few of them. Would it be good if we can avoid this word in the lesson? I understand that in some context, this word can be used as well.

**Comment by gdevenyi** [comment]
Hi, can you please be specific as to what you're referring to? Thanks.

**Comment by gcapes** [comment]
The j-word is 'just'. We could remove several uses of it from the lesson materials.
