### ISSUE TITLE
Episode 4: Don't introduce `sort -r` when teaching piping

### ISSUE THREAD

**Issue by kairstenfay** [swcarpentry/shell-novice#1027]
In Episode 4, Pipes and Filters, we introduce students to `sort` and `sort -n`.

My issue is with the exercise titled "Pipe Reading Comprehension". In it, we not only show students the longest command-chain they've seen, but we also ask them to interpret `sort -r` without any introduction or previous exercise related to it.

In my opinion, the cognitive load is high enough reading four commands piped together. Adding a new `sort` option to figure out is unhelpful to students' understanding of this part of the lesson.

**Comment by colinmorris** [comment]
That sounds reasonable. Not sure if you had a specific solution in mind, but I can imagine a few:
1. Remove the `sort` command from the pipeline
1. Remove the `-r` flag from the `sort` command
1. Introduce and explain the `-r` flag at the beginning of the exercise.

I think any of these would be an improvement. PR welcome!

**Comment by gcapes** [comment]
In #892 we have a suggestion to use `ls -r` instead of `ls -R`. While this is a different command, the concept would already have been introduced (and the option happens to be the same). This may or may not affect thoughts on this issue?

**Comment by sstevens2** [comment]
Piping in though I've yet to make a PR on #892.  I vote for option 3.  Sorting in reverse is a frequent need and being able to figure out different flags is also a useful skill so I think it is worth adding in the piping lesson.  Sounds like the `-r` flag in `sort` needs a bit more introduction though.  It may also help somewhat when they've seen `-r` use for reverse in the `ls` command.
