### ISSUE TITLE
Episode 1 is too long

### ISSUE THREAD

**Issue by kairstenfay** [swcarpentry/shell-novice#1028]
I recently taught this lesson and found that `Episode 1: Introducing the Shell` was the most unpleasant episode. I spoke for longer than 5 minutes to cover the content but felt it wasn't rich enough to merit the time spent on it. Here are my observations:

- I found the `Background` section particularly bloated. It could be reduced to just two things.
    1. A GUI interface is most popular and is different from the command-line interface (or other interfaces).
    2. Advantages of CLI over GUI include: automation, reproducibility, less prone to user error. 

    The bullet points at the top of and the bit about a REPL should be deleted as they aren't relevant to the lesson. 

- The sections `Is it difficult?` and `Flexibility and automation` can be deleted as they should be covered in the new `Background` section.

- The `Nelle's Pipeline` case study was also far too long, and it never again became relevant to the lesson (we only made it to Episode 5). In the end I felt that I wasted a couple of minutes and lost my students' interest in building up a case study that was never revisited.

**Comment by colinmorris** [comment]
Thanks for the feedback, that all makes a lot of sense. The "Nelle's Pipeline" framing device is definitely a recurring pain point in this lesson. I'm sure at some point it formed a coherent throughline, but as individual parts of episodes got rewritten, moved around, expanded, or condensed, the 'Nelle' narrative has become kind of confusing. 

All your suggested cuts sound very sensible to me - PR(s) welcome. We love red diffs!

**Comment by colinmorris** [comment]
Fixed in #1040
