### ISSUE TITLE
Typo in The Unix Shell: Navigating Files and Directories 

### ISSUE THREAD

**Issue by tshippy** [swcarpentry/shell-novice#1029]
In the Slashes section of [The Unix Shell: Navigating Files and Directories,](http://swcarpentry.github.io/shell-novice/02-filedir/index.html) the following statement about slashes doesn't seem correct. "When it appears _inside_ a name, it’s just a separator."  Possible alternatives would be "When it appears **_after_** a name, it's just a separator." or "When it appears _inside_ a **path**, it's just a separator."

**Comment by gcapes** [comment]
Thanks for the issue!

I agree that the clarity could be improved - of your suggestions, I like
> When it appears inside a path, ...
