### ISSUE TITLE
Episode 07: find name pattern can be glob expanded, needs quotes

### ISSUE THREAD

**Issue by hoytpr** [swcarpentry/shell-novice#1031]
Sorry to intrude again. 
**What happened:**
While comparing the use of quotes for wildcard expansion with the `find` command (`find . -name *.txt` vs. `find . -name '*.txt'`)  the output of `find . -name *.txt` changes depending on whether a `.txt` file is present in the current working directory. Specifically, if `haiku.txt` is removed, the command `find . -name *.txt` (without quotes around `*.txt`) PROCEEDS and returns:
```
./data/LittleWomen.txt
./data/one.txt
./data/two.txt
```
After some research it's possible this is my first *known* encounter with unwanted "globbing". Please advise. Is this due to the shell not finding the wildcard pattern in the current working directory, but the `find -name` command continues to shell-glob?

**What did you expect to happen?**
I expected `find . -name *.txt` (no quotes around *.txt) to allow immediate shell expansion of the wildcard character resulting in no matching files. This would then give no output, or maybe an error that there are no `.txt` files present in the current working directory. 

Is it reasonable to mention how wildcard expansion in the shell is affected by matches in the current working directory?  As this might not even be "globbing" I'm **_way_** out of my comfort zone here. But something like:

> Without quotes around `*.txt`, the `find . -name *.txt` command wildcard expansion immediately encounters a matching filename (from the lesson: `haiku.txt`) in the current working directory and completes (stops). **_Without_** this matching filename the command `find` will begin at `.` (the current working directory) and recursively identify all filenames matching the pattern (in a process called "globbing" (if this actually is globbing)).

This is a great lesson and (IMO) already pretty advanced.  I'm only bringing this up because it's the first thing that happened to me when trying use these tools and work outside the lesson.  

Please feel free to close this issue.

**Comment by gdevenyi** [comment]
Hi, thanks for the detailed diagnosis. The issue is indeed that the shell is expanding the "*.txt" glob before it gets passed to find, causing problems.

The calls to find should be wrapped with quotes to prevent glob expansion, this is a BUG :)

As for adding a warning, I think maintainers will have to think about that a bit more, but we should fix the find at least :+1:

**Comment by gcapes** [comment]
Hi @hoytpr 

Thanks for the question - your understanding is correct. An explanation for this same behaviour is given in episode 3:

> When the shell sees a wildcard, it expands the wildcard to create a list of matching filenames before running the command that was asked for. As an exception, if a wildcard expression does not match any file, Bash will pass the expression as an argument to the command as it is. 

However, this isn't a bug in the lesson - only the first `find` command in episode 7 has an unquoted wildcard pattern, and this is explicitly to show why you would normally want to quote the pattern with `find`.

I think that this type of information might be best dealt with if raised via a red sticky note.

**Comment by hoytpr** [comment]
Thanks @gcapes and @gdevenyi . The episode 3 explanation is clear enough, I just didn't see it. When researching the command, this didn't come up as the expected behavior but that's likely from not putting together the correct search parameters.  

So as to not create clutter in the repo, we should close this. The red sticky note is a very good idea, I'll look for that in the future.

**Comment by gdevenyi** [comment]
Cheers @gcapes I missed the fine detail on this already being covered :)
