### ISSUE TITLE
Move "moving to the current folder" exercise in 03

### ISSUE THREAD

**Issue by lmichael107** [swcarpentry/shell-novice#1032]
Can we move https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/03-create.md#moving-to-the-current-folder to later in the lesson? Currently it comes before the most basic https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/03-create.md#moving-and-copying, and before use of mv/cp with multiple files has been introduced. Might make sense to put it with https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/03-create.md#copy-with-multiple-filenames.

I'm happy to make the change and submit the pull request if someone else agrees it's a good change(?).

**Comment by colinmorris** [comment]
Good catch! Another option would be to modify the exercise so that it only involves moving one file (`sucrose.dat`, say). The first half of the episode doesn't have many exercises, so that would be one argument for keeping the exercise where it is. But I'd be happy with a PR for either solution (moving to later, or modifying).

**Comment by ibarrass-qmul** [comment]
This has been addressed by f9386ac089?

**Comment by gcapes** [comment]
> This has been addressed by [f9386ac](https://github.com/swcarpentry/shell-novice/commit/f9386ac0893c1eb8c2d67778e0a0b65baa965f5c)?

No I don't think so. That exercise has been simplified, but the point is that this exercise comes before copying multiple files has been introduced in http://swcarpentry.github.io/shell-novice/03-create/index.html#copy-with-multiple-filenames

**Comment by deppen8** [comment]
I think this is no longer relevant? It doesn't look out of order to me anymore. 

Closing for now, but happy to re-open if I am wrong.
