### ISSUE TITLE
Invalid command for Copy with Multiple Filenames exercise

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#1034]
The command

```
$ cp amino-acids.txt animals.txt backup/
```

that is part of the exercise "Copy with Multiple Filenames" in http://swcarpentry.github.io/shell-novice/03-create/index.html doesn't work even the exercise saying

> For this exercise, you can test the commands in the data-shell/data directory.

**Comment by gcapes** [comment]
I'm not sure what you mean Rainere. Could you please give the error message and steps to recreate? I just tested that command and it worked as expected.
