### ISSUE TITLE
Discrepancy between text and figure in episode 7 

### ISSUE THREAD

**Issue by alesssia** [swcarpentry/shell-novice#1035]
The text states that the `data` folder contains three files (`LittleWomen.txt`, `one.txt`, and `two.txt`), all of which are in the `data-shell.zip` downloaded during the setup step. However, `LittleWomen.txt` is not in the diagram (file: `fig/find-file-tree.svg` in the repo).

Happy to modify the Figure to include `LittleWomen.txt`, and to submit a PR -- if everyone agrees.

**Comment by gcapes** [comment]
Sounds good to me!

**Comment by alesssia** [comment]
It seems that the SVG is composed of a single layer/object. If this is true, I would need to generate the Figure from scratch (and try to make it as similar as possible to the original and the other figures in the lesson). Is the original Figure with all its objects saved somewhere?

**Comment by gcapes** [comment]
Yes, it does look like a difficult task :( 
The figures are in the `fig` directory and it looks like the svg file might have been generated from the odg file. However, the colour and formatting are different. I wonder if @gdevenyi knows how the figures were generated?

**Comment by alesssia** [comment]
I noticed that there are only three figures depicting the filesystem. I might just re-do all of them so _a)_ they all look the same and _b)_ there will be a source file if further edits are needed. 
How does it sound? 
Hope I did not sign myself up for an even harder task 😅

**Comment by gdevenyi** [comment]
Unfortunately the figures predate me @gcapes so I think the only option now is to redo them.
