### ISSUE TITLE
Ep 4: introduce 'wc' with a single file first

### ISSUE THREAD

**Issue by chennachaos** [swcarpentry/shell-novice#1047]
Episode 4: Pipes and Filters
The word count command `wc` is introduced directly for processing a group of `*.pdb` files. I think it will be a good idea to explain the usage of 'wc' command for a single input file first.

For example, show how `wc` works for one file:

```
$ wc cubane.pdb
20  156  1158  cubane.pdb
```
following with the explanation for its output and the options, `-l`, `-w`, and `-c`.

I think this is important because for a single file, `wc` doesn't display the additional `total` line. The `total` line is displayed only if the input argument is more than one file.

**Comment by gdevenyi** [comment]
Thanks for the suggestion, I think that's a good idea.

PR is welcome to add this.

**Comment by cemacrr** [comment]
Please see pull request #1052 for my efforts at updating the content as suggested.

Let me know if further adjustments are required!

**Comment by gdevenyi** [comment]
Fixed by #1052 
Thanks!
