### ISSUE TITLE
Various scenarios of using unix shell should be demonstrated in the first section

### ISSUE THREAD

**Issue by qingfengxia** [swcarpentry/shell-novice#1053]
Some new programmers may have not realise the importance of unix shell. I suggest a few bullet points should be listed at the beginning of the course to motivate learners

+ unix shell is cross-platform, from Linux to Windows, from embedded system,  to super-computer
+ unix shell is general available on all operations systems. Windows has git-bash, Windows subsystem for Linux (WSL), Azure cloud computation.
+ unix shell is essential for high performance computation (HPC) such submit job to super computer
+ unix shell can automate your workflow, not only for software engineering such as continuous integration, but also for research, engineering design, see <https://qingfengxia.github.io/>

**Comment by gcapes** [comment]
Thanks for the issue. 

I think enough of this is already covered on the home page intro blurb: http://swcarpentry.github.io/shell-novice/. Certainly the last two points are already mentioned, and in a lesson pushed for time I think we need to keep that introduction brief.

Individual instructors are of course welcome to mention examples that would interest the specific group they are teaching.
