### ISSUE TITLE
Ep1: reword "Introducing the Shell: Background"

### ISSUE THREAD

**Issue by pawsey-kbuckley** [swcarpentry/shell-novice#1054]
Possibly, given the lack of comments in the month after I submitted
the original "issue list" [Post-Teaching Demo feedback  #1036] it's
been suggested that I separate out those issues: this is one such
seperated issue.

There are links to all of the seperated issues in the original.

I have kept the opening paragraph in for context.

I may also have corrected some typos !

    I'm submitting this "issue list", ahead of one or more PRs, as a
    result of recently performing a Software Carpentry Instructor
    Training Teaching Demo, during the preperation for the demo of
    which, I was scrutinisng the content of "The Unix Shell" lesson
    quite (some might say too) intently, and so noticed some things
    that PRs could address, assuming that the Lesson and/or Style
    coveners agree that these things are in neeed of addressing.

   - Introducing the Shell: Background

The phrase "At a high level, computers do four things" doesn't tell
the full story.

Not all computers "Store data" nor "Interact with us".

Some computers will stream data in and out, and merely "run programs"
on the data stream.

I'd like to suggest that, in the context of "Software Carpentry" and in
a "researcher-focussed context, that the phrase be changed to:

"At a high level, computers that run software to process user-supplied
 data, do most, if not all, of the following four things:"

**Comment by gcapes** [comment]
Thanks for the issue. A wise man once said that sometimes it's useful to sacrifice accuracy for clarity. So while the text isn't quite true, I think it's a clearer message than adding the caveats.

Thanks for taking the time to raise this issue.
