### ISSUE TITLE
Ep7: Clarification to "Matching and Subtracting" exercise

### ISSUE THREAD

**Issue by davemckain** [swcarpentry/shell-novice#1057]
I'm wondering if the **Matching and Subtracting** exercise in the **Finding things** episode might benefit from a bit of clarification. In particular:

> which of the following commands will find all files in /data whose names end in `s.txt` (e.g., `animals.txt` or `planets.txt`), but do not contain the word `net`?"

It's not immediately obvious to me whether "do not contain" refers to the *name* of the file, or the *contents* of the file, especially as it comes immediately after a `grep $(find ...)` example, and `planets.txt` is listed as an example of a good match for `s.txt` that would subsequently be excluded by the second condition. Perhaps a clearer alternative might be something like:

> which of the following commands will find all files in /data whose names end in `s.txt` but do not contain the string `net` (e.g., `animals.txt` or `animo-acids.txt`, but not `planets.txt`)?"

Additionally, the 3rd multiple choice option greps for the string `temp`, which does not appear to have any obvious relevance to the exercise. It would probably be more interesting to replace this with `net`?

**Comment by gcapes** [comment]
Yep, good suggestion! I think it could be reworded even more clearly though:

> which of the following commands will find all files in /data whose names end in s.txt but **whose names** do not contain the string net (e.g., animals.txt or animo-acids.txt, but not planets.txt)?"

A PR would be welcome!

**Comment by davemckain** [comment]
Good idea! I decided to add an additional "also" after the 2nd "whose name" to temper the duplication a bit. I think it reads OK now.

Here's a PR: https://github.com/swcarpentry/shell-novice/pull/1058
