### ISSUE TITLE
-c -w  in episode 4

### ISSUE THREAD

**Issue by sunyi000** [swcarpentry/shell-novice#1060]
The line before section "Why isn't it doing anything"

https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/04-pipefilter.md#why-isnt-it-doing-anything

and the line after the section are kind of repetitive.

It first says 
"The -c and -w options can also be used with the wc command, to show only the number of characters or the number of words in the files."

then after the "Why isn't it doing anything" part,  it re-iterates

"We can also use -w to get only the number of words, or -c to get only the number of characters."

**Comment by gcapes** [comment]
My bad, I didn't catch this when merging #1052. A PR would be welcome to remove this duplication.

**Comment by sunyi000** [comment]
I have just created a PR here #1061
