### ISSUE TITLE
Alt text is not descriptive for images in "Navigating Files and Directories"

### ISSUE THREAD

**Issue by laporpe** [swcarpentry/shell-novice#1063]
The alt text for the diagrams in the lesson "[Navigating Files and Directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html)" does not describe the explanatory purpose of the diagram. This issue is similar to one reported in the [r-novice-inflammation issues tab](https://github.com/swcarpentry/r-novice-inflammation/issues/372). 

My suggestion is to change the alt text for the first image ("../fig/filesystem.svg" alt="The File System" ) to "the file system is made up of a root directory that contains sub-directories titled bin, data, users, and tmp".

**Comment by gcapes** [comment]
Thanks for the issue! A pull request would be most welcome!
