### ISSUE TITLE
error in commands available for wc in pipes and filters lesson

### ISSUE THREAD

**Issue by scastanedabarba** [swcarpentry/shell-novice#1073]
The lesson for pipes and filters has the options for `wc` wrong for printing the number of lines and characters (this may be a system specific problem that I am unaware of).
The commands in the lesson are:
-1    number of lines
-c    number of characters

The correct commands are:
-l    number of lines
-m  number of characters

**Comment by gcapes** [comment]
Well spotted! Pull Request anyone?
