### ISSUE TITLE
Episode 2 include full path for ls data-shell

### ISSUE THREAD

**Issue by Astahlke** [swcarpentry/shell-novice#1075]
Quick suggestion: 

In episode 2, [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir/index.html), students could directly copy-paste the `ls -s data-shell/data` commands of line 193 and 197 if Desktop is included in the path, i.e. `ls -s Desktop/data-shell/data`. 

Thanks! 
Amanda

**Comment by gcapes** [comment]
This is actually a bug rather than just a convenience thing - the command as shown in the lesson won't work because we're still in the home directory.

**Comment by gdevenyi** [comment]
Fixed by #1077
