### ISSUE TITLE
Add sleep as an example of the Unix philosophy and use it to introduce CRTL+C

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/shell-novice#108]
When I teach the shell, usually to motivate pipes, I show the `sleep` command as an example of Unix philosophy of "small programs, loosely coupled" (or whatever goes the saying). `sleep` is a funny program and appear useless at first sight, kind of shocking compared to Microsoft Office, but very easy to understand and play with. 

After running `sleep 10` (which sleeps for 10 seconds), I "accidentally" run `sleep 100000` or some other ridiculous number. This gives me the chance to introduce `CTRL+C` as the way to kill a command. This is useful later in the lesson when people gets trapped in loops or other commands that go wrong.

I think a short paragraph, maybe in a call out, would be nice in one of the first 3 parts of this lesson.

What do you think? If people agrees, I could do a PR, but actually I prefer to leave it for a newcomer.

**Comment by gvwilson** [comment]
*   +1 to having a newcomer do it.
*   -1 to including this in the novice lesson -- it's not useful to 
scientists right away.
*   +1 to including it in shell-extras along with job control or cron.

Thanks,
Greg

**Comment by r-gaia-cs** [comment]
@iglpdc My suggestion is change a little our starting point to something like

> Nelle Nemo, a marine biologist, has just returned from a six-month survey of the North Pacific Gyre, where she has been sampling gelatinous marine life in the Great Pacific Garbage Patch. She has 300 samples that still in Great Pacific Garbage Patch's server since her laptop broken during the return. One college from Nelle's lab helps getting all the 300 samples with
>
> ~~~
> for i in $(seq 1 300)
> do
> wget http://someaddress.com/${i}
> sleep 10
> done
>
> that only takes a few minutes instead of hours if Nelle goes clicking one by one with the mouse.
>
> The `sleep` command was needed because the server only accept a few request per minute.
>
> Now, Nelle has to analyses her data using some programs. Based on the experience of downloading her data she decided to learn a little about the Unix shell to save a lot of time since ... 

And add a note at instructors note that they should mention `CTRL+C` when running this example.

**Comment by gvwilson** [comment]
In shell-extras, +1, but definitely not in shell-novice: we're not going 
to try go introduce seq, wget, and ${i}.

On 2015-03-19 3:30 PM, Raniere Silva wrote:
>
> @iglpdc <https://github.com/iglpdc> My suggestion is change a little 
> our starting point to something like
>
>     Nelle Nemo, a marine biologist, has just returned from a six-month
>     survey of the North Pacific Gyre, where she has been sampling
>     gelatinous marine life in the Great Pacific Garbage Patch. She has
>     300 samples that still in Great Pacific Garbage Patch's server
>     since her laptop broken during the return. One college from
>     Nelle's lab helps getting all the 300 samples with
>
>     |for i in $(seq 1 300)
>     do
>     wget http://someaddress.com/${i}
>     sleep 10
>     done
>
>     that only takes a few minutes instead of hours if Nelle goes clicking one by one with the mouse.
>
>     The `sleep` command was needed because the server only accept a few request per minute.
>
>     Now, Nelle has to analyses her data using some programs. Based on the experience of downloading her data she decided to learn a little about the Unix shell to save a lot of time since ...
>     |
>
> And add a note at instructors note that they should mention |CTRL+C| 
> when running this example.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/shell-novice/issues/108#issuecomment-83731861>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
