### ISSUE TITLE
Be more explicit about which environments lack which help options (Ep. 2)

### ISSUE THREAD

**Issue by timspainUCL** [swcarpentry/shell-novice#1082]
In the section [Getting Help](http://swcarpentry.github.io/shell-novice/02-filedir/index.html#getting-help) of [Navigating Files and Directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html), there is a note that some environments lack one or other of the `ls` help options.
I think this should be more explicit, for example mentioning that MacOS lacks the `--help` option and that Windows git bash has no `man` pages. When I last taught this lesson, it tripped up the flow of the lesson, with me not realising MacOS lacked `--help` whilst live coding and questions from some of the learners using git bash.

**Comment by gcapes** [comment]
Thanks for raising this issue. There has been lots of discussion about how to deal with differences in Bash implementations, trying to balance giving information which will help learners without overloading the lesson with notes on exceptions. See #798.
As such I think a *brief* note to this effect would be useful.

**Comment by sheraaronhurt** [comment]
this is a test

**Comment by jsteyn** [comment]
Would it not help to create a table of options vs. operating systems, eg
<table>
<tr><td>Command/Option</td><td>Linux</td><td>Mac</td><td>Windows</td></tr>
<tr><td>man</td><td>yes</td><td>yes</td><td>no</td></tr>
<tr><td>ls --help</td><td>yes</td><td>no</td><td>yes</td></tr>
</table>
The table can be placed at the end of the lesson or on a completely separate page, with a link to it, so as not to overload the lesson with notes. I think this would even be handy for instructors as not not everybody is familiar with all the operating system.

**Comment by langk** [comment]
> 
> 
> Would it not help to create a table of options vs. operating systems, eg
> Command/Option	Linux	Mac	Windows
> man	yes	yes	no
> ls --help	yes	no	yes
> The table can be placed at the end of the lesson or on a completely separate page, with a link to it, so as not to overload the lesson with notes. I think this would even be handy for instructors as not not everybody is familiar with all the operating system.

I think the suggested table will be helpful for students and instructors as a reminder on the different behavior. Adding this to the lesson will definitely help avoiding confusion.

**Comment by gcapes** [comment]
Fixed in #1089 e264bac9ed7cf1
