### ISSUE TITLE
episode 2: add command args/options to objectives?

### ISSUE THREAD

**Issue by monicathieu** [swcarpentry/shell-novice#1083]
Hi folks,

As of issue posting, the first time that a shell command is introduced with flags/options and arguments is [episode 2](../blob/gh-pages/_episodes/02-filedir.md). The section explaining what flags and arguments do + their expected syntax and order is solid, but may sneak up on the instructor (and the students). Since command flags and arguments appear very frequently in subsequent lessons, I think it's important to foreground this concept in the episode objectives. Something like:

- Use flags and arguments to change the behavior of a shell command

could do the trick.

Related to/inspired by the following open PR (relevant comment below):
>Perhaps this question could be rephrased as "How does using flags and options change the behaviour of a shell program?"
>Flags and options do not change a shell program in terms of its content. By specifying "behaviour", we could reduce the confusion a learner may have over what flags and options do.

_Originally posted by @uoa-noel in https://github.com/swcarpentry/shell-novice/pull/992_

**Comment by gcapes** [comment]
Thanks for bringing this out of that longer discussion.
