### ISSUE TITLE
Setup procedure for Windows: which one to follow?

### ISSUE THREAD

**Issue by wirawan0** [swcarpentry/shell-novice#1086]
Folks,

This issue is specific for Windows OS. Currently "Git for Windows" is the recommended solution. I noted a few days ago that there is a notable difference between the setup procedure on shell-novice lesson (https://swcarpentry.github.io/shell-novice/setup.html#windows) and that written in the Workshop template page (http://carpentries.github.io/workshop-template/#setup) . The workshop template specifically mentions Git for Windows with detailed instructions. I wonder if the specific instructions mentioned there are important enough: (quoted here for convenience)

> 1. Click on "Next" four times (two times if you've previously installed Git). You don't need to change anything in the Information, location, components, and start menu screens.
> 2. **From the dropdown menu select "Use the nano editor by default" and click on "Next".**
> 3. Ensure that "Git from the command line and also from 3rd-party software" is selected and click on "Next". (If you don't do this Git Bash will not work properly, requiring you to remove the Git Bash installation, re-run the installer and to select the "Git from the command line and also from 3rd-party software" option.)
> 4. Ensure that "Use the native Windows Secure Channel library" is selected and click on "Next".
> 5. Ensure that "Checkout Windows-style, commit Unix-style line endings" is selected and click on "Next".
> 6. **Ensure that "Use Windows' default console window" is selected and click on "Next".**
> 7. Ensure that "Enable file system caching" and "Enable Git Credential Manager" are selected and  click on "Next".
> 8. Click on "Install".
> 9. Click on "Finish".

The boldface was part of that instruction. All the choices look reasonable to me. These are not mentioned on the "shell-novice" setup procedure. Some instructions are pertinent to Git, not bash (points 3 & 5 & 7); but still it is good to have one kind of setup that is consistent for the bash and Git lessons. (I am not familiar with the choice made in points 4 and 6, not sure what implication it has.)

**Question**: How important are these details? It would be nice to have setup instructions consistent between this lesson (shell-novice) and the Workshop template. At least for the recommended one (currently Git for Windows).

Wirawan

**Comment by gdevenyi** [comment]
The extras for git for windows in the template are so the git lesson works I suspect.

Windows continues to be a disaster for providing a uniform learning environment compared to the *nixes. We should probably do some more uniformizing. I didn't know the template had setup instructions as well...

**Comment by clbarb** [comment]
In the Windows instructions it says "it is likely you have already received instructions on how to install Git for Windows".  Would it be possible to make "install Git for Windows" a link and have it direct back to the workshop template version of the install directions or a different version with the instructions that aren't necessary (4&6) not included and create a pop out set of instructions similar to the workshop template version.

**Comment by gcapes** [comment]
There doesn't look to be any consistency across the lessons as to whether installation instructions are given, linked to, or not given at all. It would be good to have instructions in one place, and to link to the workshop template, this is the URL:
https://carpentries.github.io/workshop-template/#shell

However, as mentioned above, these instructions are lengthy but not explained, and some of the choices seem unimportant. 
Point 6 above (Use Windows' default console) isn't explained, but is probably to make launching other programs (such as python) easier, so useful for the other lessons.
The choice of the text editor is the only key choice that is important (for Git).

I would be in favour of having some simplified instructions in the shell repo. Something like 'Install git for windows, accepting all the defaults except for the text editor. Select Nano for this.' 
We can also mention Windows subsystem for Linux, and get rid of the rest of the text.

I can submit a PR if required.

**Comment by ErinBecker** [comment]
Thanks @wirawan0 for raising this issue and @gdevenyi @clbarb @gcapes for this discussion. 

I'm bringing this issue to our next Carpentries Curriculum Team staff meeting, as we've been doing some thinking about how to make sure installation instructions stay clear and consistent across all of our lessons. We meet on Tuesdays and will follow-up on this issue asap.
