### ISSUE TITLE
Introduce "clear" command in Ep4 Pipes and filters

### ISSUE THREAD

**Issue by supriya-khedkar** [swcarpentry/shell-novice#1091]
At present the lesson does not include "clear" command. Ep4 Pipes and filters immediately after "cat" command would be a good place in the lesson for this. Introduction of this command will not only help the learners clear their screen of text and previously used commands but also will aid the teacher during live coding session (By avoiding the commands that are being typed from being displayed at the bottom of the screen. There is a possibility that the bottom of the screen might not be visible to learners at the back of the room)

**Comment by gcapes** [comment]
Hi @supriya-khedkar 
Please could you add your thoughts to issue #784 
Thanks
