### ISSUE TITLE
Difficulty navigating to 'data-shell' in Setup

### ISSUE THREAD

**Issue by eosborn** [swcarpentry/shell-novice#1092]
[link to cited page](http://swcarpentry.github.io/shell-novice/setup.html)

I recently taught part of the Intro to Unix starting from the Setup, and the non-mac learners had considerable issues downloading the zip file and getting it onto their desktop. Some learners didn't even have a Desktop directory and so we needed to create. 

I felt like this was a bad note to start the lesson on, and I am wondering if there is a more universal location the lesson files can be placed, with the understanding that it is probably best that the file isn't simply left in the learners' Download file. 

Thank you!

**Comment by gcapes** [comment]
Sorry to hear you had trouble - which OS/shell environment had the problems?

**Comment by gcapes** [comment]
Closing stale issue
