### ISSUE TITLE
[submitted via email] possible mistake in solution for challenge "tracking a species"

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/shell-novice#1095]
> Thank you very much for the excellent. "Software Carpentry lessons". It's super helpful.
> Writing to you to talk about something about the "Solution" of 'Tracking a Species' in the "Finding Things" part of "The Unix Shell". 
> The code, `grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt` , should be `grep -w $1 -r $2 | cut -d , -f 1,3  > $1.txt`. I am confused with the effect of ` cut -d : -f 2`, or it's just a small mistake.

**Comment by gcapes** [comment]
`-d :` specifies `:` as the delimiter. `-f 2` selects the second column.
Try building up the pipeline one section at a time e.g.
```
$ grep -w rabbit -r .
./animals.txt:2012-11-05,rabbit,22
./animals.txt:2012-11-06,rabbit,19
./animals.txt:2012-11-07,rabbit,16
```

```
 $ grep -w rabbit -r . | cut -d : -f 2 
2012-11-05,rabbit,22
2012-11-06,rabbit,19
2012-11-07,rabbit,16
```
