### ISSUE TITLE
Episode 2: Getting help: Add third option `info` command 

### ISSUE THREAD

**Issue by hafu** [swcarpentry/shell-novice#1098]
To get help of a command there exists also a third option; the `info` command. I suggest to add this to the list of options and add a description of the command like done with `man`.

Maybe it is not so common like the `--help` option and the `man` command, but it contains a more verbose output and helps to understand command options.

```
$ ls --help
$ man ls
$ info ls
```

I would discuss this issue, because the command is not so common. I also can create a pull request if you think it is worth to add.

**Comment by myoungblom** [comment]
Having compared the output of both `info` and `man` they seem basically identical – one does not provide more information than the other. If people think `info` is easier to remember than `man` the lesson could be changed. However, I see no reason to add them both, this is an unnecessary addition that I think would only confuse learners.

**Comment by gcapes** [comment]
Thanks for the suggestion.
Like `man`, `info` doesn't work on Git Bash, and is the least commonly used way to get help with commands (in my experience anyway). So I think we do without it.
Thanks again for contributing.
