### ISSUE TITLE
 Episode 6:  Explicitly describe special variables $2 and $3 upon introduction. 

### ISSUE THREAD

**Issue by kcshocker** [swcarpentry/shell-novice#1107]
In [Episode 6: Shell Scripts](https://swcarpentry.github.io/shell-novice/06-script/index.html) of the Unix Shell, there is a line that reads "Let’s fix that by using the special variables $2 and $3 for the number of lines to be passed to head and tail respectively:".  

When I was learning this and first reading the episode, I really struggled to understand what that meant.  It would have been helpful to include a line like "$2 and $3 refers to the second and third filenames (or other arguments) on the command line."  I know it was explained a bit earlier in the episode when $1 was introduced, but this is such a tricky concept to grasp it would be beneficial to spell it out for $2 and $3 as well.  

Any other content that could be included to explicitly explain how each special variable connects to information (like filenames) in the command line would be really helpful.  I spent way too long trying to figure it out as written.

Thanks for considering!

**Comment by gcapes** [comment]
Great suggestion. PR welcome!
