### ISSUE TITLE
Reframing Nelle's Pipeline Narrative

### ISSUE THREAD

**Issue by mhamilt** [swcarpentry/shell-novice#1112]
# Reframing _Nelle's Pipeline_ Narrative

I think it may be worthwhile tweaking the framing narrative of _Nelle's Pipeline_ a little so that it is more upfornt with what the task at hand is. It is also a great opportunity to demonstrate breaking down programming problems, which is not just good for learning shell, but any any programming language.

## Nelle's Actual Task

_Nelle's Pipeline_ is introduced in the first lesson and it gives the impression that her actual task is simply running files through `goostats`. As the lessons go on more complexity is introduced. Spread across the lessons, Nelle's actual task involves:

> 1.  [\[create\] a directory called north-pacific-gyre which contains a directory of the date she collected data](https://swcarpentry.github.io/shell-novice/02-filedir/index.html#nelles-pipeline-organizing-files)
> 2.  [\[check\] to see if any files have too much data](https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html#nelles-pipeline-checking-files)
> 3.  [Select the right input files](https://swcarpentry.github.io/shell-novice/05-loop/index.html#nelles-pipeline-processing-files)
> 4.  [capture all the steps ... in a script.](https://swcarpentry.github.io/shell-novice/06-script/index.html#nelles-pipeline-creating-a-script)

## Breaking Down the Problem

Broken down into actual tasks relating to the lessons

1.  How to navigate to a file / directory: [Introducing shell](https://swcarpentry.github.io/shell-novice/01-intro/index.html) / [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir/index.html)
2.  how to create a file / directory: [Working With Files and Directories](https://swcarpentry.github.io/shell-novice/03-create/index.html)
3.  how to check file length: [Pipes and Filters](https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html)
4.  how to chain processes together: [Pipes and Filters](https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html)
5.  remove uneeded files [Pipes and Filters](https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html)
6.  retrieve a set of files: [Working With Files and Directories (wildcards)](https://swcarpentry.github.io/shell-novice/03-create/index.html#wildcards)
7.  iterate over files [Loops](https://swcarpentry.github.io/shell-novice/05-loop/index.html)

## Pipeline Reframed

It might be worth stating the above tasks at the first introduction to _Nelle's Pipeline_. I think this might make the focus of the lessons a little more explicit.

>## Nelle's Pipeline: A Typical Problem
>
>Nelle Nemo, a marine biologist,
>has just returned from a six-month survey of the
>[North Pacific Gyre](http://en.wikipedia.org/wiki/North_Pacific_Gyre),
>where she has been sampling gelatinous marine life in the
>[Great Pacific Garbage Patch](http://en.wikipedia.org/wiki/Great_Pacific_Garbage_Patch).
>She has 1520 samples that she's run through an assay machine to measure the relative abundance of 300 proteins.
>She needs to run these 1520 files through an imaginary program called `goostats` she inherited.
>On top of this huge task, she has to write up results by the end of the month so her paper can appear in a special issue of _Aquatic Goo Letters_.
>
>The bad news is that if she has to run `goostats` by hand using a GUI,
>she'll have to select and open a file 1520 times.
>If `goostats` takes 30 seconds to run each file, the whole process will take more than 12 hours of Nelle's attention.
>With the shell, Nelle can instead assign her computer this mundane task while she focuses her attention on writing her paper.
>
>
>The next few lessons will explore the ways Nelle can achieve this.
>More specifically,
>they explain how she can use a command shell to run the `goostats` program,
>using loops to automate the repetitive steps of entering file names,
>so that her computer can work while she writes her paper.
>
>As a bonus,
>once she has put a processing pipeline together,
>she will be able to use it again whenever she collects more data.
>
>**In order to achieve her task, Nelle must solve the following problems**
>1.  **How to navigate to a file / directory**
>2.  **How to create a file / directory**
>3.  **How to check file length**
>4.  **How to chain processes together**
>5.  **Remove uneeded files**
>6.  **Retrieve a set of files**
>7.  **Iterate over files**

The wording and placement is not perfect so it would be interesting hear other opinions on this.

**Comment by gcapes** [comment]
Thanks for the suggestion. I like it. Shouldn't add very much time to the lesson either.

**Comment by gcapes** [comment]
I wonder whether we should rethink the whole 'Nelle' character. Ep 1 already talks about an *imaginary* program, `goostats.sh`. Why not make the whole thing explicitly imaginary?

> ## Processing data: A typical problem
> Imagine you're a marine biologist, just returned from ....

or 

> You're a marine biologist, just returned ...
