### ISSUE TITLE
-help command and man both not working

### ISSUE THREAD

**Issue by suryanshrajput** [swcarpentry/shell-novice#1113]
Yup, no `man` with Git Bash. I try to remember to note this for students and tell them about `<command> --help` instead.

_Originally posted by @jiffyclub in https://github.com/swcarpentry/shell-novice/issues/249#issuecomment-158466299_

**Comment by gcapes** [comment]
I'm not clear what the purpose of this issue is. Could you please clarify? 

Which options (don't) work on which OS is covered here:
http://swcarpentry.github.io/shell-novice/02-filedir/index.html#getting-help

**Comment by gcapes** [comment]
Closing stale issue
