### ISSUE TITLE
Using common conventions in lesson materials when providing abstract or incomplete code examples.

### ISSUE THREAD

**Issue by casepie** [swcarpentry/shell-novice#1120]
During most of our lesson materials and essentially all of our live coding, we are dealing with very literal instructions.  By that I mean ls -r means type exactly that.  However, occasionally, we wade into the more abstract voice.  An example of this is found in the "Key points" section of the [Unix Shell Navigating Files and Directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html) episode.  The text reads:  

**cd path changes the current working directory.
ls path prints a listing of a specific file or directory; ls on its own lists the current working directory.**

Here, we don't actually intend for the learner to type "ls path", but instead the word path is a parameter or argument to the command that is a placeholder for variable text or input.  I'd suggest we use common convention here to indicate as much.  example text changed is below:

**cd [path] changes the current working directory.
ls [path] prints a listing of a specific file or directory; ls on its own lists the current working directory.**

There are likely other examples, but this is the one that jumped out at me.  Thoughts?

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by gcapes** [comment]
Yes, I like this idea. I'm not sure there is *one* convention for this sort of thing, so we probably just have to pick one (square brackets, angle brackets etc) and stick with it. However I think it might well need explaining if it is used in the main body of the lesson rather than just in the key points at the end of an episode. Some novices take things very literally or get into copy-without-thinking mode and do things like `ls path/to/file` rather than substituting an actual path.

**Comment by casepie** [comment]
I would agree that, ideally we'd need to be consistent throughout the lessons (or at least from lesson to lesson since the curriculum is rather large) in what convention we use.  I also think it might be a good idea to put a small table explaining this, and some other common conventions and shorthand learners may see throughout the day.  Not necessarily as part of the teaching, but maybe as a "notation box" in the [main page](http://swcarpentry.github.io/shell-novice/)?

**Comment by gdevenyi** [comment]
This is an awesome idea! There is in-fact a convention for how to read/describe options for a command in POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
