### ISSUE TITLE
including $ll command as another option of $ls -l

### ISSUE THREAD

**Issue by LandiMi2** [swcarpentry/shell-novice#1122]
Including $ll command in explaing $ls -l command 

ll is aliased to `ls -l', this is simplified version especially for novices in the command-line.

**Comment by gdevenyi** [comment]
Hi @LandiMi2. Thanks for the suggestion, however this alias is far from universal and aliases are a topic outside of the scope of a novice lesson, the cognitive load of comparing a command vs an alias will add too much complication. Perhaps a lesson on aliases would be good for shell-extras

**Comment by LandiMi2** [comment]
Yeah sure that would be good lesson. Makes typing life easy for specific day to day commands.
