### ISSUE TITLE
segue into wc command

### ISSUE THREAD

**Issue by amritkar** [swcarpentry/shell-novice#1124]
After directory creation using `mkdir`, the material directly jumps into `wc` command and there is no smooth transition like why `wc` and why here. I'd like to suggest a small change - instead of saying "run the command `wc cubane.pdb`" how about "run an example command `wc cubane.pdb`"? This would clarify that we are providing an example command which happens to be wc. I feel this would offer smoother segue to `wc`. What do you think?

**Comment by gdevenyi** [comment]
Thanks for the suggestion, we would welcome a PR to cleanup the transition between these sections!

**Comment by aecryan** [comment]
On it! I just made the change and submitted a pull request.
