### ISSUE TITLE
Ep. 4 Pipes and Filters suggestion: Add subheadings

### ISSUE THREAD

**Issue by dmangosi** [swcarpentry/shell-novice#1125]
As a helper, this is an episode that is relatively long and by my observation, is typically the one that trips students up a bit. It's a shame too because this is where the power of Unix is supposed to shine.

As a way of breaking up the tutorial into logical sections (and putting in breaks for reflection and questions), I propose that the episode be broken up (without changing the content) into logical sub-sections, as was done in the _Working with Files and Directories_ episode:

1. Building a command pipeline
1. Creating a pipe (pipeline)
1. Nelle’s Pipeline: Checking Files

I also think the key points should list the commands that were used in the order that they were introduced:

- **wc** counts lines, words, and characters in its inputs.
- **cat** displays the contents of its inputs.
- **sort** sorts its inputs.
- **head** displays the first 10 lines of its input.
- **tail** displays the last 10 lines of its input.
- **command > file** redirects a command’s output to a file (overwriting any existing content).
- **command >> file** appends a command’s output to a file.
- **first | second** is a pipeline: the output of the first command is used as the input to the second.
- The best way to use the shell is to use pipes to combine simple single-purpose programs (filters).

**Comment by gcapes** [comment]
I like the idea of some more headings to break things up. However your suggestions for 1. and 2. read the same to me. 

I've not found the right words yet either but I suggest something along the lines of 
1. reusing output from commands using multiple steps
2. combining commands in a single step

**Comment by dmangosi** [comment]
Yes, I guess I was "thinking" about the same thing you stated,but didn't quite come up with the right words either.  ;-)   How about this:

1. Redirecting and capturing output from commands
1. Redirecting the output commands as input to other commands using the pipe (|) operator
1. Combining multiple commands in a single step (creating a pipeline)

**Comment by gcapes** [comment]
I like these (well ... shortened versions)
perhaps:
1. Capturing output from commands
2. Passing output to another command
3. Combining multiple commands
4. as before
5.  as before

**Comment by dmangosi** [comment]
I like it ;-)

**Comment by gcapes** [comment]
Great, I think this will be a nice improvement :)
