### ISSUE TITLE
 Episode 3 : add `mkdir -p`

### ISSUE THREAD

**Issue by d-ave-g** [swcarpentry/shell-novice#1133]
Dear Carpentries Community,

Please find below proposed modifications to "The Unix Shell", Episode 3 ("Working With Files and Directories").

If you feel that these proposed modifications have merit, and would prefer a different approach, a different scope, different verbiage, etc., please share your thoughts and suggestions.

Your feedback is greatly appreciated and will help me learn and grow.  Thanks in advance!

Take care, be well, stay well, and have a great day.

Regards,
Dave George

<hr>

### Proposed Modifications to "The Unix Shell" -> Episode 3 ("Working With Files and Directories") ###

<hr>

**SUMMARY:** A proposal to modify the "Working With Files and Directories" episode to include a reference to the -p option flag of the mkdir command in two separate segments of the episode: the "Create a Directory" segment, and the "Reproduce a folder structure" exercise segment.

**RATIONALE:** The mkdir command supports the -p option flag, which automagically creates any required but missing directories passed as an argument to mkdir - an **_AMAZING_** time saver!   Instead of having to type "mkdir dir1; cd dir1; mkdir subdir1; cd subdir1; mkdir subdir2" to create a directory hierarchy, one can type "mkdir -p dir1/subdir1/subdir2" instead.

Perhaps equally important, the current verbiage in the exercise segment leaves the student with the impression that "mkdir won't create a subdirectory of a non-existent directory: the intermediate level folders must be created first" when that powerful functionality does, in fact, already exist, and can be invoked with the -p option flag.

**NOTE:** The current verbiage of the two segments follows exactly, with the proposed modifications prepended with "PROPOSED MODIFICATION OF THE SENTENCE ABOVE:" or "PROPOSED ADDITION:"

<hr>

### Create a directory ###

Let's create a new directory called thesis using the command mkdir thesis (which has no output):

$ mkdir thesis
As you might guess from its name, mkdir means 'make directory'. Since thesis is a relative path (i.e., does not have a leading slash, like /what/ever/thesis), the new directory is created in the current working directory:

$ ls -F
creatures/  data/  molecules/  north-pacific-gyre/  notes.txt  pizza.cfg  solar.pdf  thesis/  writing/

**PROPOSED ADDITION:** Note that mkdir is not limited to creating single directories one at a time.  The -p option allows mkdir to create a directory with any number of nested subdirectories in a single operation!  For example, mkdir -p thesis/chapter_1/section_1/subsection_1 will create that entire directory hierarchy within the current directory.

<hr>

### Reproduce a folder structure ###

You're starting a new experiment, and would like to duplicate the directory structure from your previous experiment so you can add new data.

Assume that the previous experiment is in a folder called '2016-05-18', which contains a data folder that in turn contains folders named raw and processed that contain data files. The goal is to copy the folder structure of the 2016-05-18-data folder into a folder called 2016-05-20 so that your final directory structure looks like this:

2016-05-20/
└── data
    ├── processed
    └── raw

Which of the following set of commands would achieve this objective? What would the other commands do?

Bash
$ mkdir 2016-05-20
$ mkdir 2016-05-20/data
$ mkdir 2016-05-20/data/processed
$ mkdir 2016-05-20/data/raw

Bash
$ mkdir 2016-05-20
$ cd 2016-05-20
$ mkdir data
$ cd data
$ mkdir raw processed

Bash
$ mkdir 2016-05-20/data/raw
$ mkdir 2016-05-20/data/processed

**PROPOSED ADDITION:** Bash
**PROPOSED ADDITION:** mkdir -p 2016-05-20/data/raw
**PROPOSED ADDITION:** mkdir -p 2016-05-20/data/processed

Bash
$ mkdir 2016-05-20
$ cd 2016-05-20
$ mkdir data
$ mkdir raw processed

### Solution ###

The first two sets of commands achieve this objective. The first set uses relative paths to create the top level directory before the subdirectories.

_ORIGINAL SENTENCE:_ The third set of commands will give an error because mkdir won't create a subdirectory of a non-existent directory: the intermediate level folders must be created first.

**PROPOSED MODIFICATION OF THE ORIGINAL SENTENCE ABOVE:** The third set of commands will give an error because the default behavior of mkdir will not create a subdirectory of a non-existent directory: the intermediate level folders must be created first.

**PROPOSED ADDITION:** The fourth set of commands achieve this objective.  Remember, the -p option flag, followed by a path of directories/subdirectories, will cause mkdir to create any intermediate directories (aka subdirectories) as required.

The final set of commands generates the 'raw' and 'processed' directories at the same level as the 'data' directory.

**Comment by gdevenyi** [comment]
I believe this kind of topic has been mentioned before and at some points at least #890 and related issues.

I would welcome a PR to show how you propose to modify the lesson.

**Comment by gcapes** [comment]
This has since been implemented in #1187 and previous.
