### ISSUE TITLE
Potentially confusing filename: data-shell.zip

### ISSUE THREAD

**Issue by PabRod** [swcarpentry/shell-novice#1141]
Some students may think that the file `data-shell.zip`, required in the [setup](http://swcarpentry.github.io/shell-novice/setup.html), contains the shell itself.

Renaming it to `data.zip`, `toy-data.zip` or something in this direction may solve this minor issue.

**Comment by gdevenyi** [comment]
The "shell" component is there to identify it as the data for the shell lesson. If learners are following the setup instructions that should explain its contents appropriately.

@gcapes thoughts?

**Comment by gdevenyi** [comment]
In addition #1139 is reorganizing setup.md to make things more clear. Do those changes alleviate your concerns?

**Comment by PabRod** [comment]
Thanks for taking this into consideration. 

I would not call it a concern. It is just a suggestion... and as such, I will happily accept a _"we don't really agree"_ as an answer :)

**Comment by gcapes** [comment]
The instructions seem clear enough to me, though the name of the file itself could be better (nothing objective in that, just my opinion). Were I to be naming this zip file I would call it something like `shell-lesson-data.zip`
Has this confusion actually arisen or is it hypothetical?

**Comment by PabRod** [comment]
Actually... something in between arisen and hypothetical: 

The last time we gave this lesson, a student asked for _"where to download the shell"_. The confusion was solved in a matter of seconds (because the instructors were there), but certainly would have taken the student a bit more of time provided he was doing the setup alone.

**Comment by korbinib** [comment]
I would like to support the idea to rename it to `shell-lesson-data.zip` as this avoids any ambiguity. I would even support using something like `swc-shell-lesson-data.zip` as it demonstrated better file naming practise.

**Comment by gcapes** [comment]
I'm part-way through addressing this and have some ideas I'd like feedback on.
The lesson repo has some directories I'm unsure about. The data is contained in `data-shell`, which I think we should rename to `shell-lesson-data`. 
There is a `data` directory which contains a zip file of `data-shell`. There is an empty `files` directory. What is the purpose of this, and should the zip file live there instead? There isn't really any consistency here over the 3 lessons I maintain. Make has the zip file in the `files` directory, MATLAB has it in the `data` directory which also contains the files in the zip file.
There is a `filesystem` directory which looks to model the computer that the lesson is built around. I can't find any reference to this anywhere in the Makefile. Do we need to keep that?

**Comment by gdevenyi** [comment]
> There is an empty files directory. What is the purpose of this, and should the zip file live there instead? 

The fact that there's no consistency means maybe this should be bumped up to the full maintainer group to decide on standardization.

> There is a filesystem directory

That's from the deep history of this lesson and can go.
