### ISSUE TITLE
Unclear Explanation - Copying Files

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/shell-novice#1142]
Sharing some feedback we received via email.

---

I am referring to this tutorial in this email:
http://swcarpentry.github.io/shell-novice/03-create/index.html
I wanted to point out that I found the beginning explanation of cp when used to copy one file to another file difficult to understand. until I went and read about it elsewhere. I think you need to make it clear that when copying one file to another, no copies are made or names changed, rather the contents are simply transferred from file A to file B.

**Comment by InternationalSanitiser** [comment]
https://modulesunraveled.com/command-line-beginners/copying-and-deleting-files-cp-and-rm-commands
here is where I found a better explanation of cp

**Comment by gdevenyi** [comment]
Thanks for the feedback @Talishask. 

After reading over the lesson and the feedback, I'm not quite sure what the person is expressing. Since this feedback was provided via email, I can't ask any followup questions here. Could you please encourage them to join in this discussion here. Thanks.

**Comment by gcapes** [comment]
Closing stale issue.
