### ISSUE TITLE
Going to a previous working directory in a terminal

### ISSUE THREAD

**Issue by awoonor** [swcarpentry/shell-novice#1147]
As part of the instructor training checkout procedure, trainees are required to submit a small contribution to one of the carpentries lesson.

Going over the [Unix shell ](http://swcarpentry.github.io/shell-novice/) lesson, the episode on [navigating files and directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html)  provides a shortcut for moving up one directory level ("cd .."). In fact, this command is useful when one wants to access a previously visited directory in the folder tree. However, if one wants to access a previous folder/directory that is not directly one level up in the folder tree, this command does not achieve the intended task (or requires multiple iterations in order to work).

I think it would be useful to introduce the "cd -" command in the lesson, which is a shortcut for accessing a previously working directory in the terminal, irrespective of whether that directory is above or beneath your current working directory.

**Comment by gcapes** [comment]
Hi @awoonor ,

Thanks for the issue, but `cd ` is already covered in the episode at http://swcarpentry.github.io/shell-novice/02-filedir/index.html#two-more-shortcuts

**Comment by awoonor** [comment]
Hi @gcapes ,

You are right that "cd" is already covered in the episode. I was referring to introducing a shortcut "cd -" to jump across directories previously accessed.

**Comment by gcapes** [comment]
Sorry I see the formatting of my message was incorrect. Apologies. I've fixed it now.

**Comment by awoonor** [comment]
No worries @gcapes . Thanks for directing me to it. Surprisingly, I missed it when reviewing the lesson.
