### ISSUE TITLE
Add mention of explainshell.com to notes

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#115]
Because http://explainshell.com is cool.

**Comment by wking** [comment]
On Fri, Apr 03, 2015 at 04:04:41AM -0700, Greg Wilson wrote:
> Because http://explainshell.com is cool.

That is awesome :).

**Comment by gvwilson** [comment]
If you have time on your hands, something like it for SQL would be 
*awesome*.

**Comment by ChristinaLK** [comment]
addressed in #145
