### ISSUE TITLE
Include an example for using 'cd -' for going to the previous directory

### ISSUE THREAD

**Issue by kevswanberg** [swcarpentry/shell-novice#1154]
http://swcarpentry.github.io/shell-novice/02-filedir/index.html

Relevant section `Two More Shortcuts` shoutout

The explanation that exists on the page is correct but might not illustrate that it only keeps track of the previous one so running it twice doesn't go through your history, but instead puts you back where you were.

**Comment by gcapes** [comment]
Yes, it's a bit like 'undo' in Windows 95. A PR with a line encouraging the learner to try it would be welcomed!

**Comment by Archana-osu** [comment]
I agree. Explaining the cd - in more detail would be useful here. cd - is a very helpful command where it takes you to the parent directory where we typed our cd earlier. Some examples for using cd - would be helpful here.

**Comment by archanaydv** [comment]
I agree. Explaining the cd - in more detail would be useful here. cd - is a very helpful command where it takes you to the parent directory where we typed our cd earlier. Some examples for using cd - would be helpful here.

**Comment by nailabc** [comment]
That's a good suggestion and in fact, they already say that in "This is a very efficient way of **moving back and forth** between directories" and I think they tried to illustrate as well when they compare to the Last Channel button on a TV remote, but maybe not everyone is familiar with TV remote anymore...

Therefore I suggest highlighting the "**moving back and forth**" expression in bold and adding a complement to the TV remote note like this:

`You can think of it as the Last Channel button on a TV remote: it put you in the channel you previously were and if you try it twice it moves you back to where you were before pressing the button.`

**Comment by helenehoffmann** [comment]
I forked the repo and send a pull request on this. How can I link this to the issue?

**Comment by gcapes** [comment]
In a commit message, or in the PR description you can use  `fix #1154`

**Comment by helenehoffmann** [comment]
Thanks, worked
