### ISSUE TITLE
Lesson contribution – instructor checkout 

### ISSUE THREAD

**Issue by Me6me82** [swcarpentry/shell-novice#1168]
Suggestion for The Unix Shell Lesson 

- **Navigating Files and Directories episode** 
After introducing the ls command it could be useful to introduce how to save file path as variable like :
ls -s Desktop/data-shell/data
my_data=Desktop/data-shell/data
ls -s $my_data

- **Pipes and Filters episode**
It is good to introduce the \ (backslash) when several Pipes will be used to have shorter lines 
 introducing more Wildcards can be helpful especially [!] or [^], a link to  read more about Wildcards will help to know more (https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm)

- **Finding Things**
explaining different arguments of grep command 
grep -n -w -v "the" haiku.txt
can be also
 grep -nwv "the" haiku.txt

**Comment by gdevenyi** [comment]
Hi. Thanks for the suggestions.

We would welcome a PR proposing changes to the lesson.

**Comment by gcapes** [comment]
Closing stale issue. If there is still interest in this, it can be reopened.
