### ISSUE TITLE
Lesson contribution – instructor checkout

### ISSUE THREAD

**Issue by MFAKhan** [swcarpentry/shell-novice#1172]
I feel that the following commands/content can be useful for this Shell Novice lesson:

1. ***Lesson - Working with Files and Directories:*** Show how to ***create multiple sub-folders*** for each folder in a single command; and also ***adding Tree command*** in the Shell Novice curriculum
    a. Creating multiple directories
        - The current example only creates one subfolder for each folder
           $ mkdir -p thesis/chapter_1/section_1/subsection_1
        - Show the audience how to create multiple sub-folders for each folder using the bracket operator e.g. 
          $ mkdir -p TensorFlow/{scripts/preprocessing,workspace/training_demo/{annotations,exported-models,images/{test,train},models,pre-trained-models}}
    
    b.	The Tree command is quoted in the advanced Shell lesson (as supplementary content), but it would be useful to teach it here as it very neatly prints out the directory and can be a very useful aid for Shell users. The only problem I see is that it might not be part of the standard a Linux installation and will, therefore, need to be installed by the novice level learners; which brings me to my next point i.e. installation commands

2. ***Installing programs:*** Researchers/Shell-users frequently might need to install new programs and, therefore, it would be useful to demonstrate how to ***install programs using Shell***
    - Some useful programs that can be installed are Tar, Git, Tree as they might not be available with standard installation
    - Teach them how to install Tree using yum or apt-get

**Comment by gdevenyi** [comment]
We would welcome a PR with the proposed changes to discuss. THanks.

**Comment by gcapes** [comment]
Thanks for the issue. 

My thoughts: these are useful things to know, but beyond a novice lesson.
1a - out of scope for novice lesson.
1b - not a standard command so won't work for all learners
2 - out of scope

You might consider a PR for the shell extras lesson.
