### ISSUE TITLE
2. Navigating Files and Directories: Truncate ls --help output

### ISSUE THREAD

**Issue by piperfw** [swcarpentry/shell-novice#1175]
Is there a good reason for including the full output of `ls --help` in episode 2? 

I see little educational value of this and it makes the page considerably longer (I doubt the expectation is for learners to read the entire output; if they wanted to it would be better for them to run the command in their own shell where it can be combined with grep, less etc.).

I propose including the first few lines and then ellipses `⋮` or `...`

**Comment by gdevenyi** [comment]
We would welcome a PR proposing a fix for this,

**Comment by gcapes** [comment]
Resolved in #1178
