### ISSUE TITLE
Broken Link - Navigating Files and Directories Lesson

### ISSUE THREAD

**Issue by LizKinney** [swcarpentry/shell-novice#1180]
The current link to exploring other directories is broken.

http://swcarpentry.github.io/shell-novice/02-filedir/exploring-other-directories - 404 File not found.  

I cannot find the actual link that is to be included in this hyperlink.

**Comment by gcapes** [comment]
The link should be http://swcarpentry.github.io/shell-novice/02-filedir/#exploring-other-directories
Navigating Files and Directories – The Unix Shell<http://swcarpentry.github.io/shell-novice/02-filedir/#exploring-other-directories>
Clearing your terminal. If your screen gets too cluttered, you can clear your terminal using the clear command. You can still access previous commands using ↑ and ↓ to move line-by-line, or by scrolling in your terminal.. Here, we can see that our home directory contains only sub-directories.Any names in your output that don’t have a classification symbol, are plain old files.
swcarpentry.github.io


Thanks
Gerard
--
Gerard Capes
Research Applications, IT Services, University Of Manchester
________________________________

**Comment by gdevenyi** [comment]
Thanks for the report, fixed at #1181
