### ISSUE TITLE
a basic command file will be useful - Instructor checkout

### ISSUE THREAD

**Issue by tvsingh** [swcarpentry/shell-novice#1182]
---
After going through the shell-novice material, I found that a new user might try to edit an executable or some other types of file. They should be warned against doing this. Another example is 'cat' command. If a user mistakenly use can on an executable, the machine characters can cause the terminal to hang or other abnormal behavior. 
In my opinion, at least the command 'file' should be introduced to check the file type before handling the target files.
 

---

**Comment by gcapes** [comment]
Thanks for the issue. I think `file` is beyond the scope of this novice lesson.
