### ISSUE TITLE
Ep03: ls output incorrect

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#1187]
Another recent change that hasn't been checked thoroughly:

The `mkdir -p` example creates a load of subdirectories in the 'thesis' directory. This output isn't shown later on in the notes when listing the contents of the `thesis` directory. The notes show we just have `draft.txt`. This error propagates through to the 'Moving files and directories' section.

It's hardly the end of the world to have these extra subdirectories there, but the notes no longer match the output you get from running the commands, and they probably mainly serve to confuse the picture. Extraneous load and all that.

**Comment by gremau** [comment]
I think this is a issue that needs to be fixed also, but I'm not sure pull request #1195 resolves the issue because it conflicts with an exercise later in the episode (see my comments there).
