### ISSUE TITLE
Instructors: Use Software Carpentry Shell Split Window

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/shell-novice#1198]
Hi everyone

I have just successfully passed my instructor demo lesson. As part of that I used the [Software Carpentry Shell Split Window](https://github.com/rgaiacs/swc-shell-split-window). This splits a bash terminal into an upper and a lower half, with a thick horizontal ine between the two. As you type commands in the lower half, the command history appears in the upper half. 

My assessing trainer suggested I note about it here, as it is a really useful tool for teaching the Shell lesson.

One point: on my MacBook Pro I had a job getting it to work at first, as my default shell was `zsh`, and I had to get it to change to the version of `bash` installed by homebrew. I also had an issue with the fact that I had put a comment in between two lines of the same command in the shell script, and the script didn't like it.

i.e. do this:

```
 command \
    argument \
    `# comment` \
    other_argument \
    `# other comment`
```

but not this:

```
 command \
    argument \
    # comment \
    other_argument \
    # other comment
```

That is, any comments you put in the middle of a multi-line shell script command should have a backtick at the start and finish of the line (the backtick is the syntax for command substitution - kudos to @giordano  for telling me this!)

**Comment by dpshelio** [comment]
Thanks @mattgillucl.

This is already mentioned in the instructor notes: https://github.com/swcarpentry/shell-novice/blob/d785bec9f931c09f6976998502315242df31aa38/_extras/guide.md#teaching-notes (brought by #204). 
It certainly can be shown more clearly, maybe with a screenshot, or a clearer explanation so instructors understand what it's about. Maybe a link to the [original thread](https://carpentries.topicbox.com/groups/discuss/T303a2de7cd637c55-Ma1c9f406c60a774715eb468b/discuss-splitting-screen-for-teaching-the-unix-shell) may be also helpful for future references.

The comment about zsh/bash and comments could be submitted to the [`swc-shell-split-window` repository](https://github.com/rgaiacs/swc-shell-split-window).

**Comment by mattgillucl** [comment]
Thanks @dpshelio . Sorry, I wasn't aware of that.

I have added the relevant part to [the existing issue ](https://github.com/rgaiacs/swc-shell-split-window/issues/2)on the `swc-shell-split-window` repository.

This issue can therefore be closed.
