### ISSUE TITLE
add another solution to exercise 

### ISSUE THREAD

**Issue by rksin8** [swcarpentry/shell-novice#1202]
Exercise [Tracking a Species ](http://swcarpentry.github.io/shell-novice/07-find/index.html) can have two solutions:

`grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt`    (Given)

`grep -w $1 -r $2 | cut -d , -f 1,3  | cut -d : -f 2 > $1.txt`

As this is a rearranging commands exercise, a user may come with either of the solutions. It will be good if we could either add both the solutions or mention in the text that there could be more than one possible solution.

**Comment by gcapes** [comment]
Looks good. PR welcome!
