### ISSUE TITLE
Replace 'interation' with 'iteration'

### ISSUE THREAD

**Issue by marianarius** [swcarpentry/shell-novice#1213]
Typo on:
https://swcarpentry.github.io/shell-novice/05-loop/index.html

Suggested replacement of 'interation' with 'iteration'

**Comment by marianarius** [comment]
> Typo on:
> https://swcarpentry.github.io/shell-novice/05-loop/index.html
> 
> Suggested replacement of 'interation' with 'iteration'

NOTE:
The typo is located within the 'Solution' of 'Saving to a File in a Loop - Part One'. The typo will NOT appear with a Ctrl + F search, one must first open the solution box to see the typo.

**Comment by gdevenyi** [comment]
Thanks for the suggestion, a very good eye catching those, my brain auto-completes the proper word.

We would welcome a simple PR to fix these :)
