### ISSUE TITLE
Episode 5 Loops: incomplete output

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/shell-novice#1214]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. 
---

The attached feedback is in refence to the lesson 06 on Loops - The Unix Shell
[Carpentry Shell-Novice lesson 06 correction.pdf](https://github.com/swcarpentry/shell-novice/files/6779196/Carpentry.Shell-Novice.lesson.06.correction.pdf)

**Comment by gcapes** [comment]
I think adding an elipsis would do the job here to indicate the output is incomplete.
