### ISSUE TITLE
Lesson Contribution - Pipes and Filters

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/shell-novice#1215]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community.

---

I would like to make two suggestions to "The Unix Shell" lesson as part of my checkout procedure. I chose "The Unix Shell" lesson for my live demo and whilst preparing for the demo I came across two instances that could be improved for the learner's clarity.

> I highly recommend changing the name of one of the animals.txt files with very similar content, located in:
> /Desktop/shell-lesson-data/data/animals.txt
> /Desktop/shell-lesson-data/data/animal-counts/animals.txt
> 
> Changing the name of /Desktop/shell-lesson-data/data/animal-counts/animals.txt to animal_counts.txt will allow the learner to clearly differentiate between the two files and directories, while they are still becoming familiar with navigating through the shell.

> Under the "Finding Things" lesson there is a section called "Tracking a Species" which utilizes the cut command and the file /Desktop/shell-lesson-data/data/animal-counts/animals.txt.
> The command solution to this task is written as follows:
>
grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt
Unfortunately, it looks like a typo has been published in this command where a double space is present between the 3 and the >. Even though the double space does not cause an error, it is not consistent with what was taught in "Pipes and Filters" and could be confusing for learners. Being consistent as possible in intorductory lessons is important for learning and retaining information. I would suggest changing this to a single space for clarity and consistency for learners.

**Comment by gcapes** [comment]
The first should be fixed soon in #1233.
