### ISSUE TITLE
Instructor Note (Pre-Workshop)

### ISSUE THREAD

**Issue by hallettc** [swcarpentry/shell-novice#1216]
Thanks to my practice teaching group for inspiring this suggestion! 

Add the following suggestion for instructors: It is highly recommended that you have an account set up on your computer just for teaching the workshops, which you keep up-to-date with only the necessary programs for the workshop. This ensures that you receive fewer notifications, are working on the same versions of software as your students, and that any aliases/alterations that you may have made to your command line/computer for work/education/life purposes do not impact your instruction. Good luck!

**Comment by gdevenyi** [comment]
An interesting suggestion! We would welcome a PR adding this to the instructor notes to refine the wording.

**Comment by gcapes** [comment]
While this is good advice, I'm not sure the shell lesson is necessarily the right place for it. It seems like general advice which would apply to any lesson, and so fit better in the instructor training lesson - see live coaching section here:
https://carpentries.github.io/instructor-training/14-live/index.html

**Comment by gdevenyi** [comment]
Great point @gcapes this definitely applies more generally!

**Comment by gcapes** [comment]
I don't have the permissions to move this issue but perhaps you could submit this issue there instead?

https://github.com/carpentries/instructor-training/issues

Thanks
