### ISSUE TITLE
Improve site navigation

### ISSUE THREAD

**Issue by ocefpaf** [swcarpentry/shell-novice#122]
It would be nice to have `next`, `previous`, and `home` links at every page to improve the navigation.

**Comment by r-gaia-cs** [comment]
@ocefpaf Thanks for the suggestion. This is a long time request that we have, see https://github.com/swcarpentry/bc/issues/835 and https://github.com/swcarpentry/lesson-template/pull/38.

The big challenge to implement this is that we are using Make and is hard to get the `next` and `previous` file. We will only do that after 5.3.

Are you OK in close this?

**Comment by ocefpaf** [comment]
Sure just mark it as duplicate.  (I am just reviewing the lesson as part of our last assignment.)
