### ISSUE TITLE
Changing word haikus to haiku in Episode 7: Finding Things

### ISSUE THREAD

**Issue by lsimpsonlibrary** [swcarpentry/shell-novice#1227]
For the lesson[ Unix Shell](http://swcarpentry.github.io/shell-novice/), [Episode 7: Finding Things](http://swcarpentry.github.io/shell-novice/07-find/index.html):

The [plural of haiku](https://www.merriam-webster.com/dictionary/haiku) is the same as the singular (haiku). 
Request to correct the word **haikus** to **haiku** on the following lines in this lesson:

*    30:we will use a file that contains three **haikus** taken from a
*    58:> We haven't linked to the original **haikus** because they don't appear to be on *Salon*'s site any longer.

Thanks for the work you do! 
Lance Simpson, [lsimpson@ua.edu](mailto:lsimpson@ua.edu)

**Comment by deppen8** [comment]
Thanks for raising this @lsimpsonlibrary. I submitted #1231 to fix this. This issue should close when that gets merged.
