### ISSUE TITLE
Consider changing /users to /home

### ISSUE THREAD

**Issue by ocefpaf** [swcarpentry/shell-novice#124]
Users using modern Linux distributions in their laptops while following the lesson will recognize `/home` immediately, while `/users`  might bring some confusing.

**Comment by r-gaia-cs** [comment]
We use `/Users` because is what Mac OS X uses. I already complains once about this but leave that way.

**Comment by ocefpaf** [comment]
Ah makes sense... or not :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
@r-gaia-cs 
BTW: here http://swcarpentry.github.io/shell-novice/02-create.html  (in Another Useful Abbreviation) the lesson uses `/home` instead of `/users`.  Maybe that is on purpose to show the two different standards?  Although, I would vote to keep the lesson consistent.

**Comment by gvwilson** [comment]
+1 to consistency; +1 to showing the Mac usage (since we have more Mac 
users in workshops than Linux users); +1 to a small callout box 
explaining what the path is likely to look like on Linux, and on Windows.

**Comment by ChristinaLK** [comment]
addressed in PRs
