### ISSUE TITLE
Ep 05: Write a loop from scratch

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#1244]
Following on from #1155, I think there would be a lot of value to an exercise where learners must write a loop from scratch.

**Comment by eroesch** [comment]
I agree. Having taught this lesson a few times, novices tend to not understand the value of loops in context until they realise that it is something they can use themselves, with something else than files.
I am thus proposing: https://github.com/swcarpentry/shell-novice/pull/1273

**Comment by bkmgit** [comment]
https://github.com/swcarpentry/shell-novice/pull/1273 was merged, so closing.
