### ISSUE TITLE
Episode 3 - file created in exercise not referenced after

### ISSUE THREAD

**Issue by deppen8** [swcarpentry/shell-novice#1252]
In episode 3, the lesson reads

> The first argument tells `mv` what we're 'moving',
> while the second is where it's to go.
> In this case,
> we're moving `thesis/draft.txt` to `thesis/quotes.txt`,
> which has the same effect as renaming the file.
> Sure enough,
> `ls` shows us that `thesis` now contains one file called `quotes.txt`:
> 
> ~~~
> $ ls thesis
> ~~~
> {: .language-bash}
> 
> ~~~
> quotes.txt
> ~~~
> {: .output}

However, if the instructor/learner did the "Creating Files a Different Way" exercise above this, they will also have a file called `my_file.txt` in this directory. I propose the following change:

> `ls` shows us that `thesis` now contains one file called `quotes.txt` (or two files if you created `my_file.txt` in the exercise above:

Later, the lesson says:

> The effect is to move the file from the directory it was in to the current working directory.
> `ls` now shows us that `thesis` is empty:
> ~~~
> $ ls thesis
> ~~~
> {: .language-bash}
> ~~~
> $
> ~~~
> {: .output}

I propose:

> The effect is to move the file from the directory it was in to the current working directory.
> `ls` now shows us that `thesis` is empty (or containing a single file, `my_file.txt`):
> ~~~
> $ ls thesis
> ~~~
> {: .language-bash}
> ~~~
> $
> ~~~
> {: .output}

**Comment by gcapes** [comment]
Thanks for raising this. I think that the lesson's output should match what might be there, but the proposal feels clunky like the various OS-dependent caveats we have/had(?) throughout the material. My preference would be to edit the exercise which creates this file to create it elsewhere.
