### ISSUE TITLE
Ep03 - Add some information on -f option of rm command

### ISSUE THREAD

**Issue by Fredrick-Kakembo** [swcarpentry/shell-novice#1260]
Great content you have explaining the rm command for deleting files and as well as including -r for directories. However sometimes some content may fail to be deleted with the regular `rm -r`  options say redundant compilation files that may give a permission denied error. In such case adding the the `-f` will solve the problem in every scenario.

However, it should be used with caution, as it can also delete system files if one is not careful.

**Comment by deppen8** [comment]
Thanks for your suggestion @Fredrick-Kakembo. Personally, `rm -rf` is one of those snippets that I have committed to muscle memory.

In the lesson, however, I think it is best to leave the "guardrails" in place. At the stage where most of the learners are, it can be a good thing to see error messages.
