### ISSUE TITLE
Demonstration of R or Python loop

### ISSUE THREAD

**Issue by lincoln-harris** [swcarpentry/shell-novice#1268]
In the [Loops](https://swcarpentry.github.io/shell-novice/05-loop/index.html) section of the Unix Shell lesson, for loops are developed explicitly in bash. Bash is an intuitive and generally useful language for beginner programs, however, in practice I think it's safe to assume that learners are far more likely to use R or python. I suggest adding a word or two at the end of this section along the lines of "Hey you can also write loops in R or Python! The language and syntax are different but the core idea is the same." 

To better demonstrate this point, we could also provide a basic example of a for loop in R or Python. But its also worth pointing out that for loops in R are almost never the most efficient solution...perhaps its best to stick with Python, then.

**Comment by gdevenyi** [comment]
Hi @lincoln-harris this lesson is specifically for teaching shell/bash, and not a general introduction to programming, or R/python. In addition, these lessons are actually aimed at people who might have almost no programming experience, so providing a reference to another language won't help them. 

For those who are familiar, they are likely to be able to recognize the similarities themselves, while for those who don't know, its noise in the lesson. As such, I don't think this is an appropriate addition for the lesson.

Thanks for the suggestion!
