### ISSUE TITLE
Question regarding the us of 3 minus sign in the text

### ISSUE THREAD

**Issue by ocefpaf** [swcarpentry/shell-novice#127]
There are some `---` used in the text at some places and, I believe, that should represent a &mdash;.  Is that correct?  If so, should we use some "Markdown flavor/plugin" to take care of that?  Or should we fix it using the HTML syntax (`&mdash;`)?

**Comment by r-gaia-cs** [comment]
> There are some `---` used in the text at some places and, I believe, that should represent a —. Is that correct?

Yes. This is the behavior of `kramdown` that we previously use

~~~
$ kramdown <<EOF
foo --- bar
EOF
<p>foo — bar</p>
~~~

> If so, should we use some "Markdown flavor/plugin" to take care of that?

We just need to enable it on Pandoc:

~~~
$ pandoc <<EOF
foo --- bar
EOF
<p>foo --- bar</p>
$ pandoc -S <<EOF
foo --- bar
EOF
<p>foo — bar</p>
$ pandoc -S --ascii <<EOF
foo --- bar
EOF
<p>foo &#8212; bar</p>
~~~

> Or should we fix it using the HTML syntax (&mdash;)?

I just enable it on the template, check https://github.com/swcarpentry/lesson-template/commit/3ae50df511b43693748c68a927bfdd96b61b6bcb.

**Comment by ocefpaf** [comment]
Now the question is:  How to keep the lessons in sync with the template?

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 12:03:36PM -0700, Filipe wrote:
> Now the question is:  How to keep the lessons in sync with the template?

Either the lesson maintainers can pull, or @gvwilson can push.  See
discussion in #92.

**Comment by r-gaia-cs** [comment]
> Now the question is: How to keep the lessons in sync with the template?

We don't plan to change the template very often.
Last weekend a send a few pull requests just change minor things.
After some pull request be merged we notify lessons maintainers to update the files from the template.

**Comment by ChristinaLK** [comment]
We'll plan to update before the next html generation.
