### ISSUE TITLE
Add shortcuts for RStudio to "all" Intro to R epsiodes/lessons

### ISSUE THREAD

**Issue by laureltree** [swcarpentry/shell-novice#1271]
Kia ora,

I noticed that some of the "Intro to R" sessions provide (some) of the **shortcuts** that make working in RStudio so much faster, but not _all_ of them do this.

____

Mentions some shortcuts:

E.g. in https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html it says:

_In RStudio, typing Alt + - (push Alt at the same time as the - key) will write <- in a single keystroke in a PC, while typing Option + - (push Option at the same time as the - key) does the same in a Mac._

**I suggest to add at least the "save script" (Ctrl + S) and "run code" shortcut (Ctrl + Enter).**

___

Mentions no shortcuts:

E.g. other lessons such as http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html:

_Here, no shortcuts are mentioned at all._

____

**I have been asked for shortcuts in my R workshops regularly and repeatedly, so I believe adding these (maybe even as a noticeable box) to the beginning of each "Intro to R"-related episode would be useful.**

What do others think?

Thanks, 
laureltree

**Comment by gcapes** [comment]
Hi @laureltree 

This is the UNIX shell repo. I think your issue would be better placed in one of these repos:

https://github.com/swcarpentry/r-novice-inflammation
https://github.com/swcarpentry/r-novice-gapminder

Thanks

**Comment by laureltree** [comment]
Good point, thank you!
