### ISSUE TITLE
'ls' vs 'ls -F'

### ISSUE THREAD

**Issue by sbplaisier** [swcarpentry/shell-novice#1282]
In the Navigating episodes, you ask the students to use 'ls -F'.  If you are using a Linux environment, there is no difference when you use the -F option.  The default environment uses different colors and symbols to note what is a file vs a directory. It might be good to add a note to the instructors that you can test this and leave out the '-F' if it makes sense to in the environment they are going to do the demo in.  One less thing to explain.

**Comment by gcapes** [comment]
I would encourage this discussion as part of a broader issue #798.
