### ISSUE TITLE
Alternatives to Setup: Accessing a cluster

### ISSUE THREAD

**Issue by sbplaisier** [swcarpentry/shell-novice#1283]
In the website for this lesson, Setup section (https://swcarpentry.github.io/shell-novice/setup.html), I think it would be helpful to add a section on connection to a cluster using ssh.  In the university I am part of, students will generally be asked to learn Unix in order to use the biocomputing cluster. In this case you will need to do the following instead of downloading an emulator inside your Windows or Mac environement:
1) download an SSH terminal program such as Putty or use a web-accessible portal if there is one set up for that server
2) set up an account on the server you would like to use
3) use the ssh command to log in to that server: ssh server.domain.edu -l username

I plan to teach using a web-accessible portal set up at my university so no one needs to download anything and we all have the same thing to work on.

**Comment by gcapes** [comment]
Thanks for your issue.

Connecting to a cluster is however beyond the scope of this novice tutorial. A workshop could certainly be run that way, but specific setup instructions should be sent for individual workshops run remotely.

There is a [section on ssh](https://carpentries-incubator.github.io/shell-extras/02-ssh/index.html) in the shell-extras lesson.
