### ISSUE TITLE
Adding the use of "#!/bin/bash" on the scripting lesson

### ISSUE THREAD

**Issue by hekima31** [swcarpentry/shell-novice#1288]
With the episode on scripting - https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/06-script.md - I thought it would be useful to add some explanation on the use of #!/bin/bash as it is very common on almost all bash scripts I come across. Thought this is a fundamental concept that could be included.

**Comment by gcapes** [comment]
Hi, Thanks for the contribution!

We have [discussed this previously](https://github.com/swcarpentry/shell-novice/pull/1127) and decided it brings too many extra concepts with it to be worth implementing. Striking the right balance is often difficult but I think this is out of scope for a novice lesson.
