### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by sri29** [swcarpentry/shell-novice#1290]
<How to check disk space>
< We often would like to see how much disk space left while running the unix shell and I think it is very useful to know the commands that are used to check the disk space on the system. For example **df** to check how much space left on disk and **du** for howmuch space already taken>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by deppen8** [comment]
Thanks for the suggestion. While this might be useful to some learners, we have a high threshold for adding totally new content to the lesson. In this case, I don't think it is broadly applicable enough to reach that threshold.

Closing this issue for now but always happy to have further discussion.
