### ISSUE TITLE
A small change in the episode "Finding Things"

### ISSUE THREAD

**Issue by jsarmagmu** [swcarpentry/shell-novice#1294]
This correction is for the content in Episode 07 - https://swcarpentry.github.io/shell-novice/07-find/index.html

In the  "Matching and Subtracting" section, the following command:
  `grep -v "unicorn" $(find creatures -name "*.dat"))`
produces an error:
   `-bash: syntax error near unexpected token `)'`

As a lesson contribution for instructor training, I would like to edit it to remove the extra ')' so the answer provided in the Solution area will match the expected output.

</details>

**Comment by deppen8** [comment]
@jsarmagmu, would you like to submit a fix for this?

**Comment by Trombach** [comment]
Hi @deppen8 

I have created a PR to fix this and linked it to this issue.
