### ISSUE TITLE
Ep_3 Possible wrong solution at the More on Wildcards

### ISSUE THREAD

**Issue by ghostenel** [swcarpentry/shell-novice#1304]
I'm a new learner but I believe I spotted a small mistake in the solution section at More on Wildcards in the lesson [Working With Files and Directories](https://swcarpentry.github.io/shell-novice/03-create/index.html).

The last line of the solution states `$ cp *-23-dataset* send_to_bob/all_datasets_created_on_a_23rd/`.
However this would not copy the `$ 2015-11-23-calibration.txt` mentioned in the question. I'm a new student so I could be incorrect, but I believe the last line in the solution should be `$ cp *-23-* send_to_bob/all_datasets_created_on_a_23rd/`.

Thank you for your time.

**Comment by gcapes** [comment]
Hi @ghostenel and thanks for your question.

The task in the exercise is to copy the datasets created on a 23rd. So the suggested solution avoids copying any calibration data created on a 23rd, and only copies the datasets. Does that make sense?
