### ISSUE TITLE
About ls output

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/shell-novice#131]
`ls` output is "different" depending of the size of the terminal. E.g. for a large terminal I get

~~~
$ ls
1.txt  2.txt  3.txt  4.txt  5.txt  6.txt  7.txt  8.txt  9.txt
~~~

but for a small one I get

~~~
$ ls
1.txt  3.txt  5.txt  7.txt  9.txt
2.txt  4.txt  6.txt  8.txt
~~~

Can we always display the output of `ls` as if we are using `-1`?

~~~
$ ls -1
1.txt
2.txt
3.txt
4.txt
5.txt
6.txt
7.txt
8.txt
9.txt
~~~

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 07:47:36PM -0700, Raniere Silva wrote:
> Can we always display the output of `ls` as if we are using `-1`?

Ugh, that takes up so much space :p.  Does it really matter how many
columns ‘ls’ uses?  Have learners been confused by this in the past?

**Comment by ChristinaLK** [comment]
I'm with @wking , I don't think this is critical and I'd like to think it's not a place where learners stumble.
