### ISSUE TITLE
Getting help: is additional guidance for Linux users necessary

### ISSUE THREAD

**Issue by Elisa-on-GitHub** [swcarpentry/shell-novice#1315]
The [Getting help section](https://swcarpentry.github.io/shell-novice/02-filedir/index.html#getting-help) in Episode 2 only specifies how to get help for Mac and Windows users. Does this need additional guidance for Linux users - i.e. what command they should use?
This question was sparked when I submitted issue #1314

**Comment by gcapes** [comment]
Both man and help should be available in Bash on Linux. I'm not sure whether a short note to this effect would be appropriate to make this explicit, or whether this is a 'red sticky note' question i.e. for the instructor.

**Comment by gcapes** [comment]
Ok let's flip the explanation. I'll submit a PR.

**Comment by Elisa-on-GitHub** [comment]
Thank you so much for following up!

**Comment by gcapes** [comment]
No worries - thanks for the issue!
