### ISSUE TITLE
Lesson Contribution: integrate Unix shell with R

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/shell-novice#1327]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

My suggestion is to incorporate the information in the lesson that we can integrate Unix shell with R. For example; we can use R software on the terminal (Unix environment) by using R scripts as we do in a separate R studio. And if we again want to switch to a Unix shell environment then we will simply write EXIT in the terminal and we will again come to the Unix environment.

**Comment by bkmgit** [comment]
This is out of scope for this lesson.  For those teaching Unix Shell and R together, a comment is helpful and instructors can adapt the material accordingly.
