### ISSUE TITLE
Consider adding an `-exec` with find

### ISSUE THREAD

**Issue by mahdi-b** [swcarpentry/shell-novice#133]
Consider given an example of how to use `-exec` in conjunction with `find`. Currently, it is suggested to use command expansion -- $() --  to run a command on a file. As suggested by by @wking  in https://github.com/swcarpentry/shell-novice/pull/132, it is simpler and much more idiomatic, to use  -exec. 
Ex.

```$ find .. -name '*.pdb' -exec grep FE {} \+```

rather than

```$ grep FE $(find .. -name '*.pdb') ```

**Comment by wking** [comment]
On Mon, Apr 27, 2015 at 07:31:22PM -0700, bingo11 wrote:
> Consider given an example of how to use `-exec` in conjunction with
> `find`. Currently, it is suggested to use command expansion -- $()
> -- to run a command on a file. As suggested by by @wking in
> https://github.com/swcarpentry/shell-novice/pull/132, it is simpler
> and much more idiomatic, to use -exec.

While I think this is all true, my preferred solution (mentioned in
#132) is to *drop* the ‘grep FE $(find …)’ call.  Folks already have
enough on their plate without learning more of find's pre-getopt-long
syntax ;).

**Comment by gvwilson** [comment]
I'm -1 to `-exec` in our basic lessons (but +1 in the shell-extras): the 
`{} ;` syntax is nasty.

**Comment by gdevenyi** [comment]
I'm with @gvwilson this should either go in shell-intermediate or shell-extras, it's well outside the scope of novice material.
