### ISSUE TITLE
Proposed brief introduction of sed and awk - Instructor training checkout contribution

### ISSUE THREAD

**Issue by Jeff-Intersect** [swcarpentry/shell-novice#1333]
While **grep** was introduced in the "[Finding Things](https://swcarpentry.github.io/shell-novice/07-find/index.html)" section, I think it is better to briefly mention **sed** and **awk**. I noticed that awk has already been added to the [Extra Unix Shell Material](https://carpentries-incubator.github.io/shell-extras/). Probably sed can be **added** as well.

**Comment by bkmgit** [comment]
Thanks for the suggestion.  The lesson is quite long, so clarifications are more useful than extensions.  Perhaps sed can be mentioned briefly with motivation and suggesting using the manual pages.  There are several tutorials available online for self study, not sure worth creating another tutorial is of great benefit.  A pull request mentioning sed would be helpful if you want to make one.

**Comment by Jeff-Intersect** [comment]
Thanks @bkmgit for the clarification. I agree as I have the same feeling that this is a long lesson.

**Comment by Jeff-Intersect** [comment]
All resolved now. Thanks @bkmgit
