### ISSUE TITLE
Letter casing issue in lesson 02

### ISSUE THREAD

**Issue by nigeldgreen** [swcarpentry/shell-novice#1334]
Hi,

In lesson 02 (https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/02-filedir.md) there is an instruction near the end that will cause issues in different shells:

"If Nelle adds G and presses Tab again, the shell will append 'goo' since all files that start with 'g' share the first three characters 'goo'."

As the shell in use is bash this will not work as it won't complete 'goo' from a capital 'G'. This may be OS-dependent, but bash on Ubuntu will not complete the filename here.

I'd suggest changing this to a lower case 'g' as this will work on all unix-like OSes, and maybe adding a hint box to mention case sensitivity (you can add `bind -s 'set completion-ignore-case on'` to .bashrc to get it, for instance).

Nigel Green
nigel.green@manchester.ac.uk

**Comment by gcapes** [comment]
Thanks for the issue. However, if you press the "G" key on a keyboard, you get a lower case G, (g). If you press "shift" + "G" you get a capital G.

Perhaps the wording could be made extra clear by changing to 
> If Nelle then presses `G` then presses `Tab` again ....

**Comment by deppen8** [comment]
There is also a Carpentries style guide that has some guidance on key presses: https://carpentries.github.io/lesson-example/06-style-guide/index.html

**Comment by mehrdadbn9** [comment]
hi
i think it's ok but if need any changes i would like  to do it.
@gcapes  should i do what you've said? if so, please assign me
thanks

**Comment by gcapes** [comment]
Thanks for volunteering! @mehrdadbn9
