### ISSUE TITLE
phrasing on grep -w command

### ISSUE THREAD

**Issue by driftsignal** [swcarpentry/shell-novice#1357]
in the [finding] things lesson.

current sentence:

To restrict matches to lines containing the word ‘The’ on its own, we can give grep **with** the -w option.

the __with__ seems unnecessary

perhaps change to:

To restrict matches to lines containing the word ‘The’ on its own, we can give grep the -w option.

[finding]:https://swcarpentry.github.io/shell-novice/07-find/index.html

**Comment by mehrdadbn9** [comment]
Hi 
is it possible to make this changes? 
would you please assign it to me?
after fork and making changes can PR it or  not?
