### ISSUE TITLE
Ep03: fill in the blanks answers color inconsistency

### ISSUE THREAD

**Issue by cedorikku** [swcarpentry/shell-novice#1370]
Hello, 

Just noticed a slight color inconsistency on two lines of the solution of this exercise section [Using wildcards for accessing multiple files at once - More on Wildcards](https://swcarpentry.github.io/shell-novice/03-create/index.html#more-on-wildcards)

On the solution part, specifically these bash lines:
```bash
$ cp *calibration.txt backup/calibration
$ cp 2015-11-* send_to_bob/all_november_files/
```

only their `*` is colored/ highlighted while `.txt` or  `11` aren't, even if it's part of what I think is an answer to the _fill-in-the-blank_ problem. I guess what I'm trying to suggest, for consistency's sake, is to change the colors of these two to match the blanks of the problem?

**Comment by gcapes** [comment]
This is probably one for the [styles](https://github.com/carpentries/styles) repo(?), but given the upcoming move to the workbench format, it might not get fixed for the current style.

**Comment by tobyhodges** [comment]
Indeed, this looks like the Markdown parser getting confused by the combination of underscores and asterisks in the exercise code blocks. As @gcapes suggested, that makes it a templating issue for _styles_. 

However, [the Workbench version of the lesson does not have the same issue](https://fishtree-attempt.github.io/shell-novice/03-create#challenge8), so I believe you can safely close this on the grounds that the problem should disappear after the new infrastructure is rolled out at the start of May.

**Comment by gcapes** [comment]
Great, thanks Toby!
