### ISSUE TITLE
Wonky formatting for a challenge item

### ISSUE THREAD

**Issue by chungkky** [swcarpentry/shell-novice#138]
Re. page on Finding Things file <06-finding.md>, lines 457-471, The formatting of the section on "Matching ose.dat but not temp" is out of wack with the other challenges (the titles is too large, it is not in a box with a pencil icon like other challenge, etc.) Looks like the code has been interpreted as "block indent" and "heading font size" rather than "challenge." I looked at the Markdown file and can't find where the error is but the resulting HTML page is definitely wrong. Can anyone tell me where the problem is in the code?
![formatting-error-06-find](https://cloud.githubusercontent.com/assets/7913902/7467552/f53ef1ce-f2c8-11e4-9d93-5dc5cc00d066.jpeg)

**Comment by gvwilson** [comment]
The problem is the use of back quotes for code formatting in the level-2 header of the challenge: if `ose.dat` and `temp` are in plain font (no backquotes), the formatting is correct.  Is this a bug in Pandoc?

**Comment by r-gaia-cs** [comment]
> I looked at the Markdown file and can't find where the error is but the resulting HTML page is definitely wrong. Can anyone tell me where the problem is in the code?

~~~
$ pandoc <<EOF
# \`foo\` {.bar}
EOF
<h1 id="foo"><code class="bar">foo</code></h1>
$ pandoc <<EOF
# \`foo\` {}{.bar}
EOF
<h1 id="foo" class="bar"><code>foo</code></h1>
~~~

>  Is this a bug in Pandoc?

Nope. This is intended. See my example above. I couldn't find the issue at https://github.com/jgm/pandoc/ that cover this.

I already send a pull request to fix this: https://github.com/swcarpentry/shell-novice/pull/142.
