### ISSUE TITLE
Some issues with the shell-novice lesson

### ISSUE THREAD

**Issue by jevbelikov** [swcarpentry/shell-novice#140]
I had a look at the lesson and found a few things I need to clarify before I can submit a pull request correcting them.  I have decided not to create an issue for each as some are fairly minor issues
(numbers are point numbers, not lesson sections).

1. In the introduction it could be mentioned that automation using scripts also makes research more *reproducible* (or at least the analysis).

2. The actual commands like cd or ls could be mentioned in the learning outcomes.

3. In the 'Files and Directories' section: 
    * 'read-run-print cycle' is used but in the Intro REPL is used (switch to REPL for consistency?)
    * When talking about home directory: could mention *~* and *cd* (w/o argument) here instead of later in 'Creating Things'
    * *pwd* is cryptic but can be remembered as 'print working directory' -- so I suggest cutting the lengthy discussion (alternatively we could introduce *alias* command e.g. *$ alias whereami=pwd*);
    * there is a mismatch in Figures and text (*/users* vs  */Users*), which misleadingly suggests that bash is case insensitive
    * arguments vs parameters: why use inconsistently and not define them and stick to definitions?

4. 'Creating Things':
    * could emphasise more that *mv* overwrites an existing file if second argument is the same as the name of another exiting file (potential for mistake and loss of a file)
    * perhaps the title should be more general as this part covers deleting and copying/moving too
    * discussion of '~' (home directory) could be moved to 'Files and Directories'

5. 'Pipes and Filters': 
    * > (redirection) overwrites existing files without a warning
    * Figure has no part for *'wc -l *pdb | sort -n'* (slight mismatch to text)
    
6. 'Loops': could mention automation of repetitive tasks as motivation and add a sentence explaining semicolon as separator (useful in one-liner scripts)

7. 'Finding Things' could be introduced before sections 4 (Loops) and 5 (Scripts) as they fit well with 3 (pipes and filters; as an example). What is the rationale for putting it at the end? (I mentioned unspecific link in another issue).

8. Would any of the sections benefit from additional MCQs?

**Comment by r-gaia-cs** [comment]
Please considere +1 when there is no comment.

> 1. In the introduction it could be mentioned that automation using scripts also makes research more *reproducible* (or at least the analysis).
>
> 2. The actual commands like cd or ls could be mentioned in the learning outcomes.
>
> 3. In the 'Files and Directories' section: 
>     * 'read-run-print cycle' is used but in the Intro REPL is used (switch to REPL for consistency?)
>     * When talking about home directory: could mention *~* and *cd* (w/o argument) here instead of later in 'Creating Things'
>     * *pwd* is cryptic but can be remembered as 'print working directory' -- so I suggest cutting the lengthy discussion (alternatively we could introduce *alias* command e.g. *$ alias whereami=pwd*);

As fas as I remember we agreed that `alias` will be cover only in intermediate lesson.
Novice users can use scripts as `alias`.

>     * there is a mismatch in Figures and text (*/users* vs  */Users*), which misleadingly suggests that bash is case insensitive
>     * arguments vs parameters: why use inconsistently and not define them and stick to definitions?

Please check https://github.com/swcarpentry/bc/pull/420 and
https://github.com/swcarpentry/bc/pull/511.

> 4. 'Creating Things':
>     * could emphasise more that *mv* overwrites an existing file if second argument is the same as the name of another exiting file (potential for mistake and loss of a file)
>     * perhaps the title should be more general as this part covers deleting and copying/moving too
>     * discussion of '~' (home directory) could be moved to 'Files and Directories'
> 
> 5. 'Pipes and Filters': 
>     * > (redirection) overwrites existing files without a warning
>     * Figure has no part for *'wc -l *pdb | sort -n'* (slight mismatch to text)
>     
> 6. 'Loops': could mention automation of repetitive tasks as motivation and add a sentence explaining semicolon as separator (useful in one-liner scripts)
> 
> 7. 'Finding Things' could be introduced before sections 4 (Loops) and 5 (Scripts) as they fit well with 3 (pipes and filters; as an example). What is the rationale for putting it at the end? (I mentioned unspecific link in another issue).
> 
> 8. Would any of the sections benefit from additional MCQs?

I suggest that you try to send small pull request since we will merge them faster.

**Comment by ChristinaLK** [comment]
Thanks for the suggestions @jevbelikov!  I agree w/ all of @r-gaia-cs comments, the only thing I'll add is that I prefer to not have the commands in the learning objectives, mostly because it allows them to be broader and more principle/action based ("be able to move/copy files" as opposed to "use `mv` and `cp`")

Would it be okay with you if I made this into a checklist of requested contributions for new contributors?

**Comment by jevbelikov** [comment]
@ChristinaLK, please do turn it into a list of possible contributions. I have addressed the issue with mv and > potentially overwriting existing files without a warning here: https://github.com/swcarpentry/shell-novice/pull/148. We could consider introducing a different callout style for warning/common mistakes (unless it exists already; I was thinking about O'Reilly books and their 'trap' symbol).

**Comment by ChristinaLK** [comment]
created as individual issues.
