### ISSUE TITLE
Glossary "shell" term has a broken anchor link in its text

### ISSUE THREAD

**Issue by vansteph** [swcarpentry/shell-novice#1413]
Hey,

The `shell` term under the "Glossary" section for both the [instructor](https://swcarpentry.github.io/shell-novice/instructor/reference.html#shell) and [learner](https://swcarpentry.github.io/shell-novice/reference.html#shell) Reference page, has a broken anchor link for the "command-line interface" text.

**Comment by bkmgit** [comment]
@vansteph  Fixed. Thanks for reporting this.
