### ISSUE TITLE
A detail in Unix Shell Pipes and Filters Lesson

### ISSUE THREAD

**Issue by trevdoesdev** [swcarpentry/shell-novice#1439]
### How could the content be improved?

In the pipes and filters lesson, I found it very confusing why "uniq" didn't condense the duplicates in a file unless used with "sort".  It would be nice for new learners to add a note like this:

"The uniq command is designed to work with sorted input data by default. It's intended to remove consecutive duplicate lines, meaning that it considers duplicate lines only if they are adjacent to each other in the input. This design is based on the assumption that uniq is often used in conjunction with sort to process data.

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/shell-novice/04-pipefilter.html

**Comment by bkmgit** [comment]
Thanks for raising this issue. Might you be able to make a pull request
to improve the explanation?

**Comment by gcapes** [comment]
I think the `uniq` command is first introduced in the [pipe contruction](https://swcarpentry.github.io/shell-novice/04-pipefilter.html#pipe-construction) exercise like this:
> The uniq command filters out adjacent matching lines in a file.

Perhaps changing 'adjacent' to 'consecutive' would suffice? I'm concerned that the suggestion above adds an unnecessary length of explanation, as well as giving the answer to the exercise (use `sort`). As always, the lesson is rather full of material already and I think we need to keep that in mind.

**Comment by trevdoesdev** [comment]
> Perhaps changing 'adjacent' to 'consecutive' would suffice? I'm concerned that the suggestion above adds an unnecessary length of explanation, as well as giving the answer to the exercise (use `sort`). As always, the lesson is rather full of material already and I think we need to keep that in mind.

My apologies.  I guess that first statement was clear enough, I just missed it on my first read.  I think it would've been more clear if it had appended: 

`uniq` identifies lines as duplicates _only_ if they are next to each other in the file.
