### ISSUE TITLE
04 - Pipes and Filters

### ISSUE THREAD

**Issue by sushma-4** [swcarpentry/shell-novice#1465]
### What is the problem?

Is there a reason why head and tail are shown to be limited to 10 lines in the summary?

- head displays the first 10 lines of its input.
- tail displays the last 10 lines of its input.

### Location of problem (optional)

https://github.com/swcarpentry/shell-novice/edit/main/episodes/04-pipefilter.md

**Comment by bkmgit** [comment]
By default when no arguments specifying the number of lines to show are given, 10 lines are shown.  Most of the examples in that section specify a smaller number of lines than 10.

**Comment by sushma-4** [comment]
Got it, thanks for explaining.

May I suggest to edit it to reflect that -

- head displays the first 10 lines of its input by default
- tail displays the last 10 lines of its input by default

You can go ahead and close the issue.

**Comment by bkmgit** [comment]
@sushma-4  Thanks for your feedback. Please re-open if further changes are needed.
