### ISSUE TITLE
05 - Loops wildcard matching

### ISSUE THREAD

**Issue by sushma-4** [swcarpentry/shell-novice#1466]
### What is the problem?

![image](https://github.com/user-attachments/assets/7b0a2c6e-be49-4fad-b596-222d6e9ad2be)
In this particular piece, my shell seems to print all files ending in A followed by files ending in B, instead of the alternate A's and B's in the output here. Not sure if it is shell dependent but a note might be helpful if it is.

### Location of problem (optional)

https://github.com/swcarpentry/shell-novice/blob/main/episodes/05-loop.md

**Comment by bkmgit** [comment]
@sushma-4 Thanks for the feedback. Made a pull request to fix it.  Further feedback is welcome.
