### ISSUE TITLE
Data type error

### ISSUE THREAD

**Issue by Galileo72** [swcarpentry/shell-novice#1468]
### How could the content be improved?

Hi !

Learning in this awesome [link](https://datacarpentry.org/python-ecology-lesson-es/02-starting-with-data.html)   when you use "grouped_data.mean()" must be use 
"grouped_data.mean(numeric_only=True)"  cos have an issue regarding TypeError.
Helped by AI, I fix the issue as show below :

```python
grouped_data.mean()
```

#### Hypothesis

The traceback indicates a TypeError that likely occurred during the calculation of the mean. The error message "Could not convert string 

#### Suggested Changes

 Calculate the mean of each column by sex, excluding non-numeric columns
```python
grouped_data.mean(numeric_only=True)
```
Thanks a lot for your great work teaching Pandas in Python.
Greetings from Argentina.

**Comment by bkmgit** [comment]
@Galileo72 Hola, por favor plantee el problema aquí: https://github.com/datacarpentry/python-ecology-lesson-es/issues
