### ISSUE TITLE
.tmp and .my.log hidden files extraneous?

### ISSUE THREAD

**Issue by jttkim** [swcarpentry/shell-novice#155]
There's an emtpy file called `.tmp` in `data/Users/larry`, and there are `.tmp` files in other directories as well. Likewise, there are empty files `.my.log` in some directories. `find data -name '.*' -print` prints a full list of dotfiles.

My impression is that only `data/Users/nelle/.bash_profile` could serve any didactic purpose (other than perhaps some "easter egg hunt" type challenge). Is this correct, and if so, should we get rid of these `.tmp` and `.my.log` files?

**Comment by gvwilson** [comment]
Good catch - yes, I believe the .tmp files should go.  We should add an 
entry to .gitignore to exclude them in future.

**Comment by ChristinaLK** [comment]
I put them there because I didn't think I could commit the directories if they were empty.  If that's not true, then they can be removed.

**Comment by drj11** [comment]
@ChristinaLK you're write that git can't commit empty directories. If you need that, you add a dummy file as you did.

There is a convention of calling these files `.gitkeep` but it is entirely an unenforced social convention.  See http://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep

**Comment by r-gaia-cs** [comment]
#165 tries to address this issue.
