### ISSUE TITLE
Output samples

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#166]
At 01-filedir.md we have

```
$ ls -F
creatures/  molecules/           pizza.cfg
data/       north-pacific-gyre/  solar.pdf
Desktop/    notes.txt            writing/
```

where the output is alphabetic sorted by columns and

```
$ ls -F data
amino-acids.txt   elements/     morse.txt
pdb/              planets.txt   sunspot.txt
```

where the output is alphabetic sorted by lines.

This is bugging me.

I previous suggested to implicit use flag `-1`, see #131. I'm OK to not use it but could we agree in how to sort `ls` output and the numbers of maximum of columns?

@wking I was trying to use [shopt](http://ss64.com/bash/shopt.html) to unset `checkwinsize` and fix the number of columns but didn't work. Any advice?

**Comment by ChristinaLK** [comment]
I think we should just make our lesson output the same as what you would see on a bash window (which is alphabetically by columns, yes?).

**Comment by r-gaia-cs** [comment]
> I think we should just make our lesson output the same as what you would see on a bash window (which is alphabetically by columns, yes?).

@ChristinaLK I'm OK with your decision here as long as the output samples are compatible and we mention it in our documentation. =)

**Comment by gdevenyi** [comment]
I think the issues we may be running into here and that different users will be on differ operating systems, with different default "ls" invocations hidden within their default .bashrc.

No matter what we decide on, it will not always be consistent with the learners, unfortunately.

**Comment by shwina** [comment]
Unfortunately, we can't be sure of what learners will see when they type in "ls". How about adding a note that:

"Depending on your operating system and configuration, the output of ls may be sorted alphabetically, by size, or some other parameter". (?)

**Comment by gcapes** [comment]
Does anyone still feel strongly about this? It looks like the summary of this issue and #133 is that there will be differences in how the output is displayed, and that we won't worry about it?

**Comment by gdevenyi** [comment]
@gcapes I think the solution here is to add a callout box very early to note
- the exact output here will be *slightly* different in formatting to what you are likely to see
- the exact output the instructor shows is also likely to be slightly different
- this is due to different defaults on various systems but the core info remains the same.

**Comment by deppen8** [comment]
Looks like this is resolved: `ls` is taught before `ls -F` and suitable caveats are in the text. Closing as part of old issue cleanup.
