### ISSUE TITLE
highlight diagram for exercises in 01-filedir

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#168]
In `01-filedir.md`, the exercise "ls reading comprehension" isn't in conformance with our example filesystem.

**Comment by ChristinaLK** [comment]
it's meant to go with the diagram directly above - so maybe the change should be to make that more obvious.

**Comment by jevbelikov** [comment]
Related to this issue: should the figures be numbered for ease of referencing or should they be referenced by caption?

**Comment by ChristinaLK** [comment]
Caption (as you did) is fine.  I don't think any of the lessons use numbers.
