### ISSUE TITLE
Improve paragraph about control keys

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#169]
In `02-create.md` we

- [x] should mention that `^` means the control key before using "Control-O".
- [x] should mention that in some keyboards the control key is the "Ctrl".
- [x] should use only "Control", not "control".
- [x] **on Mac OS X**, control really means control and not command.

**Comment by ChristinaLK** [comment]
when you say that `^` means control from the beginning, where were you thinking?  
otherwise, +3

**Comment by r-gaia-cs** [comment]
> when you say that ^ means control from the beginning, where were you thinking?

In replacing

> Let’s type in a few lines of text, then use Control-O to write our data to disk:

with

> Let’s type in a few lines of text, then press `^0` *that is the Unix way to say hold the Control key and press `O`) to write our data to disk:

**Comment by gdevenyi** [comment]
I agree with these changes, I'll try and get them done.

**Comment by bsmith89** [comment]
Claiming this issue for the Bug BBQ (we're demoing how to do a pull request).

**Comment by Ry4an** [comment]
Merged fix.  Probably closeable.

**Comment by gdevenyi** [comment]
Resolved!
