### ISSUE TITLE
Move "Another Useful Abbreviation" for the begin

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#171]
In `02-create.md`, the call out "Another Useful Abbreviation" shouldn't be at the end.

**Comment by ChristinaLK** [comment]
I would say we should move this to 01-filedir.md.  I know that I vetoed that in the past, but I think it belongs there.  Might require a bit of rewriting to find the right place.

**Comment by rgaiacs** [comment]
Out of date.

Thanks to @ab120 for commit 74fbea8a1e5a15c400dc492e1d25147807b6cbf9.
