### ISSUE TITLE
Improve exercise "Moving and Copying"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#172]
In `02-create.md`, the exercise "Moving and Copying" isn't in conformance with our example filesystem.

**Comment by ChristinaLK** [comment]
I think that's okay - maybe as an intro to the exercise, learners should try drawing the contents of the directory/filesystem, since they don't actually have these files in front of them.

**Comment by gcapes** [comment]
Closing stale issue. Please re-open if this issue still applies.
