### ISSUE TITLE
Clarify exercise "Listing Directories and Files"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#173]
I think the exercise "Listing Directories and Files" in `02-create.md` isn't very clear.

**Comment by ChristinaLK** [comment]
agree.

**Comment by pschloss** [comment]
Sorry for all of the nuisance references above, still getting the hang of submitting multiple pull requests to the same repository. As I indicated in my commit message, IMHO this exercise has little to do with "Listing Files and Directories" and more to do with organization of files and directories. That is the path I took with my pull request.

**Comment by ChristinaLK** [comment]
Haha, no problem.  I'll review the PR.
