### ISSUE TITLE
Add example of expression with more than one word for grep

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#174]
In `06-find.md', there are no example of search for a expression with more than one word.
What about add "is not" in the begin?

**Comment by pschloss** [comment]
This is my first PR with SWC. :)

One thing I wonder in reference to this issue is why grep is taught without quotes in the first place. It would certainly seem a lot safer in the long run to teach quotes from the get go.

**Comment by ChristinaLK** [comment]
I agree - I'll leave some ideas on your pull request

**Comment by gdevenyi** [comment]
Changes merged
