### ISSUE TITLE
Move man page for 01-filedir.md

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#176]
What about move the note about man page to `01-filedir.md` instead of `06-find.md`?

**Comment by ChristinaLK** [comment]
There's already a lot going on in 01-filedir.md (esp. if we move the "home dir/~" callout there #171), but I do agree it should appear earlier in the lessons overall.  I actually think the best would be to move it to `discussion.md` or `reference.md` and then do a callout in the lesson that links to the appropriate doc.

**Comment by ChristinaLK** [comment]
See also #55
