### ISSUE TITLE
Start with "find ." instead of "find . -type d"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#178]
In `06-find.md` our first example about find is `find . -type d`. I think that we **must** start with `find .`.

**Comment by ChristinaLK** [comment]
Can you explain why you want this change?

**Comment by r-gaia-cs** [comment]
> Can you explain why you want this change?

Because `-type d` is one of the many filters of `find` and I think that show the "default" output will help learners understand `find`. And will not take more than one minute to explain `find .`.

**Comment by gdevenyi** [comment]
+1 for this change, lets start with the simplest example first.

**Comment by gdevenyi** [comment]
Resolved
