### ISSUE TITLE
Mention flag "-exec" of "find"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#179]
What about mention flag `-exec` of `find`? I think it useful and one powerful example for convincing students to try the shell.

**Comment by iglpdc** [comment]
+ 1

**Comment by gvwilson** [comment]
But what do we take out to make room for this addition?  Because `{} \;` 
is going to take some explaining...

**Comment by r-gaia-cs** [comment]
> But what do we take out to make room for this addition?

"-mindepth" and "-maxdepth". See #180.

**Comment by ChristinaLK** [comment]
see UW Madison customized bootcamp curriculum for some ideas: 
https://github.com/UW-Madison-ACI/boot-camps/blob/2015-06-03/shell/Readme.md
(near the end)

**Comment by gvwilson** [comment]
@rgaiacs please PR and I'll review.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
