### ISSUE TITLE
Drop flags "-mindepth" and "-maxdepth" of "find"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#180]
I think that we can drop the flags `-mindepth` and `-maxdepth` of `find`. Students can always find them looking at the man page.

**Comment by drj11** [comment]
I've always found the flags obnoxiously GNU specific.

+1

**Comment by jevbelikov** [comment]
+1  "-exec" seems more useful

**Comment by Ry4an** [comment]
Added a no-new-content PR for this.

**Comment by gdevenyi** [comment]
Resolved.
