### ISSUE TITLE
Would tee be helpful?

### ISSUE THREAD

**Issue by SamPenrose** [swcarpentry/shell-novice#182]
The Unix command tee duplicates STDOUT and sends the second copy to a file. Since reading scrollback is a core skill for working with the shell, would it make sense to incorporate the use of tee into the lesson? Because tee preserves STDOUT, it allows recovery from actions that overwhelm the buffer of your shell's window.

**Comment by lexnederbragt** [comment]
Something for the in-progress "shell-extras" lessons? See https://github.com/swcarpentry/shell-extras

**Comment by gdevenyi** [comment]
+1 for @lexnederbragt shell-novice is full, but shell-extras is the perfect place.
