### ISSUE TITLE
Small inconsistency between dir structure in shell-novice-data.zip and dir structure in lessons

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/shell-novice#184]
When I click the link to download the `shell-novice-data.zip` file I get a file structure that has a folder `users/` instead of `Users/` (which is what is used throughout the lessons. Note that cloning the git repo yields a directory structure consistent with the lesson plans.

**Comment by ChristinaLK** [comment]
I thought the zip had been re-done after we made that change - thanks for bringing this up.

**Comment by davidrpugh** [comment]
No worries @ChristinaLK.
