### ISSUE TITLE
Use of cat in lesson-5 on scripting

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/shell-novice#185]
In lesson 5 the command `cat middle.sh` raises the following error in my terminal:
```
cat: middle.sh: No such file or directory
```

I think that the command should be `cat > middle.sh` which them allows the user to input commands
```
head -15 octane.pdb | tail -5
```
straight into the newly created `middle.sh` file. Once finished student then needs to hit `CTRL-D` the buffer.

Am I missing something?

**Comment by mikemhenry** [comment]
I noticed the same thing. I think either introducing using cat for quick file creation like this could be introduced as @davidrpugh describes or just explicitly stating something like "Use your favorite text editor to create a file named middle.sh with the following line"

**Comment by ChristinaLK** [comment]
I think it's supposed to be `nano` instead of `cat` - that change has been made.
