### ISSUE TITLE
What changes should we make for our 5.4 release?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#194]
Please use this issue for discussion of changes we should make by mid-August 2015.

**Comment by ChristinaLK** [comment]
These can each spawn more specific issues to be worked on: 

[ ]: read through learning objectives + confirm that lesson content matches.  Do we need new objectives?  To remove others?  
[ ]: Look at callouts + what purpose they serve.  Are there points where callout text should be re-integrated into main text or moved to `discussion.md`, `reference.md`?  
[ ]: In general, having more a list of interactive exercises - either for instructor demo or student participation, not just multiple choice questions.  Pull from what people have actually used in workshops!

**Comment by ChristinaLK** [comment]
Will tag other already open issues that we'd like to complete w/ the milestone

**Comment by ChristinaLK** [comment]
Issues I would really like to see addressed are: 
- moving homedir callout ("another useful abbrevation") from 02-create to 01-filedir (#171)
- better handling of man pages / getting help (#55 #176)

**Comment by ChristinaLK** [comment]
Also, after train the trainers today, a "solution" page for the exercises, with solutions and - more importantly - what concept the question is trying to test and what misconceptions are attached to the wrong answers.

**Comment by gvwilson** [comment]
*  Maxime Boissoneault asked about the use of '/' with the downloaded files in [this message on the discussion list](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-July/003160.html).
*  Emily Davenport had [the same question](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-July/003161.html).
*  Raniere Silva [explained what he does](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-July/003162.html).
*  Amanda Charbonneau explained why [she finds the whole 'Files and Directories' page difficult to teach](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-July/003163.html).

**Comment by spthm** [comment]
Slightly off topic(?), but I'd like to second Raniere's [most recent message](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-July/003167.html). Pretty much the first thing I get students to do after showing them `pwd` is
```bash
export PS1='\u@\h:\w$ '
```
and then, if they want it to be permanent,
```bash
echo "export PS1='\u@\h:\w$ '" >> ~/.bashrc
```
(FYI this means your prompt is `user@host:<current directory>$ `, and note the space after `$`. Some wifi networks seem to make the `\h` `host` variable unintelligible, at least on mac, so it might be better to use Raniere's simpler variant.)

I haven't actually taught the shell lesson; this is based on my experience with an introductory programming course at my university: students are fine navigating folders, but forget where they are, and thus end up losing track of files in directory structures of the form
```plain
problem1/
    solution1.sh
    problem1/
        solution1.sh
    problem2/
        solution2.sh

problem3/
```
You see the 'problem'...

Modifying the PS1 value is somewhat esoteric, but useful. I believe it would be worth adding a little bit about having the current directory in your prompt to the material.

**Comment by mboisson** [comment]
Going through the tutorial, I find that there is a problem with the final loop that Nelle runs, i.e. 

for datafile in *[AB].txt; do echo $datafile; bash goostats $datafile stats-$datafile; done

The problem is that if you run the loop twice, it will actually take "stats-$datafile" as the input for the second run, as well as the original files. 

A slightly more complex, but correct loop, would be 
for datafile in N*[AB].txt; do echo $datafile; bash goostats $datafile stats-$datafile; done

**Comment by mboisson** [comment]
I also find that it would be useful to have a directory with the exercises at the end of the lessons. Instead of having "Suppose that ls initially displays:" ... and having people who need to think about what the answer might be, they can actually try it for themselves.

**Comment by rgaiacs** [comment]
@ChristinaLK, @gdevenyi and @gvwilson What do you think of collecting Nelle’s examples as a capstone exercise? I like the Nelle's text but I never taught it due time limitation.
