### ISSUE TITLE
change title of 02-create.md?

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/shell-novice#199]
from #140, have a more general title as this lesson covers deleting and copying/moving too

**Comment by jevbelikov** [comment]
I find it surprisingly difficult to come up with a good name for this one that is not long (Creating, Moving, Copying, Removing Files and Directories') and not too abstract ('Manipulating Files and Directories'). I find 'Things' a little bit to informal and unspecific. How about: 'Operations on Files and Directories'?

**Comment by Ry4an** [comment]
"File and Directory Manipulation"
"Working with Files and Directories"
?

**Comment by jevbelikov** [comment]
@Ry4an: +1, your second suggestion is my favourite so far

**Comment by datamat** [comment]
@Ry4an: +1 for your second suggestion!

**Comment by shwina** [comment]
+1 for "Working with Files and Directories". To avoid confusion with the "Files and Directories" module, may I also propose changing the title of `01-filedir.md` to something like "Finding Your Way Around"? This section is really about filesystem navigation.

**Comment by Ry4an** [comment]
Spun up a tiny PR ( #378 ) to with the suggestions thus far.

**Comment by Ry4an** [comment]
The PR went through with the title change, but I mistakenly thought that was interpolated more places than it is. I'm going to follow up with a PR to correct all the references to those sections.

**Comment by Ry4an** [comment]
Tacked on #379 to fix the internal link text. Sorry for missing that on the first go round.

**Comment by Ry4an** [comment]
Looks like this got merged today.  I think we're good to go. @ChristinaLK assigning to you for closing I guess.

**Comment by Ry4an** [comment]
n/m looks like I can't assign.  I'll go mention it in the etherpad.

**Comment by gdevenyi** [comment]
Resolved!
