### ISSUE TITLE
changes to loops

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/shell-novice#200]
item 6 from #140:
'Loops': could mention automation of repetitive tasks as motivation and add a sentence explaining semicolon as separator (useful in one-liner scripts)

**Comment by r-gaia-cs** [comment]
+1.

Something that I learned from @kstatebioinfo is that we request that learners use the up arrow key to discovery the semicolon. =)

**Comment by Ry4an** [comment]
Looks like this was well addressed in a merged PR and hte parent issue #140 closed.  This can be closed too, right, @ChristinaLK?

**Comment by ChristinaLK** [comment]
yes
