### ISSUE TITLE
teaching tool

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/shell-novice#203]
Create a pre-built page w/ all the diagrams (w/ a "table of contents" at the top and in-page links)

**Comment by r-gaia-cs** [comment]
@ChristinaLK I can try do it upstream after we agree on http://software-carpentry.org/blog/2015/06/using-jekyll-for-lessons.html.

**Comment by gdevenyi** [comment]
Jekyll is not being used anymore, is there work afoot upstream?

**Comment by gvwilson** [comment]
Yes - I'm going to poll the maintainers in a couple of weeks about ditching Pandoc and going to a pure Jekyll solution so that we don't have to compile/check in the HTML (and so that instructors are using the same toolchain they'll use if they're writing GitHub Pages).  Stay tuned...

**Comment by gdevenyi** [comment]
Redirected to the new-lesson-example repo.
