### ISSUE TITLE
Style at discussion

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#221]
https://swcarpentry.github.io/shell-novice/discussion.html has some style for `CTRL+c` that is only used there.

![screen shot 2015-08-30 at 16 19 54](https://cloud.githubusercontent.com/assets/1506457/9569014/03ecce32-4f33-11e5-91b1-00c194e0375e.png)

I would like to (1) change the style to the one used in the rest of the lessons or (2) change the style of the rest of the lessons to the one used in this page.

**Comment by gvwilson** [comment]
Please remove it from discussion.md - it's created using `<kbd>`, 
whereas we use back quotes to get `<code>` elsewhere.

**Comment by gvwilson** [comment]
p.s. it's a shame there *isn't* a standard Markdown notation for `<kbd>` ...
