### ISSUE TITLE
HTML need update

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#222]
https://swcarpentry.github.io/shell-novice/01-filedir.html has one bad formatted call out box:

![screen shot 2015-08-30 at 16 30 39](https://cloud.githubusercontent.com/assets/1506457/9569065/8e48512c-4f34-11e5-8888-1658f1f86dc1.png)

The Markdown is fine, just the HTML need to be update.

![screen shot 2015-08-30 at 16 30 52](https://cloud.githubusercontent.com/assets/1506457/9569076/bece1fb6-4f34-11e5-946c-8dc445eb8751.png)

Maybe you need to run

~~~
$ make -B preview
~~~

**Comment by ChristinaLK** [comment]
done
