### ISSUE TITLE
zip file need to be update

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#229]
[data](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data) only has `Users` but

~~~
$ wget https://swcarpentry.github.io/shell-novice/shell-novice-data.zip
$ unzip -l shell-novice-data.zip|grep User|sort|wc -l
215
$ unzip -l shell-novice-data.zip|grep user|sort|wc -l  
215
~~~

We should remove `shell-novice-data.zip` and create it from scratch.

**Comment by cbergman** [comment]
It looks like this issue has been dealt with in https://github.com/swcarpentry/shell-novice/pull/232. Should this issue be closed?
