### ISSUE TITLE
History question in shell scripts section

### ISSUE THREAD

**Issue by sstevens2** [swcarpentry/shell-novice#243]
> ## Why record commands in the history before running them? {.challenge}
> 
> If you run the command:
> 
> ~~~
> history | tail -5 > recent.sh
> ~~~
> 
> the last command in the file is the `history` command itself, i.e.,
> the shell has added `history` to the command log before actually
> running it. In fact, the shell *always* adds commands to the log
> before running them. Why do you think it does this?

Hey all,
I'm planning for teaching the shell next week and I noticed the above question.  I wasn't sure of the answer was and when I asked around an others weren't sure either.
It was suggested that this question is trying to get at why it is useful to test the commands individually and in combination before putting them in a script.  Which seems true based on the question in the header but the final part about why history is always added is a bit confusing.

What do you think? Should we keep this question?  Remove it?  Replace it? Reword it?

Thanks!
Sarah

**Comment by naupaka** [comment]
Perhaps because some commands may fail, and thus wouldn't ever get added to the history?

**Comment by sstevens2** [comment]
@naupaka That was my best guess to.

**Comment by gvwilson** [comment]
Commands are added to the history log before being run because back in the early days of the Unix shell, there was a significant chance a command would crash the shell itself (or the entire operating system).  When that happens, you really, *really* want to know what the command was...

**Comment by jni** [comment]
@gvwilson great to know! Now if we could only get the shell to write its history to `.bash_history` _before_ the shell is correctly exited... =P

**Comment by naupaka** [comment]
Can always modify `PROMPT_COMMAND` to do this to an arbitrary text file, e.g. [this post](https://software-carpentry.org/blog/2015/05/instructor-debriefing-2015-04-28.html).
