### ISSUE TITLE
Using "tree" command to teach cd/ls/mv/rm

### ISSUE THREAD

**Issue by SamPenrose** [swcarpentry/shell-novice#244]
Has anyone explored using "tree" as a component for teaching "Files and Directories"? The current version has pre-baked images of a file system as DAG. tree allows students to "draw" the DAG themselves.

Disadvantages:
  - it must be installed on many systems
  - run on large directory sets it produces large output

One alternative to "tree" is paper and pencil.

**Comment by jduckles** [comment]
While not the exact same output, `find .` can show the same thing without a new dependency, not formatted as a DAG, but formatted in the way they'll actually be using a path to reference a specific file. 

Also note that we do cover `find` in the final topic, and associate it to the directory tree diagram: http://swcarpentry.github.io/shell-novice/06-find.html

**Comment by SamPenrose** [comment]
Great, thanks for clueing me in.
