### ISSUE TITLE
Should bash strict mode be recommended as good practice?

### ISSUE THREAD

**Issue by peterjc** [swcarpentry/shell-novice#251]
I appreciate deciding what important things not to include in an short session is very difficult, but based on searching the repository via GitHub this may not have come up before:

``` bash
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
```

See http://redsymbol.net/articles/unofficial-bash-strict-mode/

Personally I use ``set -e`` most heavily, and generally just use the one line ``set -euo pipefail`` after the hash-bang.

**Comment by drj11** [comment]
I think it's a good idea (personally, I would remove `-o pipefail` because it's not portable), but I worry about the cognitive load (one more straw breaking the camel's back).

**Comment by tomwright01** [comment]
Great article, it taught me many things I didn't know. -1 for including it in shell-novice, currently we don't even introduce the hashbang. Would be a good addition for an extension lesson "making robust shell scripts".

**Comment by iglpdc** [comment]
I also think that it's too advanced for the novice lesson, but great as an
extra or part of the intermediate lesson.

**Comment by peterjc** [comment]
So should I close this issue and re-open it on https://github.com/swcarpentry/shell-extras instead?

**Comment by ChristinaLK** [comment]
yes, that would be great!

**Comment by peterjc** [comment]
Closing in favour of https://github.com/swcarpentry/shell-extras/issues/30
