### ISSUE TITLE
Loop file "don't do this" examples

### ISSUE THREAD

**Issue by stanfodder** [swcarpentry/shell-novice#252]
I wouldn't immediately spot there were examples of bad practice in the documentation whilst bashing through to learn. It would be good to somehow distinguish a bad practice example, from a good practice example. For example a different colour box, or a cross or tick in the right hand side of the box.

Also a typo:
This a problem arises when cp receives more than two inputs.
should probably be:
A problem arises when cp receives more than two inputs.
or
Thus a problem arises when cp receives more than two inputs.
or something similar.

**Comment by iglpdc** [comment]
@stanfodder thanks for catching the typo! Do you want to send a pull request with the fix?

**Comment by gdevenyi** [comment]
Need a PR or lines to fix.
