### ISSUE TITLE
Remove mentions of man pages

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/shell-novice#26]
man pages aren't installed on all systems, we can't teach them in the main material

Replace with google instructions?

**Comment by wking** [comment]
On Thu, Nov 27, 2014 at 07:02:30PM -0800, Gabriel A. Devenyi wrote:
> man pages aren't installed on all systems, we can't teach them in
> the main material
> 
> Replace with google instructions?

There's more discussion on this issue in #55.  We should probably
consolidate to a single issue and close the other.
