### ISSUE TITLE
Wrong PS1 definition in 01-filedir.html (but correct in markdown source)

### ISSUE THREAD

**Issue by mstimberg** [swcarpentry/shell-novice#267]
The HTML file (and therefore the lesson online) asks the user to set `PS1='$ '1'` instead of `PS1='$ '`. Apparently the HTML is based on an earlier version of the markdown file, the typo had already been fixed in the markdown source on Oct 19 2015 (a7da9b9).

**Comment by cbergman** [comment]
I agree that this should be fixed in the HTML fairly soon. Since this command comes is so early in the tutorial, it could really throw a new user off and risk them not completing the lesson.

**Comment by mstimberg** [comment]
This has been fixed with the merge of PR #273 .
