### ISSUE TITLE
01-filedir: "Exploring more ls arguments" challenge

### ISSUE THREAD

**Issue by mstimberg** [swcarpentry/shell-novice#275]
Last year, I taught the shell and finished the first lesson with its last challenge:

> What does the command `ls` do when used with the `-s` and `-h` arguments?

While doing this I noticed two things that I had not anticipated:

1. `-s` does not simply display the size of the files but the "allocated size of each file, in blocks" which I think is a bit of an advanced topic and also will differ quite a bit between different file systems
2. `-h` does not change anything when used on OS X (i.e. with the BSD `ls` command), its documentation (on both Linux and OSX) states that it is for use "with -l", even though on Linux it *does* change the output for `-s`.

Given that the lessons generally stick to the basic commands and options that "work everywhere", I'd rather remove this challenge from the lesson (or maybe adapt it or add an explaining note -- but not sure the `-s` option is important enough for this...). Showing the use of `-l` would certainly be more interesting (since it shows the highly useful last modification date), but unfortunately this also prominently displays permissions and ownership information that are not covered anywhere in the novice lessons.

**Comment by madkiwi23** [comment]
Just a thort, if they have multiple "big" files -h is useful if they want to see file sizes. 
The rest of the stuff you could just give them the means to look it up if they want.
i.e. these are the things you look at, ignore the rest.

ls -la shows in bytes, which for big files is ungainly.
ls -lh shows a more readable size for the files, especially if they are all multi-GB.

e.g.
[root@xxxxxxxxxxxxxxxxxxxxxx ~]# ls -la showreplresults_gpfs1_20150411071911_o10
-rw------- 1 root root 16924672 Apr 13  2015 showreplresults_gpfs1_20150411071911_o10
                file size = 16,924,672 bytes

[root@xxxxxxxxxxxxxxxxxxxxxx ~]# ls -lh showreplresults_gpfs1_20150411071911_o10
-rw------- 1 root root 17M Apr 13  2015 showreplresults_gpfs1_20150411071911_o10
file size = 17M (rounded up/down for M)

**Comment by mstimberg** [comment]
I agree that `ls -lh` is useful -- so your suggestion is to use this in the challenge instead of `ls -sh`? I actually did this when I gave the lesson, but if everybody agrees on it then we should probably change the exercise accordingly.

**Comment by btel** [comment]
I also use `-lh` is much more often than `-sh`. Maybe the intention was to use `-S` argument. But again `-h` makes only sense when combined with `-l` (so `-lSh`).

**Comment by mstimberg** [comment]
Maybe @ethanwhite wants to weigh in with his opinion (given that he added the exercise back then)?

**Comment by ethanwhite** [comment]
Thanks for the ping @mstimberg. I agree that `-s` is too advanced and that `-h` on its own doesn't make a lot of sense. I like the idea of a change to `-lh` since that's something I use regularly as well.

**Comment by madkiwi23** [comment]
I think using -s for blocks is more a "diagnostic" when looking at the file system rather than being useful to a "user" as such.

Using -S to sort by file size I have very rarely used, but...
-lt (or -lrt) to sort by mod date I use quite often when looking for "latest" changed files 
using the -lrt if there are a lot of files and I don't want to scroll back

**Comment by btel** [comment]
-t option is also used in the last exercise in "Creating things" lesson
