### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by btel** [swcarpentry/shell-novice#279]
In "Finding things" lesson, the link to regexp lesson is broken (see Wildcards callout)

**Comment by btel** [comment]
the links seems to be a part of old Software Carpentry website:

http://software-carpentry.org/v4/regexp/index.html

Any idea where to find it now?

**Comment by rgaiacs** [comment]
@gvwilson Did we drop v4?

**Comment by gvwilson** [comment]
See https://github.com/swcarpentry/website/issues/192
