### ISSUE TITLE
"find pipeline reading comprehension" exercise

### ISSUE THREAD

**Issue by btel** [swcarpentry/shell-novice#280]
This one-liner from exercise "`find` pipeline reading comprehension" in "Finding things" lesson:

`find . -name '*.dat' | wc -l | sort -n`

 will always print a single line (the number of .dat files in the current dir and its subdirs), so sort at the end of the pipeline is not necessary.  Since the goal of the exercise is to write an explanatory comment, it may be confusing.

Perhaps this command would make more sense:

`wc -l $(find . -name '*.dat')  | sort -n`

**Comment by drj11** [comment]
I wonder if

```
find . -name '*.dat' | xargs wc -l | sort -n
```

was intended (It's "morally equivalent" to yours).

**Comment by btel** [comment]
It might be, but the `xargs` is not introduced in the lesson, so it may be hard to comprehend. The `$( )` expression is used with find in this lesson, so I think it would be easier for the students.

**Comment by drj11** [comment]
Good. I didn't bother checking the lesson to see if `xargs` was already introduced and should've said that.

**Comment by gdevenyi** [comment]
PRs welcome to fix this.
