### ISSUE TITLE
Dead link to discussion.html

### ISSUE THREAD

**Issue by wking** [swcarpentry/shell-novice#29]
The `discssion.md` source was removed with 3eaab252 (Removing example files (they belong in the gh-pages branch), 2014-12-11) but the link was added to `index.md` with 59fc96f76 (Reformatting home page, 2014-12-17).  Maybe we should have some stub content in `discussion.md`?  Or leave the link off until we have a browsercast slide deck to put there?

**Comment by gvwilson** [comment]
Discussion file added in 00ff80e119
