### ISSUE TITLE
Front page instructions for unzipping .ZIP file are wrong?

### ISSUE THREAD

**Issue by MikeTheGreat** [swcarpentry/shell-novice#293]
I was looking through the instructions for downloading the .ZIP file on the index page and I believe that the instructions for extracting the .ZIP file are wrong.

On [the front page](https://github.com/swcarpentry/shell-novice/blob/gh-pages/index.md), under the 'Getting Ready' section step #2 reads
> Double-click on the zip file to unzip it. You should end up with a new folder called data-shell.

This is definitely wrong for Windows (10, 8, and I think 7).  **On Windows if you double click on a .ZIP file it will show you the contents of the .ZIP file as if it were a normal folder but it does not actually extract it.**

On Windows one should right-click on the .ZIP file, then select "Extract All...", and then pick where to put it.

I'm opening up an issue (instead of submitting a pull request) because I'm not sure if the lesson is supposed to be Windows-specific, Windows-and-Mac-specific, or platform agnostic.

**Maybe the fix here is to include accurate instructions for both Windows and Mac**?

**Comment by gdevenyi** [comment]
Can we rely on learners to know how to unzip a file? This is a place where installed software can seriously change the given experience.

**Comment by iglpdc** [comment]
In MacOSX the zip files uncompress automatically. In Windows you have to do the "Extract all " thing. I never have a problem during a workshop with that. Either because people know how to do it, or because they are asked to copy the file afterward to the Desktop and the combination works.

@MikeTheGreat, do you know if this (double click and then copying the contents of the zip file) would work on Windows?

**Comment by MikeTheGreat** [comment]
@iglpdc **Yes** - Double-clicking the .ZIP will show the contents inside the .ZIP, and then when you select them all and copy them to another (non-compressed/non-.ZIP) folder Windows will extract the files as it copies them.

That said - I don't see where in the lessons is says to copy the contents of the .ZIP to a new location.  The next time that the contents are mentioned is in [01-Files and Directories](https://github.com/swcarpentry/shell-novice/blob/gh-pages/01-filedir.md) file, where it seems to assume that the .ZIP has been extracted onto the Desktop (it sounds like this is exactly what will have happened, on a Mac).

Thinking about it, I think my concern is that the instructions specifically tell students to do the wrong thing on Windows.  Inexperienced Windows users will double-click the file and then Windows will show them a folder that appears to be a normal folder containing normal files.

I wonder about rephrasing this as "~~Double-click on the zip file to u~~Unzip**/extract** ~~it~~**the file**. You should end up with a new folder called data-shell."

If you want to include platform-specific instructions for unzipping you could include more specific directions (or links to directions) under that item.

**Comment by shwina** [comment]
@MikeTheGreat @iglpdc 

How about:

> Unzip/extract the file (ask your instructor if you need help with this step). You should end up with a new folder called `data-shell` on your Desktop.

**Comment by MikeTheGreat** [comment]
This looks good to me!


--Mike
Date: Tue, 16 Feb 2016 09:55:43 -0800
