### ISSUE TITLE
Link for regexp broken

### ISSUE THREAD

**Issue by dvanic** [swcarpentry/shell-novice#295]
Hi! The link to ["if you want to do complex searches, please look at the lesson on our website."](http://software-carpentry.org/v4/regexp/index.html) is broken, given a 404 error. Where should the link be pointing to?

**Comment by gdevenyi** [comment]
Looks like our regex lesson has been depreciated, will need to find the archived version

**Comment by gdevenyi** [comment]
Duplicate of #279
