### ISSUE TITLE
colrm seems not to be included in the windows installer

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/shell-novice#296]
At a workshop today, learners who used the SWC Windows installer didn't have the `colrm` command available (used in http://swcarpentry.github.io/shell-novice/05-script.html).

**Comment by wking** [comment]
On Mon, Feb 01, 2016 at 03:07:17AM -0800, Lex Nederbragt wrote:
> At a workshop today, learners who used the SWC Windows installer
> didn't have the `colrm` command available…

colrm (from util-linux [1], but possibly with other providers as well)
isn't in POSIX [2].  That colrm callout dates back to 8e77786c
(Importing shell lesson for novices, 2013-11-11), and I haven't traced
it back further, but I think we should just remove it.

[1]: https://git.kernel.org/cgit/utils/util-linux/util-linux.git/tree/text-utils/colrm.1?h=v2.27.1
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html

**Comment by drj11** [comment]
or replace it with `cut`?

I think I'd rather the callout got removed (I agree with @wking).

**Comment by lexnederbragt** [comment]
As `cut` isn't really a part of the lesson material, I opted for removing, see #303
