### ISSUE TITLE
re: http://swcarpentry.github.io/shell-novice/   "cd"

### ISSUE THREAD

**Issue by Thaerious** [swcarpentry/shell-novice#299]
In the page http://swcarpentry.github.io/shell-novice/ it says the following 

> You need to download some files to follow this lesson:
> 
> Download shell-novice-data.zip and move the file to your Desktop.
> Double-click on the zip file to unzip it. You should end up with a new folder called data-shell.
> Open a terminal and type:
> $ cd
> In the lesson, you will find out how to access the data in this folder.

Should there be something after cd?  Or am I missing the point of just typeing "cd"?  Presumably it should be '$ cd data-shell'

**Comment by Thaerious** [comment]
Edit:  I see that you mean to have them call into their home directory.  The notes don't mention this.

**Comment by iglpdc** [comment]
Nop, the instructions are missing one part. Compare to [the equivalent in the python lesson](http://swcarpentry.github.io/python-novice-inflammation/#getting-ready).

@Thaerious can you reopen the issue?

**Comment by ChristinaLK** [comment]
@iglpdc with the lesson rewrite, we *do* want them to start in their homedir, the lesson will get them to the data directory.  

@Thaerious, is there any place I could add notes to make this more clear?

**Comment by Thaerious** [comment]
I have given the seminar since I posted that comment.  I found that at the beginning I was still trying to get the participants up and running and didn't get into cd until part 2, files and directories.  I had to explain directories before explaining home directories and then 'cd'.

**Comment by marwahaha** [comment]
Is there any way I can help here? @Thaerious

**Comment by deppen8** [comment]
There is now an explanation for this in the setup instructions. Closing as part of old issue cleanup.
