### ISSUE TITLE
bash middle.sh has typos with hyphens

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/shell-novice#322]
Currently the user puts this into `middle.sh`:

    head -n "$2" "$1" | tail -n "$3"

And are told to run it like so...

    $ bash middle.sh pentane.pdb -20 -5

This gives an error: 

    head: 20: No such file or directory
    tail: 5: No such file or directory

A similar problem crops up further down the tutorial where they are asked to add comments to `middle.sh`

**Comment by shwina** [comment]
Thanks for your PRs @pschloss!
