### ISSUE TITLE
tail output on wc command is wrong in pipefilter tutorial

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/shell-novice#324]
The tutorial currently has:

    $ wc -l *.txt | sort -n | tail -n 5
    300 NENE02040A.txt
    300 NENE02040B.txt
    300 NENE02040Z.txt
    300 NENE02043A.txt
    300 NENE02043B.txt

But this is missing the real final line that produces the total number of lines across all files. The actual output is:

```
 300 NENE02040B.txt
 300 NENE02040Z.txt
 300 NENE02043A.txt
 300 NENE02043B.txt
5082 total
```

**Comment by shwina** [comment]
Thanks!
