### ISSUE TITLE
Don't teach "rmdir"

### ISSUE THREAD

**Issue by DanielBaird** [swcarpentry/shell-novice#337]
Immediately after teaching `rm`, we teach `rmdir`, along with the paragraph or two to explain that it doesn't work when there's content in the dir you're removing.

Then in an callout we teach `rm -r` and warn learners about its potential for catastrophe.

`rmdir` seems useful in tiny example-sized situations with few files and shallow directory trees, but in practice I think learners will / should always use `rm -r` (with a mandatory pause before hitting enter).

So here's an opportunity to remove some content.  Unless anyone disagrees, I'll have a go at rewriting the rm / rmdir / rm -r section to leave out rmdir, and submit a pullreq for comment...?

**Comment by shwina** [comment]
I'm +1 for this - thanks.

**Comment by plijnzaad** [comment]
I concur.

**Comment by gdevenyi** [comment]
PRs welcome.
