### ISSUE TITLE
Using expr in 04-loop.md ...

### ISSUE THREAD

**Issue by plijnzaad** [swcarpentry/shell-novice#344]
In exercise 04-loop.md, I came across the ancient `expr` command. Noone uses that anymore these days. Would it not be better to replace it with `$[ 3 + 5 ]` ? (I will submit a pull request to this effect later on)

**Comment by shwina** [comment]
Thanks @plijnzaad 

I'm no expert on portable bash scripting, but based on the discussion [here](http://stackoverflow.com/questions/2415724/bash-arithmetic-expression-vs-arithmetic-expression), the `$((3+5))` form is preferable.

**Comment by gvwilson** [comment]
I still use `expr` to avoid yet another layer of parentheses in my 
expressions - as with teaching people to run scripts with `bash 
myscript.sh` instead of changing permissions and adding a `#!`, it's not 
how proficient users do things, but it saves us having to explain 
another layer of shell-ism to novices.

**Comment by jttkim** [comment]
Adding to @gvwilson's comment I'd also say that if a script does so much / so complex arithmetics that using `expr ...` vs. `$[ ... ]` vs. `$(( ... ))` makes any real difference, it quite certainly wants to be written in another language that provides proper numerical types.

Variable values in the shell are basically always strings, using bash-isms don't change that. bash-isms been brought in at a time when the overhead of starting an external process was much more of a concern that it is today.

**Comment by plijnzaad** [comment]
@Ashwin: good call, and @Jan: I wholeheartedly agree. See also my pull request.

**Comment by plijnzaad** [comment]
(This could be considered part of my instructor training/certification 'home work', see also https://github.com/swcarpentry/shell-novice/issues/349)

**Comment by gdevenyi** [comment]
Looks like this has been resolved.

**Comment by jan** [comment]
@plijnzaad Please don't use "@Jan" unless you want to talk to me. ;-)
