### ISSUE TITLE
Adding section on 'setting up gitbash' that includes how to enable copy/paste

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/shell-novice#346]
Ad idea from a debriefing session with @rgaiacs @weaverbel

By default gitbash on Windows doesn't allow copy/paste. We run in to this in every workshop, and it can be really frustrating for learners and instructors, so it would be good to include this right in the lesson. There could be a 'Setting up gitbash' section, like there is for 'setting up RStudio' for R.

Here is information on how to get copy/paste to work
https://www.udacity.com/wiki/ud775/git-bash-copy-paste

**Comment by shwina** [comment]
Great suggestion! I'll open a PR

**Comment by gdevenyi** [comment]
I wondering, should this be documented in the install instructions instead?

**Comment by evanwill** [comment]
the default terminal for Git Bash for windows is now MinTTY, so this copy/paste issue doesn't come up with the default install. I think the SWC windows installer suggests/links to an out of date version of Git for Windows, so people with this issue might be installing an old version?

**Comment by cjieming** [comment]
Hi I am new here, trying to complete my instructor checkout. I was a helper for a couple of workshops before and ran into this problem. I can try to incorporate this into the 'Setting up Gitbash' section so that it gets included everytime the website for each SWC workshop gets set up. Is that ok?

**Comment by rgaiacs** [comment]
@cjieming Thanks for your offer. I would ask you to hold any pull request until we make a decision if we are going to stay with Git Bash or move to another terminal emulator (see https://github.com/swcarpentry/workshop-template/pull/391, https://github.com/swcarpentry/workshop-template/issues/394, https://github.com/swcarpentry/workshop-template/issues/394, https://github.com/swcarpentry/workshop-template/issues/395).

**Comment by deppen8** [comment]
Not sure if this is still an issue with modern systems and versions of GitBash. (I only have MacOS.)

In any case, this issue might be more appropriate for the workshop template repo, which is where the detailed instructions for git can be found. https://github.com/carpentries/workshop-template

Closing as part of old issue cleanup.
