### ISSUE TITLE
Issue with downloading data instructions in Getting ready section

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/shell-novice#347]
I just tested the instructions for downloading data in **Getting ready** as this has been a bugbear in lots of classes I have taught. I got the data on my desktop with no issues but the next step (open terminal, enter `cd`) won't do the same thing for all people so it probably needs to be amplified - maybe with different instructions for different operating systems. My Windows laptop opens a terminal on a different drive for a start (a networked drive) so my home directory is on a different drive from the downloaded data. To navigate to the data, I needed first to get to the C drive, and then it took a bit of navigating to get to the data on the Desktop from there - there's a complicated path through `Users`. On Gitbash or cygwin terminals, you can't just do `cd c` to change to the C drive, you have to do `cd c:/` which would stump a lot of people. I am happy to teach `wget` for the data download in classes as this teaches them how to do something useful, but it often doesn't work on Macs where the command they need is `curl -O`. So both should be mentioned.

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 06:56:56PM -0800, Belinda Weaver wrote:
> I am happy to teach `wget` for the data download in classes as this
> teaches them how to do something useful, but it often doesn't work
> on Macs where the command they need is `curl -O`.

Does Git for Windows not come with a curl command?  Their build
repository certainly uses curl a number of times [1].

[1]: https://github.com/git-for-windows/build-extra/search?p=1&q=curl&type=Code&utf8=%E2%9C%93

**Comment by weaverbel** [comment]
On Windows, `wget` seems to work - it's just the Macs where we have needed `curl` - and only some of the time ;-( which is why this is a tricky thing to try to write instructions for - talk about aiming at a moving target ...

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 09:04:44PM -0800, Belinda Weaver wrote:
> On Windows, `wget` seems to work - it's just the Macs where we have
> needed `curl` - and only some of the time…

They both work fine, and I use both wget and curl for this sort of
thing.  I was just saying that if curl is always installed, I see no
reason to mention wget at all.  We only need to talk about both if
there are some systems that only include wget and others that only
include curl.  Currently it sounds like:

* Linux: you likely have both
* OS X: you likely have curl, and may have wget
* Git for Windows: you likely have both wget and curl

It would be good to nail down those “likely” and “may” wiggles.  I
have access to amd64 Gentoo installs, and while they only include wget
out of the box [1], all of my systems will include something that
pulls in curl (e.g. GnuPG depends on curl [2]).  Can folks with access
to other systems report on what's available out of the box?

And as an aside, this sort of question will be easier to answer if we
get a GSoC student working on [3] ;).

[1]: https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/base/packages?id=0f9ab4a2ff84c250ae4f6d89668ac40adddcb54e#n37
[2]: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-crypt/gnupg/gnupg-2.1.11-r1.ebuild?id=0f9ab4a2ff84c250ae4f6d89668ac40adddcb54e#n25
[3]: https://github.com/numfocus/gsoc/blob/master/2016/ideas-list-swc.md#write-a-result-aggregation-server-for-the-installation-test-scripts

**Comment by gdevenyi** [comment]
*buntu installs come with both

**Comment by Mahdisadjadi** [comment]
OS X comes with `curl` but not `wget`.

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 10:28:37AM -0700, Mahdi Sadjadi wrote:
> OS X comes with `curl` but not `wget`.

I imagine these are going to be be pretty stable, but can you share
which OS X versions you've checked?

**Comment by gdevenyi** [comment]
I think for now we will keep people using the web browser/GUI for downloading and extracting the example data. The lesson flow just doesn't allow for introducing command-line downloading this early, along with the complications regarding the different operating systems. Thanks for the discussion!
