### ISSUE TITLE
"Measure Twice, Run Once" unclear, and duplicate of 'Doing a dry run'

### ISSUE THREAD

**Issue by plijnzaad** [swcarpentry/shell-novice#353]
While preparing my instructor exam :-) it struck me that the callout 'Measure Twice, Run once' has, first of all, a (to me at least) incomprehensible header (what is being measured? and why twice?). Secondly, the 'echo' trick to do a dry-run is also treated in the 'doing a dry-run' exercise further down. If people agree I will write code to merge these things into one dryrun exercise to replace the measuretwice callout. Also cuts down on the size of this lesson :-)

**Comment by wking** [comment]
On Mon, Mar 14, 2016 at 03:10:52PM -0700, Philip Lijnzaad wrote:
> While preparing my instructor exam :-) it struck me that the callout
> 'Measure Twice, Run once' has, first of all, a (to me at least)
> incomprehensible header (what is being measured? and why twice?).

Looks like that phrasing landed in 8e77786c (Importing shell lesson
for novices, 2013-11-11), so I expect motivation for the phrasing is
lost in the mists of time.  Seems like a play on [1] and our
carpentry-ness, but proverb references are a tricky balance as the
lesson audience becomes more global.  And in case it helps, the thing
being measured is your code, and twice could be “as you write it” and
“during a dry run”.  But it's probably more figurative and just means
“make sure you want to do what you're about to do before you do it”
;).

[1]: https://en.wiktionary.org/wiki/measure_twice_and_cut_once

**Comment by gdevenyi** [comment]
PRs welcome!

**Comment by gdevenyi** [comment]
Claimed by @ttimbers

**Comment by ttimbers** [comment]
pull request to address this: https://github.com/swcarpentry/shell-novice/pull/393
