### ISSUE TITLE
Strange rendering of 04-loop

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/shell-novice#377]
When working on the release process, I saw a bash code block that is not well converted by pandoc.

Starting from her home directory, Nelle types: ~ {.bash} $ cd north-pacific-gyre/2012-07-03 $ for datafile in *[AB].txt > do > echo $datafile > done {.output} NENE01729A.txt NENE01729B.txt NENE01736A.txt … NENE02043A.txt NENE02043B.txt ~

(I saw it after building the alpha release with the latest 1.17.0.2 pandoc
http://swcarpentry.github.io/swc-releases/2016.06-alpha/shell-novice/04-loop.html
)

**Comment by shwina** [comment]
Fixed this in `gh-pages`. Missing line between paragraph and code block.

**Comment by twitwi** [comment]
Great. I'm closing then.
