### ISSUE TITLE
reformat the .md formats to use 80 characters per line

### ISSUE THREAD

**Issue by btel** [swcarpentry/shell-novice#389]
Many lines in the `.md` source files are different character lengths. Make them uniformly formatted.

**Comment by gdevenyi** [comment]
Sounds like a reasonable idea, let's wait on this until after the BBQ completes.

@gvwilson should this go into the new validator?

**Comment by gdevenyi** [comment]
Checked globally in https://github.com/swcarpentry/styles/blob/2016-06/bin/lesson_check.py for transition to Jekyll.

I expect we will have several cleanups to do so that our markdown validates.

**Comment by btel** [comment]
@gdevenyi I could not find the code checking the line lengths in https://github.com/swcarpentry/styles/blob/2016-06/bin/lesson_check.py. Could you specify the line number? Thanks.

**Comment by shwina** [comment]
Although not official, I've noticed a tendency to use [semantic linefeeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/). So, not necessarily ~80 characters per line.

**Comment by TomKellyGenetics** [comment]
+1 @shwina I tend to use a new line to add sentences to reduce conflicts.

**Comment by gdevenyi** [comment]
@btel https://github.com/swcarpentry/styles/blob/2016-06/bin/lesson_check.py#L303-L311

**Comment by btel** [comment]
Thanks, @gdevenyi! I noticed that the maximum length is 100 characters. It's quite a lot. Also the script does not check for short lines (which might be hard to do automatically), which was the main problem with the lesson.

 I agree that something like [semantic linefeeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) might be a better style than using fixed number of characters per line. In any case we should adapt one convention and stick to it.

**Comment by shwina** [comment]
I imagine it's difficult to enforce semantic linefeeds in an automated way though. The most we can do is include it as a part of guidelines for contributing.

**Comment by gdevenyi** [comment]
Something for the global contribution guide, wherever that is?
