### ISSUE TITLE
Loops: potential pitfall with "measure twice, run once" section

### ISSUE THREAD

**Issue by standage** [swcarpentry/shell-novice#39]
I use the approach described in this section quite frequently. One pitfall I occasionally run into is forgetting to quote the command when it includes a file redirect. What if our example was this.

```bash
for filename in *.dat
do
    someCommand $filename >> outfile
done
```

If we simply add `echo` to the beginning of the looped command, we could easily corrupt our data file.

There are a couple of potential ways we could address this.
- Add a brief parenthetical right after "*This isn't foolproof...*" citing this as an example of a case where the described approach could be problematic.
- Add an additional example in that section demonstrating why and how to handle this type of case.
- Add an additional challenge, one loop having ``echo someCommand $filename >> outfile`` and the other having ``echo "someCommand $filename >> outfile"`` and ask what the difference in outcome would be.

On one hand we don't want to set the students up to fail, but on the other hand we don't want to overload them with details. Any suggestions?

**Comment by r-gaia-cs** [comment]
@standage Thanks for the feedback. I'm closing this since your pull request was merged.
