### ISSUE TITLE
Add a photo of line printer in the introduction

### ISSUE THREAD

**Issue by btel** [swcarpentry/shell-novice#390]
In the introduction we say:

> But in between,
> from the 1950s to the 1980s,
> most people used line printers.
> These devices only allowed input and output of the letters, numbers, and punctuation found on a standard keyboard,
> so programming languages and interfaces had to be designed around that constraint.

Would it be useful to add a photo, so people can understand better what line printers were? For example: https://upload.wikimedia.org/wikipedia/commons/d/df/ASR-33_at_CHM.agr.jpg

**Comment by cjantonelli** [comment]
That is a beautiful picture of a Model 33 Teletype.  But a line printer looked like this 
https://upload.wikimedia.org/wikipedia/commons/9/93/PrinterIBM1403_090325.jpg .

**Comment by btel** [comment]
Nice! Should we add it then?

**Comment by wking** [comment]
I expect the introduction meant “teletype”.  Folks seem unlikely to
use line printers for input ;).

**Comment by Mahdisadjadi** [comment]
I really enjoyed seeing a line printer but I think this does not add to the lesson mainly because I do not how they work!

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 11:20:28AM -0700, Bartosz Telenczuk wrote:
> For example:
> https://upload.wikimedia.org/wikipedia/commons/d/df/ASR-33_at_CHM.agr.jpg

You can't use this image in a core SWC lesson, because it's CC BY-SA
3.0 Unported [1], and SWC lesson content cannot have the SA (Share
Alike) restriction [2].

[1]: https://en.wikipedia.org/wiki/File:ASR-33_at_CHM.agr.jpg
[2]: http://software-carpentry.org/license/

**Comment by btel** [comment]
@wking Good point! How about this [one](https://commons.wikimedia.org/wiki/Category:ASR-33#/media/File:ASR-33_2.jpg). Its CC BY 2.0 - we can add the attribution in the caption.

@Mahdisadjadi I have never used one, but I imagine it's like telnet, but instead of screen you have a typewriter ;). We can also add a link to wikipedia article in the [caption](https://en.wikipedia.org/wiki/Teleprinter)

**Comment by Mahdisadjadi** [comment]
+1 for adding the link to Wikipedia!

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 02:43:57PM -0700, Bartosz Telenczuk wrote:
> @wking Good point! How about this
> [one](https://commons.wikimedia.org/wiki/Category:ASR-33#/media/File:ASR-33_2.jpg). Its
> CC BY 2.0 - we can add the attribution in the caption.

That sounds better.  I'm not sure about mixing CC BY versions (2.0
vs. 4.0).  The GPL suggests explit “or later” language for that sort
of thing, but the closest I can find in CC-land is BY-SA's §1.c (which
lists compatible licenses [1,2]).  The CC FAQ has [3], and I expect we
could include the image with a caveat in LICENSE.md about the image
being CC BY 2.0, but I'm doubtful that we can unilaterally promote the
license to version 4.0.

[1]: https://creativecommons.org/licenses/by-sa/4.0/legalcode
[2]: https://creativecommons.org/compatiblelicenses/
[3]: https://creativecommons.org/faq/#can-i-combine-material-under-different-creative-commons-licenses-in-my-work

**Comment by btel** [comment]
Alternatively, we can try to contact the author and ask him to re-license with CC BY 4.0

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 04:23:00PM -0700, Bartosz Telenczuk wrote:
> Alternatively, we can try to contact the author and ask him to
> re-license with CC BY 4.0

If you're that motivated, that would be great.  I'd make sure the
maintainers are interested in including the picture before going
through that much work though ;).

**Comment by btel** [comment]
Thanks. I already sent a message to the author.

 I'd love to hear from the maintainers what they think. Personally, I like using such a photo at a workshop to explain the history of command line. I find it very illustrative.

**Comment by willpitchers** [comment]
A similar image exists [here](https://www.flickr.com/photos/15587432@N02/4669611994) and seems to be under CC BY 2.0... would that help?

**Comment by deppen8** [comment]
This text that sparked this conversation is no longer in the lesson. Closing as part of old issue cleanup.
