### ISSUE TITLE
Add this image (if we can find the original)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#402]
https://twitter.com/49SD/status/744189404030316544

**Comment by ppgardne** [comment]
I've knocked the attached together (fixed some issues with case, some spelling, descriptions, etc.). 
[standard-filesystem-hierarchy.pdf](https://github.com/swcarpentry/shell-novice/files/322515/standard-filesystem-hierarchy.pdf)
Github wont let me upload the SVG (:-/) -- but the pdf should give you an idea. Where would you like to include it (if at all)? Comments/edits welcome.

**Comment by ppgardne** [comment]
Fixed some of the issues I introduced:
[standard-filesystem-hierarchy.pdf](https://github.com/swcarpentry/shell-novice/files/322516/standard-filesystem-hierarchy.pdf)
