### ISSUE TITLE
Add a dotfile to the image related to ls -F -a command

### ISSUE THREAD

**Issue by willingc** [swcarpentry/shell-novice#41]
dotfiles are a concept that trip up new users of the command line and shells. In file `01-filedir.md`, the description of the `..` directory is great. Although `.` is mentioned related to files, it would be helpful to learners to see a dotfile in the output image or to have a sentence explaining dotfiles for configuration information.

![screen shot 2015-01-16 at 11 57 18](https://cloud.githubusercontent.com/assets/2680980/5783380/3f1df878-9d77-11e4-8064-aa990d48e05d.png)

**Comment by lexnederbragt** [comment]
Hmmm... It is not straightforward to come up with a dotfile that is relatively easy to explain. The file should be there in the actual folder when they clone/download the repo. I was thinking a .bashrc file with just one command, but it should then be one that doesn't trip the student. Even a simple thing as an alias (alias la='ls -la') would require a few lines to explain. Is there a type of dotfile that makes sense, but has no content, or one that can be easily understandable?

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 06:52:35AM -0800, Lex Nederbragt wrote:
> The file should be there in the actual folder when they
> clone/download the repo.

.gitignore?

**Comment by lexnederbragt** [comment]
On 2 Feb 2015, at 18:13, W. Trevor King wrote:

> On Mon, Feb 02, 2015 at 06:52:35AM -0800, Lex Nederbragt wrote:
> > The file should be there in the actual folder when they
> > clone/download the repo.
> 
> .gitignore?

Maybe. It would mean adding a .git folder as well, with the burden of having to explain these - and why would the entire 'nelle' folder be under version control…

	Lex

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 01:59:03AM -0800, Lex Nederbragt wrote:
> Maybe. It would mean adding a .git folder as well, with the burden
> of having to explain these - and why would the entire 'nelle' folder
> be under version control…

I'd have the students getting the example files via a Git repository
(either via a ‘git clone …’ or via an archive zip [1]).  That's going
to come with a .gitignore (and .nojekyll) out of the box.  The clone
will also come with a .git.  The shell lesson usually lands before the
Git lesson, so I'd just say something like:

  The .gitignore file has a leading dot to mark it as a hidden file
  (or directory).  Dotfiles are just like a regular files, except that
  `ls` doesn't list them by default and the shell doesn't use them
  when expanding wildcard globs like `*` (although it will *only* use
  dotfiles when expanding `.*`).  Programs generally use dotfiles for
  configuration and other things that the user only needs to interact
  with occasionally; that way they're not cluttering up your working
  directory the rest of the time.

  Git is a version-control program, which means it tracks how your
  files change over time.  We'll learn more about it later, but as an
  example dotfile, we can peek inside the .gitignore file:

    $ cat .gitignore
		*~
		*.pyc

  That's telling Git that we don't want it to track files ending with
  `~` (editors save files like this) or `.pyc` (Python caches files
  like this).

  There are likely lots of other dotfiles on your system (for example,
  try `ls -d ~/.*`), so feel free to poke around and see the sort of
  thing they're used for.

[1]: https://github.com/swcarpentry/shell-novice/archive/gh-pages.zip

**Comment by gvwilson** [comment]
-1 to making the shell lesson depend on use of Git - too many real-world 
failure modes.

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 10:32:55AM -0800, Greg Wilson wrote:
> -1 to making the shell lesson depend on use of Git - too many
> real-world failure modes.

I'm not suggesting a Git dependency, I'm suggesting optional use of
Git with a zip-download fallback [1].  Students will need to get the
example files somehow, and “try Git, but fall back to a zip download
of the same content (without the history)” seems like a pretty safe
bet to me.

[1]: https://github.com/swcarpentry/shell-novice/issues/41#issuecomment-72702114

**Comment by ChristinaLK** [comment]
I like @lexnederbragt 's idea of a `.bashrc` or `.bash_profile` as a sample dotfile.  It doesn't need to be functional - it could live in the `nelle` user directory - and then people would have something to compare to their own `.bash_profile` in their home directory.  

semi-related question: do we have a convention for how students get the data files for this lesson?  (may be relevant to #62). clone this lesson repo? clone something else? zip download?

**Comment by lexnederbragt** [comment]
PR submitted, #63

**Comment by willingc** [comment]
@lexnederbragt Thanks for the PR. I like the changes using .bash_profile. I did leave a comment on the PR suggesting a clarification on dotfiles and the -a option for ls.
