### ISSUE TITLE
Check/remove unexpected images

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#423]
`make lesson-check` reports:

Unexpected image files: filesystem-challenge.png, filesystem.png, find-file-tree.png, home-directories.png, homedir.svg, redirects-and-pipes.svg, vlad-homedir.png

**Comment by williamssanders** [comment]
The files are all located in: `shell-novice/fig/`

The following have no output:
* `grep filesystem-challenge.png *.md`
* `grep filesystem.png *.md`
* `grep find-file-tree.png *.md`
* `grep home-directories.png *.md`
* `grep homedir.svg *.md`
* `grep redirects-and-pipes.svg *.md`
* `grep vlad-homedir.png *.md`

So the files aren't mentioned or used in the lessons.

Submitted Pull Request #429.

**Comment by shwina** [comment]
Closing as #429 is merged.
