### ISSUE TITLE
Add table w/ commands for working with files and folders

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/shell-novice#425]
The last time I taught the shell, I wrote the table below on the blackboard. When helping learners that got stuck, when I said 'do you remember the command for ...', I could then point to the table, which helped them a lot. If instructors find it useful, it could be added to the lesson or the instructor notes.

|Action      |Files|Folders     |
|------------|-----|------------|
|Inspect     |ls   |ls          |
|View content|cat  |ls          |
|Navigate to |cd   |cd          |
|Move        |mv   |mv          |
|Copy        |cp   |cp -r       |
|Create      |nano |mkdir       |
|Delete      |rm   |rmdir, rm- r|

**Comment by shwina** [comment]
+1. I think `reference.md` would be the best place for this.
