### ISSUE TITLE
Add diagrams showing how pipes work

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#435]
See https://github.com/swcarpentry/bc/issues/817 for original material.

**Comment by crocha700** [comment]
I'm picking this up.

**Comment by ChristinaLK** [comment]
Doesn't this already exist? 
http://swcarpentry.github.io/shell-novice/04-pipefilter/

**Comment by shwina** [comment]
Yes, I think this issue could be closed. @crocha700, any objections?

**Comment by crocha700** [comment]
No objections.
