### ISSUE TITLE
Suggestion for the lesson: Navigating Files and Directories

### ISSUE THREAD

**Issue by thanyta** [swcarpentry/shell-novice#436]
Suggestion for the lesson: Navigating Files and Directories
In a recent workshop, instructors asked learners to open the shell and adjust the window to fit half of their screen. Then we asked to open their files explorer (in windows or the corresponding in mac) and fit the window to the other half of the screen. See picture attached.

In this way, learners could navigate files using the shell, and simultaneously see the corresponding location in the GUI. They could also type ls and see the contents of directories both in the shell and in the GUI.

We received excellent feedback with this exercise.

![shell_and_explorer_windows](https://cloud.githubusercontent.com/assets/14966526/17343407/588a4350-58b2-11e6-9b3f-d6935dc651f5.png)

**Comment by gdevenyi** [comment]
Hi,

Thanks for the suggestions.

PRs are welcome for the instructor's guide to recommend this.

**Comment by nknadmin** [comment]
I wonder if it would be beneficial and help with understanding various commands to include the Explainshell tool as a resource (http://explainshell.com/) at the end of the lesson.   [This idea may apply to other lessons as well].  Of course, suggesting third party tools may not be proper in these SCW lessons.

**Comment by Mahdisadjadi** [comment]
I'll be happy to work on this!

**Comment by cjieming** [comment]
Hi I am new here. Trying to complete the instructor checkout. Is this still open or is it closed?

**Comment by Mahdisadjadi** [comment]
Welcome, @cjieming! I think this can be closed, PR is already merged!

**Comment by cjieming** [comment]
Ok, because the "help-wanted" tag is still on, so it's quite confusing too. But thanks for the prompt reply!

**Comment by Mahdisadjadi** [comment]
You're right, it's confusing! 
@gdevenyi, could you please close this issue? Thanks!
