### ISSUE TITLE
Add a reference to sourcecaster

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/shell-novice#438]
https://datapraxis.github.io/sourcecaster/

**Comment by nknadmin** [comment]
Also see Thomas Padilla's blog regarding the origins of the Sourcecaster

http://www.thomaspadilla.org/2016/06/24/sourcecaster/

**Comment by deppen8** [comment]
Not sure where this would fit in to the lesson as it exists today. Closing as part of old issue cleanup.
