### ISSUE TITLE
Do we create a Nelle user?

### ISSUE THREAD

**Issue by reedacartwright** [swcarpentry/shell-novice#44]
From reading the lesson plan and the instructor notes, I am uncertain whether i need to create a Nelle user on my linux laptop for the lesson and import her filesystem.  What is the recommended way to prepare my machine for teaching about the filesystem, etc.

**Comment by jiffyclub** [comment]
We keep a facsimile of Nelle's filesystem in the repo at https://github.com/swcarpentry/shell-novice/tree/gh-pages/filesystem/users/nelle. If students are cloning our workshop repo they will likely have this, but you can also zip up that directory and provide it via Dropbox or something.

**Comment by reedacartwright** [comment]
Do you usually chroot into it so it shows the right paths with live coding?

**Comment by gvwilson** [comment]
I usually don't bother, but it's never been a particular problem. (I 
also often use the names of the actual directories I'm in, since they're 
watching me type rather than looking at these notes.)

**Comment by jiffyclub** [comment]
No, nothing fancy. In the class students aren't reading the lesson, so the fact that paths don't match between your computer and the written lessons won't matter.

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 11:40:56AM -0800, Matt Davis wrote:
> We keep a facsimile of Nelle's filesystem in the repo at
> https://github.com/swcarpentry/shell-novice/tree/gh-pages/filesystem/users/nelle. If
> students are cloning our workshop repo they will likely have this,
> but you can also zip up that directory and provide it via Dropbox or
> something.

You can also have them use an archive link [1].  I'm still favor of
splitting lesson and workshop content out into “for the website” and
“for students to download” branches, but until we do that I don't have
a problem with students getting a zipped up version of the whole “for
both website and student-downloads” branch.

[1]: https://github.com/swcarpentry/shell-novice/archive/gh-pages.zip

**Comment by gdevenyi** [comment]
Closing since the question has been answered, no, we don't create Nelle.
