### ISSUE TITLE
05: Further explanation of `sort`

### ISSUE THREAD

**Issue by mjones01** [swcarpentry/shell-novice#445]
Currently in 05 `sort`  and `sort -n` is introduced, however, on this dataset (downloaded from website link on 31 Aug 2016) both work the same, might want to consider explanation for this.

**Comment by iglpdc** [comment]
Yep, I agree. By default, if you are ordering according to a numeric value you should always use `sort -n`. In this case, it doesn't matter because the numbers are properly prepended with some whitespace makes `sort` work as `sort -n`. But, I agree it's confusing...

**Comment by gdevenyi** [comment]
Hi, on this dataset, ``sort`` and ``sort -n`` do not produce the same results,

from https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/04-pipefilter.md:
```
> cat lengths.txt
  20  cubane.pdb
  12  ethane.pdb
   9  methane.pdb
  30  octane.pdb
  21  pentane.pdb
  15  propane.pdb
 107  total
> sort lengths.txt
 107  total
  12  ethane.pdb
  15  propane.pdb
  20  cubane.pdb
  21  pentane.pdb
  30  octane.pdb
   9  methane.pdb
> sort -n lengths.txt
   9  methane.pdb
  12  ethane.pdb
  15  propane.pdb
  20  cubane.pdb
  21  pentane.pdb
  30  octane.pdb
 107  total
```

This is on linux with GNU coreutils' version of sort.

Are you using another system?

**Comment by iglpdc** [comment]
They produce the same result in the Macs (and maybe in Windows).

**Comment by shwina** [comment]
Can confirm that both commands produce the same result on Macs. Macs don't use GNU sort by default. Maybe we should just recommend using the `-n` switch to sort numerically if it doesn't work without it (perhaps in a callout?).

**Comment by aliceminotto** [comment]
Wouldn't it be good to add a note or a comment in the lesson? Last time we had about 1/3 of the people with a red post it to ask why they were getting a different output than the instructor. I realized the pattern mac/linux users after checking on a couple of people. I guess since the instructor likely works on a specific OS s/he may no notice this before the actual carpentry.

**Comment by deppen8** [comment]
Both `sort` and `sort -n` still produce the same result on MacOS. `sort` is part of [Episode 4: Pipes and Filters](http://swcarpentry.github.io/shell-novice/04-pipefilter/index.html).

Perhaps someone would like to add a note or callout?
