### ISSUE TITLE
Flip vertical file system diagram

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#450]
On September 20th Instructor Discussion was proposed, by Dmitri Rozmanov, to flip vertical the file system diagram. For example, instead of

![tree](https://cloud.githubusercontent.com/assets/1506457/18711564/80581926-8002-11e6-9dfa-215d681b4a78.png)

use

![tree2](https://cloud.githubusercontent.com/assets/1506457/18711572/87442bb2-8002-11e6-9839-979fe91c1300.png)

The reason for the suggestion is that the general sense says that the root is the lowest part of the tree. I agree that make this change will help non-computer science learners better get the root idea.

**Comment by iglpdc** [comment]
I disagree, but mildly. We read from top to bottom, so I feel the current option more natural with the start (root) on top. It's also common notation in CS and similar structures like family trees are often depicted this way. We tend to associate parent-child relationships with descending: my parents are my ascendants and my children my descendants. We also say often that `..` moves us "up" in the filesystem and that we have the directories `larry` and `nelle` "under" `users`. 

In any case, I think it's a close call and either way is fine. Maybe the proposed change could be more intuitive for some people, but then we should be careful with all the wording attached to the old way.

**Comment by shwina** [comment]
I agree with all of @iglpdc's points. I think we will make things more difficult for novices by flipping the figure, and we will also surprise/confuse those who may have seen similar diagrams before.

**Comment by gdevenyi** [comment]
+1 for not breaking people's reading tendencies. It should probably stay as is.
