### ISSUE TITLE
No link to file system used on the lesson

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#453]
http://swcarpentry.github.io/shell-novice/02-filedir/ has

> including the data-shell directory you downloaded at the start of the lesson.

but there is not instruction for how to download that file. Before the new template we had some instructions. Can we return it?

**Comment by iglpdc** [comment]
It's now under the "Setup" pane, in the main header of the page. It took me a while to find the the first time, but makes sense to have a "Setup" in the lesson template.

Maybe we can make a link from this sentence to "Setup".

**Comment by rgaiacs** [comment]
> It's now under the "Setup" pane, in the main header of the page.

Thanks.

> It took me a while to find the the first time, but makes sense to have a "Setup" in the lesson template.
>
> Maybe we can make a link from this sentence to "Setup".

I opened https://github.com/swcarpentry/lesson-example/issues/66 and will close this since is a issue across all lessons.
