### ISSUE TITLE
New call out box: Don't over-write a file in-place

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#456]
Later in Python, R or MATLAB we will say to the students that they can create a variable with

~~~
x = 1
~~~

and they can increase the variable in one unit with

~~~
x = x + 1
~~~

Students can extend this model to bash and thing they can use

~~~
$ sort -n lengths.txt > lengths.txt
$ head -n 1 lengths.txt
~~~

instead of

~~~
$ sort -n lengths.txt > sorted-lengths.txt
$ head -n 1 sorted-lengths.txt
~~~

that is one of the examples in http://swcarpentry.github.io/shell-novice/04-pipefilter/. Unfortunately they can't do that (as explained at http://stackoverflow.com/questions/10586623/why-piping-to-the-same-file-doesnt-work-on-some-platforms). I want to suggest add a call out box after the example warning learners about this.

**Comment by shwina** [comment]
Great point. Opened PR
