### ISSUE TITLE
Flags in ls command

### ISSUE THREAD

**Issue by crocha700** [swcarpentry/shell-novice#464]
Currently we teach the use of two or more flags of  `ls` as separate inputs, e.g., 

``` bash
ls -F -l -t
```

But equally valid –– and convenient –– is to patch the flags

```
ls -Fht
```

Is the first form preferred on pedagogical grounds? Would it be useful to teach the second form? Perhaps using a "pin box"?

**Comment by rgaiacs** [comment]
> Is the first form preferred on pedagogical grounds?

Yes. For a novice it makes things easy to read.

> Would it be useful to teach the second form? Perhaps using a "pin box"?

I'm -1 to add it to the novice lesson since beginners are already presented with a lot of new information.

**Comment by shwina** [comment]
Agreed. Something needs to go out if we're going to add in new information.

**Comment by iglpdc** [comment]
This (patching the flags) used to be in the lesson. I think it is useful to have: it's standard practice, saves a lot of time when typing, and instructors may accidentally use it during the lesson or solo-learners will find it in the web.

When I teach the lesson I just say that, say, `ls -F -l -t` is equivalent to `ls -Flt` and enter the second comment after the first, so people can actually see it's really the same.

I would add a really short sentence to the lesson just saying this.

**Comment by gdevenyi** [comment]
I'm okay only with a small callout if anything for improving this. It's advanced usage, and makes the lesson longer.

**Comment by shwina** [comment]
PRs welcome on this

**Comment by jarekbryk** [comment]
I think this can be closed given that my PR #496 was merged a while ago.
