### ISSUE TITLE
Markdown not parsed properly

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#465]
On https://github.com/swcarpentry/shell-novice/blob/gh-pages/_extras/guide.md we have

![screenshot_2016-10-12_14-46-22](https://cloud.githubusercontent.com/assets/1506457/19312542/c47c8acc-908a-11e6-9095-f6acf79557f9.png)

The `{: .bash}` should be parsed in a different form. The Markdown looks good to me.

```

*   On Windows, it appears that:

    ~~~
    $ cd
    $ cd Desktop
    ~~~
    {: .bash}

    will always put someone on their desktop.
    Have them create the example directory for the shell exercises there
    so that they can find it easily
    and watch it evolve.
```

**Comment by cjieming** [comment]
Hi, I think this is not 'bug' as this only appears on the Github page - this appears in most other pages too if you create a code block. Once it's rendered, it goes away: [https://swcarpentry.github.io/shell-novice/guide/](https://swcarpentry.github.io/shell-novice/guide/). So I think this can be closed @rgaiacs ! =)
