### ISSUE TITLE
Missing files motivation.md and discussion.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/shell-novice#47]
From [check.py](https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py):

- [ ] In /tmp/shell/index.md: The document links to motivation.html, but could not find the expected markdown file /tmp/shell/motivation.md
- [x] In /tmp/shell/index.md: The document links to discussion.html, but could not find the expected markdown file /tmp/shell/discussion.md

**Comment by ChristinaLK** [comment]
need for `motivation.md` opened again in #100, closing this issue.
