### ISSUE TITLE
Missing heading in instructors.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/shell-novice#48]
From [check.py](https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py):

- [x] In /tmp/shell/instructors.md: Document is missing expected heading: Legend
- [x] In /tmp/shell/instructors.md: Document is missing expected heading: Overall

**Comment by iglpdc** [comment]
I'm closing this by #60.
