### ISSUE TITLE
Data download link in "pre-requisites"? 

### ISSUE THREAD

**Issue by arokem** [swcarpentry/shell-novice#486]
Would it be useful if the participants download the data in advance?

**Comment by shwina** [comment]
In practice, not many are likely to do this. Workshops that would like learners to do this in advance can always link them to the setup page in advance and request that they follow the steps there.

**Comment by dlstrong** [comment]
There's a step in the "02 Filedir" lesson that says "Your output should be a list of all the files and sub-directories on your Desktop, **including the data-shell directory you downloaded at the start of the lesson**. Take a look at your Desktop to confirm that your output is accurate." This won't work as written unless we've already taken them through downloading and extracting the information into that directory.

As far as I can tell, there isn't a "download this batch of stuff and extract it here" step in either 01 Intro or 02 Filedir before that "here's how it will look" section shows up - or if there was one in a past edition, it doesn't appear to be available in what's live right now?

**Comment by GregoryRHart** [comment]
On the [schedule page](http://swcarpentry.github.io/shell-novice/) for the module there is on a link to setup, which has the download instructions.

**Comment by deppen8** [comment]
This is covered in the [Setup](http://swcarpentry.github.io/shell-novice/setup.html) instructions nowadays. Closing as part of old issue cleanup.
