### ISSUE TITLE
Desktop directory in data-shell

### ISSUE THREAD

**Issue by ateucher** [swcarpentry/shell-novice#487]
I'm just getting ready to teach next week, and I see there is a `Desktop` directory in the `data-shell` directory that learners download. Is there a reason for that? It seems like it could be confusing

**Comment by shwina** [comment]
I don't know if any instructors have used this to their advantage (i.e., demonstrating that the two `Destop` directories have different absolute paths, and are distinct directories, etc.,)

I'm all in favour of getting rid of it otherwise.

**Comment by rgaiacs** [comment]
> > I see there is a Desktop directory in the data-shell directory that learners download. Is there a reason for that? It seems like it could be confusing

`data-shell` try to replicate the file system that learners will find in any Unix-like machine with `/`, `/bin`, `/home`, ... 

> I'm all in favour of getting rid of it otherwise.

I would like to keep it.

**Comment by shwina** [comment]
@rgaiacs, I am a little confused: `data-shell` has none of this other than `Desktop`. 

└── data-shell
    ├── Desktop
    ├── creatures
    ├── data
    ├── molecules
    ├── north-pacific-gyre
    ├── notes.txt
    ├── pizza.cfg
    ├── solar.pdf
    └── writing

**Comment by ateucher** [comment]
I think it's the filesystem directory that mimics the contents of /.  In that directory there is Users/nelle and Users/Larry both of which contain Desktop folders

**Comment by shwina** [comment]
Ah, I understand now. In any case, I think that `data-shell/Desktop` can be removed. `filesystem/Users/Larry/Desktop` and `/filesystem/Users/nelle/Desktop` may be retained, depending on the discussion in #490.

**Comment by rgaiacs** [comment]
> I think it's the filesystem directory that mimics the contents of /. In that directory there is Users/nelle and Users/Larry both of which contain Desktop folders

@ateucher You are right.

@shwina Sorry to not be clear. `data-shell` was created as a copy of `filesystem/Users/nelle` as you can check at [data-shell](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data-shell) and [filesystem/Users/nelle](https://github.com/swcarpentry/shell-novice/tree/gh-pages/filesystem/Users/nelle).

> I'm just getting ready to teach next week, and I see there is a Desktop directory in the data-shell directory that learners download. It seems like it could be confusing

@shwina I agree with you that is a bit confusing but I prefer that we back to work to resolve  https://github.com/swcarpentry/shell-novice/issues/371 (duplicated at https://github.com/swcarpentry/shell-novice/issues/490).

**Comment by ateucher** [comment]
Sounds good closing in favour of #371.
