### ISSUE TITLE
filesystem vs data vs data-shell

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#490]
Can we have only one? [filesystem](https://github.com/swcarpentry/shell-novice/tree/gh-pages/filesystem)
[data](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data) and [data-shell](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data-shell).

**Comment by shwina** [comment]
Yes. Based on the setup instructions (http://swcarpentry.github.io/shell-novice/setup/), [data](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data) is the one to keep. Would you agree @rgaiacs?

**Comment by ateucher** [comment]
I think (though am not certain) that the zipfile in data/ contains the files in data-shell for download

**Comment by shwina** [comment]
This means that we have two versions of the same files that may be out of sync at any time?

**Comment by ateucher** [comment]
I think so. Also, this isn't the first open issue on this (See #371). We should coalesce around one.

**Comment by rgaiacs** [comment]
> This means that we have two versions of the same files that may be out of sync at any time?

Short answer, **yes**. Long answer, we almost never change the data used on the lesson so the files will not be out of sync very often but it can happen.

I'm closing this issue to keep the conversation on #371.
