### ISSUE TITLE
Unix Shell "Bash Configurations"  link

### ISSUE THREAD

**Issue by okFlatLander** [swcarpentry/shell-novice#498]
I was looking through the unix shell lesson and noticed on the "Discussion" page, that the link given for “Bash Configurations Demystified” is no longer working.   I discovered it because I was thinking some discussion of the "env" command may be useful to the students somewhere in the lesson.    Initially I was thinking at the end of the last episode.

**Comment by marwahaha** [comment]
Is this it? http://dghubble.com/blog/posts/.bashprofile-.profile-and-.bashrc-conventions/
