### ISSUE TITLE
Time allocated for exercises is 0

### ISSUE THREAD

**Issue by jarrah42** [swcarpentry/shell-novice#501]
In all the episodes in this lesson, the time allocated for exercises is 0, even though some of the episodes have challenges. Is this by design, or for some other reason?

**Comment by marwahaha** [comment]
Yea, I'm in agreement here. I feel like we should bump out the time of this lesson to around 2.5 or maybe 3 hours, to account for the challenges.

**Comment by gdevenyi** [comment]
I think we will need some feedback from people who have taught the lesson recently to update the timings. Thanks!

**Comment by marwahaha** [comment]
I've taught this lesson 4-5 times this calendar year, and each time, it takes nearly 3 hours.

**Comment by gdevenyi** [comment]
Thanks @marwahaha that's helpful information, but we need to specify exercise time use on each episode and the final time is calculated from those.

Do you have any feedback on the exercise time use for each episode?

**Comment by ChristinaLK** [comment]
I'd like to bump this again -- the timing for this lesson is still off (as far as I know) -- all the lesson pieces should take 3+ hours.

**Comment by ErinBecker** [comment]
@gdevenyi - I've also taught this lesson this year and the timings are significant underestimates, as no time for exercises are included. In instructor training, we recommend half a day for this lesson and half a day for git, meaning each is about 3-3.5 hours (after allowing for coffee breaks and lunch). I recommend that we add time estimates to each episode that split this time addition equally among them (except for the first episode which has no exercises). Even though this will be inaccurate, it will be a vast improvement to the current time estimates. I will put in a PR.
