### ISSUE TITLE
Misleading diagram in 05-loop.md

### ISSUE THREAD

**Issue by jarrah42** [swcarpentry/shell-novice#502]
The diagram on line 251 of _episodes/05-loop.md describes what happens when the loop body is "echo cp $filename original-$filename". However, the commands shown in the text before and after the diagram does not use the "echo" command, but use "cp" directly. It's confusing for the student because the diagram doesn't match the text.

**Comment by shwina** [comment]
Thanks @jarrah42. PRs welcome on this one.

**Comment by deppen8** [comment]
Looks like this was closed by #506
