### ISSUE TITLE
07-find: suggestion for grep -w

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [swcarpentry/shell-novice#510]
In order to better demonstrate the use of grep's -w flag, I'd like to 
suggest that, instead of using the word "day", for which `grep -w`
doesn't actually show anything, you could compare and contrast 
the '-w' invocation using  "The", as follows:

```
$ grep The haiku.txt 
The Tao that is seen
"My Thesis" not found.
$
```
where the bare invocation then matches across "word boundaries" 
```
$ grep -w The haiku.txt 
The Tao that is seen
$
```
whilst the second invocation filters out the "The" in "Thesis".

**Comment by shwina** [comment]
Great suggestion. PR welcome.

**Comment by vuw-ecs-kevin** [comment]
Before I create that PR, I should add that I have now seen that in the "challenges", 
there's one that uses the string "of" to highlight the same behaviour as I suggest 
be in the lesson itself, vis:

the right answer
```
$ grep -w "of" haiku.txt
and the presence of absence:
```
and one of the wrong answers
```
$ grep "of" haiku.txt
and the presence of absence:
Software is like that.
```
however, I'd suggest that having an example in the lesson that has some output
in BOTH invocations, and so being able to point to the "The", as opposed trying to 
explain word boundaries in terms of there being nothing in the second invocation, 
might make the "word boundaries" concept a little easier to grasp/explain.

In which case, the grep-ing for "day" might then need to move (be swapped) into
the exercises, as a further illustration of "word boundaries".

Then again, maybe the choice of "day" in the existing episode,  was made for
a specific reason - so as to have the students think about (go off and read up on)
"word boundaries" ?

**Comment by shwina** [comment]
I'm not sure what the original intention was, although I like the idea of having a better explanation in the lesson material itself - not all instructors will work through all exercises.

**Comment by shwina** [comment]
Closing after #511 merge

**Comment by vuw-ecs-kevin** [comment]
Just realised that there's one more small grammatical change required
```
-we can give `grep` with the `-w` flag.
+we can invoke `grep` with the `-w` flag.
```
It's on the top of the branch you pulled from.
