### ISSUE TITLE
The Unix Shell: Summary of Basic Commands: Change “path” to “directoryname”, and Spelling error.

### ISSUE THREAD

**Issue by Claudia-Lange** [swcarpentry/shell-novice#513]
Some descriptions under “Navigating Files and Directories” and “Working with Files and Directories” are confusing. For explaining cd, ls, mkdir and rm it might be better to use “directoryname” or “filename” instead of “path”. A note can be made to say that the current working directory can be replaced by a “path” to a different directory or file.
Change “heirarchy” to “hierarchy”.

**Comment by jttkim** [comment]
I'm not sure about this -- "path" and "directory name" are not synonyms. As an example, `../nelle/data` is a path comprised of the directory names `..`, `nelle` and `data`. So "path" and "directory name" coincide only when using simple relative paths to a direct subdirectory of the current working directory.

Perhaps it's worthwhile explaining this, e.g. in a callout box?

**Comment by Claudia-Lange** [comment]
Yes, you are correct that they are not synonyms. However, in the lesson, we are mainly using simple relative paths to a direct subdirectory of the current working directory, e.g. creating a new directory by mkdir thesis.

I was thinking about how novices would look at the "Summary of Basic Commands" and might get confused. A callout box might be helpful.

________________________________

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen for further discussion.
