### ISSUE TITLE
Missing solutions to, context for, and files required by exercises

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#518]
Many of the exercises don't have solutions. Some don't need solutions because learners can run the commands and see which is the correct answer. In some of the exercises, the commands can't be tested because the data files don't exist e.g. 07-find, "matching and subtracting" - there are no *ose.dat files

> The -v flag to grep inverts pattern matching, so that only lines which do not match the pattern are printed. Given that, which of the following commands will find all files in /data whose names end in ose.dat (e.g., sucrose.dat or maltose.dat), but do not contain the word temp?
> 
> find /data -name '*.dat' | grep ose | grep -v temp
> find /data -name ose.dat | grep -v temp
> grep -v "temp" $(find /data -name '*ose.dat')
> None of the above.

Sometimes it isn't clear which directory the question refers to.

I plan to submit a series of PRs to address these issues, using existing files as much as possible. Is this of interest to others?

**Comment by shwina** [comment]
@gcapes - yes, of course! PRs addressing these issues are more than welcome.

**Comment by gcapes** [comment]
@shwina 
See #520.
A bit of context for the latter part of this PR: I think it's very helpful for learners to be able to try the commands, rather than only having a mental exercise e.g. 05-loops/variables in loops
> Suppose that `ls` initially displays...

It is for this reason that I'll be changing the exercises on this episode to use existing files, rather than providing solutions for the exercises as they currently stand.
Cheers

**Comment by shwina** [comment]
Thanks for all your contributions and for this summary @gcapes! I'll begin reviewing ASAP.

**Comment by gcapes** [comment]
Great, thanks!
