### ISSUE TITLE
head -1 vs head -n 1

### ISSUE THREAD

**Issue by marwahaha** [swcarpentry/shell-novice#529]
In http://swcarpentry.github.io/shell-novice/04-pipefilter/

The lesson text specifies `head -n 1`, but the graphic uses `head -1`. They both "work"; however, they should be consistent.

I prefer `head -n 1` since I can show what `head -n 2` does, also.

**Comment by shwina** [comment]
Thanks for reporting. PR welcome that changes the graphic to use `head -n 1`.
