### ISSUE TITLE
07-find.md, haiku authors

### ISSUE THREAD

**Issue by tinavisnovska** [swcarpentry/shell-novice#530]
Hi, authors of the haiku poems used in http://swcarpentry.github.io/shell-novice/07-find/ are Bill Torcaso, Howard Korder, and Margaret Segall, respectively. 

source and the competition description:
https://web.archive.org/web/19991201042211/http://salon.com/21st/chal/1998/01/26chal.html
https://web.archive.org/web/20000310061355/http://www.salon.com/21st/chal/1998/02/10chal2.html 
https://web.archive.org/web/20000229135138/http://www.salon.com/21st/chal/1998/02/10chal3.html

Also, if the names are added at some point, the comment 'Forever, or Five Years' won't be appropriate anymore.

**Comment by shwina** [comment]
@tinavisnovska  Thank you for finding this!

**Comment by jessnicwelch** [comment]
Hi! I've created a [PR](https://github.com/swcarpentry/shell-novice/pull/1346) to address this issue.

**Comment by bkmgit** [comment]
@jessnicwelch Thanks for working on this.

**Comment by bkmgit** [comment]
https://github.com/swcarpentry/shell-novice/pull/1346
