### ISSUE TITLE
goodiff and goostats do not give usage instructions when used without arguments

### ISSUE THREAD

**Issue by mbeyeler** [swcarpentry/shell-novice#538]
The two bash scripts `goodiff` and `goostats` in [data-shell/north-pacific-gyre/2012-07-03](https://github.com/swcarpentry/shell-novice/tree/gh-pages/data-shell/north-pacific-gyre/2012-07-03) tend to confuse workshop participants. It would help if the scripts' usage would be explained [on the website](http://swcarpentry.github.io/shell-novice/06-script/).

In addition, it would be great if the scripts printed usage information to stdout whenever people attempt to use them without input arguments (as is common with bash scripts).

**Comment by shwina** [comment]
+100.

**Comment by gcapes** [comment]
Fixed in #616
