### ISSUE TITLE
Setup for machine with Windows patched by the university

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#539]
During https://anenadic.github.io/2017-03-30-manchester/, some learners was using Windows patched by the university. At their custom Windows machine, the `HOME` directory is mapped to a "virtual"/network driver that I don't know how to access from Git Bash. We solve the problem using

~~~
$ curl -o data-shell.zip http://swcarpentry.github.io/shell-novice/data/shell-novice-data.zip
$ unzip data-shell.zip
$ cd data-shell
~~~

# Proposal

Change http://swcarpentry.github.io/shell-novice/setup/ to use the command line (`curl` and `unzip`) to access the files.

# Benefits

The instructions will work for most our users. And we can recommend Linux users to use `wget` instead of `curl`.

# Drawback

Learners could not be able to find the `zip` file on their GUI file manager.

# Related issues

#347

# Instructors who can provide more information

cc @anenadic

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen.
