### ISSUE TITLE
Grep example wrong in lessons 07-find

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/shell-novice#540]
```
$ grep "FE" $(find .. -name '*.pdb')
../data/pdb/heme.pdb:ATOM     25 FE           1      -0.924   0.535  -0.518

```
The above piece of code in lesson 07 (finding things) of shell-novice (http://swcarpentry.github.io/shell-novice/07-find/) does not work as there is no data file heme.pdb in the molecules directory. It also searched in the .. (parent) of the current directory instead of ../molecules.

**Comment by cjieming** [comment]
Hi, I just downloaded the shell-novice-data.zip file [here](http://swcarpentry.github.io/shell-novice/data/shell-novice-data.zip). It seems that under the previous directory, there is a 'data' directory (different from the data dir within the 'writing' dir), and within this 'data' directory, there is a 'pdb' dir, and within this dir a 'heme.pdb' file. So I think this example seems correct.
