### ISSUE TITLE
Enhancement: show error for unknown commands

### ISSUE THREAD

**Issue by mondkaefer** [swcarpentry/shell-novice#545]
Section: http://swcarpentry.github.io/shell-novice/02-filedir/

After showing the first command (whoami) we could show what happens if you type non-existing commands. I remember when I started with the Shell many years back I was confused initially because I didn't fully understand what can be typed in the terminal and what not, and learned quickly that it had to be existing commands that i also had to type correctly.
Adding a little paragraph of the type like "Preparation Magic" to show what error message the shell prints if you type a non-existing command like "hello" or the like would perhaps be useful.

I'm happy to contribute if people think that's a good idea.

**Comment by shwina** [comment]
Yes please. There is a distinction to make:

1. Using an existent command incorrectly
2. Using a non-existent command

If possible, could we show examples of both?

**Comment by mondkaefer** [comment]
Yes, sounds good to me.
Question is then where to place these examples in the current tutorial. 
How about putting 2. immediately after the first command that is being used (whoami), and 1. (using an invalid option) right before "ls --help"?

**Comment by mondkaefer** [comment]
Contribution has been merged.
