### ISSUE TITLE
error in solution in loops section

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/shell-novice#546]
Submitted via email by a self paced user:

I was recommended your site by a colleague in computer science, I am a scientist who wants to learn R. I just completed the unix shell (as a starting point) and it was really helpful - thank you guys so much!

However, I spotted a mistake (I tested it to make sure it was a mistake) in one of your questions in the loops section:

http://swcarpentry.github.io/shell-novice/05-loop/

> > ## Solution
> > 5 is the correct answer. `*` matches zero or more characters, so a file name with zero or more
> > characters before a letter c and zero or more characters after the letter c will be matched.

Should be

> > ## Solution
> > 4 is the correct answer. `*` matches zero or more characters, so a file name with zero or more
> > characters before a letter c and zero or more characters after the letter c will be matched. 

Therefore filenames beginning with c, ending with c or with a c in the middle are all matched, therefore cubane and octane are both matched so answer 4 is correct, not answer 5.

**Comment by shwina** [comment]
@maneesha, thank you! This is fixed now:

https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/05-loop.md

**Comment by stragu** [comment]
Could someone close this resolved issue? I just checked and yes, it was corrected in the material.
