### ISSUE TITLE
Reference for teaching command line to people new to UNIX

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/shell-novice#549]
This could be a useful reference in thinking about teaching or presenting the shell to people new to the command line

Addressing the digital divide in contemporary biology: Lessons from teaching UNIX
http://www.biorxiv.org/content/early/2017/04/07/122424.full.pdf+html

HT @ctb

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
