### ISSUE TITLE
Distribute challenges throughout exercises

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#552]
The question of how to use the exercises (distributed throughout the episode or all at the end of the episode) has come up several times in instructor training and instructor discussion sessions. I think this issue is confusing to many new instructors because of the way the new template groups all of the challenges at the end of the episode. We don't want to mislead instructors into thinking the recommended practice is to only use challenges at the end of each episode, especially since we tell them in instructor training that best practice is to have an interactive exercise at least every 10-15 minutes. 

Can we move the challenges from the end of the episode and distribute to appropriate points in each episode?

**Comment by gcapes** [comment]
While there is merit in this request, I think there is also merit in leaving the exercises at the end so they don't interrupt the flow of the lesson.

Instructors are then free to use them where they feel is appropriate. Each instructor will have their own style, and teach the material slightly differently.

I think a higher priority issue which would benefit new instructors is to have realistic timings for each lesson, if all the material is taught. Current timings are far too short.

**Comment by ErinBecker** [comment]
While I certainly agree that each instructor will teach the material differently (and I wouldn't want to enforce uniformity), my concern based on the questions I'm getting from new instructors is that many of them think that because all of the challenges are showing at the end of the lesson, they should be taught at the end of the lesson. This misunderstanding has the potential to be very problematic as it directly contradicts core Carpentry teaching practices (i.e. something interactive every 15-20 minutes). 

I also agree though about making lesson timings more realistic.

**Comment by shwina** [comment]
I think that for each episode, we should identify 2 or 3 key exercises (which should **definitely** be covered in every workshop, and place them appropriately in the episode. The rest of the challenges can be left at the end as extras.

**Comment by gcapes** [comment]
That's a good idea @shwina. 
I would also like to point out that there are the [instructor notes](http://swcarpentry.github.io/shell-novice/guide/), which discuss some of these points under the "Preparing to teach" section. Given this section mentions that there is probably too much material for the time (which is no more self-explanatory than when the exercises should come), perhaps a short discussion of when to give the exercises would be appropriate?

**Comment by shwina** [comment]
In any case, I don't think that this issue should be disscussed in the shell-novice (or any specific lesson's) repository. Perhaps:

https://github.com/swcarpentry/lesson-example/

?

**Comment by shwina** [comment]
Or the instructor's mailing list?

**Comment by k8hertweck** [comment]
When we moved to the new template last year, we discussed the placement of the challenge exercises and elected to keep them at the end of the lesson for reasons @gcapes describes above. Additionally, we recognized that there may be many more challenges listed than would be reasonable for some instructors to cover (e.g., some instructors spend almost half the time on exercises, while others spend less than 10% of their time). 

It would make sense to me to include 2-3 key exercises embedded within the lesson, as @shwina suggests (and which we've also previously discussed, but likely never implemented), and then place other exercises at the end under "Extra challenges" (or a similar subheading, to indicate that these are available but not required).

**Comment by gcapes** [comment]
Having taught this lesson today, I'd like to completely backpedal and agree with @k8hertweck ;)

It would be useful for the first-time instructors (which was me today for the shell lesson) to have some exercises placed strategically to break up the lesson. It's just too much to keep track of if the new instructor has to think which exercises to include and where. I ended up just having an exercise session at the end of each episode, which isn't ideal. 

Also it took about 5 hours to cover all the material.

**Comment by k8hertweck** [comment]
I couldn't ask for more than nearly instantaneous field testing and feedback; thanks @gcapes!
It seems like there's a tendency for instructors to teach directly from the lesson materials (which is not something I personally do; I have a separate document with my teaching notes). The other consideration is that the online lessons are referenced by students following a workshop as a refresher, and are sometimes used as a primary resource for learning programming (I've had students work through lessons on their own). Given these multiple uses, I'll stand by the option of strategic placement of a few exercises, plus extras at the end.

**Comment by ErinBecker** [comment]
I'm excited to see all the great thought and conversation around this. I hadn't realized that there had been previous conversation about this issue and the maintainers' decision was to have the exercises at the end of each module (although I should have realized this). My apologies for jumping the gun on this, it's only that I had this comment from multiple instructors this week and was worried about confusion in communicating our teaching practices. Of course it's up to the maintainers to decide how to format and implement the lesson materials.

I really like the idea of moving a few exercises into the lesson and putting extras at the end. I'd be happy to make some suggestions from a pedagogical perspective if it would be helpful.

**Comment by iglpdc** [comment]
The original idea was to have the exercises at the end, because the episodes should be short enough to avoid the need of having to break them up. The basic rule is that is that if you need to introduce an exercise in the middle of an episode, it's probably because at that point the episode should be split in two.

If we shoot for ~10 episodes in ~3 hours, this means episodes should be around 10-15 minutes at most, with a few minutes to do the exercises at the end of each of them.

**Comment by tracykteal** [comment]
I've also had feedback that instructors want to know which exercises to prioritize, but also know that people use them for self-guided learning, so strategic placement of a few exercises, plus extras at the end sounds great as @k8hertweck @iglpdc  @ErinBecker discuss.

Also, this does seem to be a broader issue. Starting an issue in https://github.com/swcarpentry/lesson-example/ (and pointing to this one here) seems like a good plan for making a general decision. It could also be posted on discuss, and point people to that issue, to get general feedback since not that many people watch that repo.

**Comment by gcapes** [comment]
@iglpdc 
That sounds like solid reasoning. However, in my experience nearly all the episodes take longer than 15 minutes.

**Comment by shwina** [comment]
Closing this, as per @tracykteal and my own suggestion to reopen at https://github.com/swcarpentry/lesson-example/

**Comment by tracykteal** [comment]
Issue submitted to lesson-example https://github.com/swcarpentry/lesson-example/issues/114

**Comment by ErinBecker** [comment]
Thanks @tracykteal. I'll close the duplicate issues in the other SWC repos and point towards your issue.
