### ISSUE TITLE
Section on understanding home directory confusing

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#583]
In the module ["Navigating Files and Directories"](http://swcarpentry.github.io/shell-novice/02-filedir/), there is a section with graphics diagramming Nelle's filesystem. I really like these diagrams, however initially I thought that this filesystem would be in the data file that learners download for this lesson "data-shell", and that doesn't appear to be the case. It seems that this file structure is hypothetical. I think that we should clearly state at the introduction to this hypothetical filesystem that it isn't something that will be represented on the learner's computer anywhere and that we'll be exploring the learner's filesystem shortly. Thoughts?

**Comment by shwina** [comment]
I don't think learners get the idea that we are "downloading Nelle's filesystem". I think it might be more important to stress that their own filesystems may look different.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
