### ISSUE TITLE
List maintainers for this lesson somewhere in the repository?

### ISSUE THREAD

**Issue by wking** [swcarpentry/shell-novice#59]
My impression with the bc split was that Gabriel Devenyi (@gdevenyi) and Christina Koch (@ChristinaLK) would [continue][1] to act as maintainers for this lesson.  However, recent activity in the main branch has been by others:

    $ git log --date=short --pretty='%aN (%ad) - %s' --first-parent origin/gh-pages
    Bernhard Konrad (2015-02-01) - Merge pull request #30 from wking/filedir-challenge-titles
    Emily Jane McTavish (2015-02-01) - Merge pull request #35 from wking/find-challenge-titles
    adina (2015-01-31) - Merge pull request #32 from wking/pipefilter-challenge-titles
    Greg Wilson (2015-01-26) - Merge pull request #58 from standage/html
    Greg Wilson (2015-01-26) - Merge pull request #57 from standage/typo
    Raniere Silva (2015-01-21) - Merge pull request #45 from gvwilson/gh-pages
    Greg Wilson (2015-01-21) - Incorporating change made by @ggorman in #22 manually.
    Greg Wilson (2015-01-21) - Merging #8 and fixing challenge titles
    Greg Wilson (2015-01-16) - Fixing up title
    Greg Wilson (2015-01-16) - Merge pull request #40 from standage/loop
    Greg Wilson (2015-01-16) - Little Women
    Greg Wilson (2015-01-16) - Merge pull request #38 from halexand/gh-pages
    Greg Wilson (2015-01-16) - Merge branch 'fixme' of https://github.com/PBarmby/shell-novice into gh-pages
    Greg Wilson (2015-01-16) - Adding a short note about touching files.
    Greg Wilson (2015-01-16) - Making sub-title display properly
    Greg Wilson (2015-01-16) - Adding mention to discussion of other shells.
    Greg Wilson (2015-01-14) - New Makefile and footer
    Greg Wilson (2015-01-14) - Merge branch 'core' of github.com:swcarpentry/lesson-template into gh-pages
    Greg Wilson (2015-01-05) - Merge branch 'core' of github.com:swcarpentry/lesson-template into gh-pages
    Greg Wilson (2015-01-05) - Merge branch 'core' of github.com:swcarpentry/lesson-template into gh-pages
    Greg Wilson (2014-12-20) - Bringing titles into line with latest version of template
    …

@gvwilson has a lot on his plate, so while I'm happy to have him contributing so much to the lesson, I think we should have at least one person who takes the lesson under their wing and focuses on reviewing pull requests, handling issues, preserving the lesson's focus, and all the other little things that go into maintaining a project.  If we actually have an active maintainer (or maintainers) like that, it would be nice to list them in a local `CONTRIBUTING.md` so the rest of us know who to poke when things go quiet ;).  If nobody is interested in assuming that responsibility, the shell lesson is quiet enough that I'm happy to fill in the role (although it would be better if we could find an interested maintainer with more free time than I have).

For my earlier thoughts on avoiding absent maintainers, see [my][2] [comments][3] [in][4] swcarpentry/site#603.

[1]: https://github.com/swcarpentry/bc/blob/gh-pages/CONTRIBUTING.md#topic-maintainers
[2]: https://github.com/swcarpentry/site/pull/603#issuecomment-56160059
[3]: https://github.com/swcarpentry/site/pull/603#issuecomment-56188437
[4]: https://github.com/swcarpentry/site/pull/603#issuecomment-56203393

**Comment by gdevenyi** [comment]
Hi yes, I am still willing to maintain, just been busy recently and haven't been able to keep up with the firehose of SWC emails.

**Comment by wking** [comment]
On Sun, Feb 01, 2015 at 05:31:22PM -0800, Gabriel A. Devenyi wrote:
> Hi yes, I am still willing to maintain, just been busy recently and
> haven't been able to keep up with the firehose of SWC emails.

No worries.  A month of quiet time is rarely going to be a big deal,
but it may be worth tapping someone as interim maintainer if you get
swamped again.

**Comment by gdevenyi** [comment]
Well, that was kinda the point of having the co-maintainer...

**Comment by ChristinaLK** [comment]
Thanks for the callout @wking and @gdevenyi - I just moved and started a new job and didn't communicate with @gdevenyi or anyone else about making sure that things were covered.  That's on me, and I apologize.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 07:52:01AM -0800, Christina Koch wrote:
> I just moved and started a new job…

Congrats, and good luck :).  Anyhow, it sounds like this was just a
fluke of business compounded by communication issues.  It's unlikely
to happen again going forward, especially if we keep each other up to
date (or poke each other if things go suspiciously quiet ;).

I'd still like a local CONTRIBUTING.md listing maintainers so folks
who are new to this lesson know who to poke.

**Comment by ChristinaLK** [comment]
I like the idea - could we just add it to the README?

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 10:46:11AM -0800, Christina Koch wrote:
> I like the idea - could we just add it to the README?  

We'll want something in CONTRIBUTING.md [1], and I think an
introduction to the maintainers is more contributor-focused than
user-focused (which is who I see as the README audience).  It's a
fuzzy boundary though, and “users” and “contributors” aren't disjoint
sets, so I'm ok with it landing in the README.  We may want to ask on
lesson-template to get a broader consensus.

**Comment by ChristinaLK** [comment]
You're right, it's more appropriate in CONTRIBUTING.md, I just want us to be as easily found as possible.  :)  Maintainers listed in CONTRIBUTING.md and then a link to CONTRIBUTING from the README sounds like a good compromise to me.  

I'll open an issue on lesson-template for more input...

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 07:59:50PM -0800, Christina Koch wrote:
> Maintainers listed in CONTRIBUTING.md and then a link to
> CONTRIBUTING from the README sounds like a good compromise to me.

Sounds great :).

> I'll open an issue on lesson-template for more input...

Thanks.

**Comment by ChristinaLK** [comment]
See PR #68
