### ISSUE TITLE
ls -F different on Git Bash

### ISSUE THREAD

**Issue by marwahaha** [swcarpentry/shell-novice#590]
Hi folks,

Right now, the `ls` lesson starts like this:
![image](https://user-images.githubusercontent.com/2541209/27620236-253f1cfe-5b96-11e7-9391-271c5f5adc74.png)

This is true for Mac machines, but on Git Bash on Windows, I think this is not the case. `ls` already adds `/`s to directories -- instead, `ls -F` will colorize the screen (it will also show the `/`s). 

(I'm not 100% sure about the behavior, but I can check at my workshop tomorrow.)

It's a little weird because this is so early in the lesson, and almost immediately, the instructions are OS-dependent, which seems odd. 

Here's a suggested fix:

> On some systems, `ls` won't tell the difference between files and directories! You can change that by supplying the **flag** `-F`, which will classify each entry. Directories will now have a trailing slash.

**Comment by gdevenyi** [comment]
Hi, your suggested fix is welcome as a PR.

I'd like to see the addition to mention that colour is also used (and inconsistent)

**Comment by loz-hurst** [comment]
I'm concerned about this - Git for Windows does not provide BASH but rather "BASH emulation" for the sole purpose of running `git` commands.  I think "fixing" the content for a shell environment that the developers themselves say is not BASH is going to introduce a wealth of unnecessary confusion and complexity to the materials.

From the "Git for Windows" homepage (https://gitforwindows.org/):

> Git for Windows provides a BASH emulation used to run Git from the command line. *NIX users should feel right at home, as the BASH emulation behaves just like the "git" command in LINUX and UNIX environments.

**Comment by gcapes** [comment]
> but on Git Bash on Windows, I think this is not the case. ls already adds /s to directories -- instead, **ls -F will colorize the screen** (it will also show the /s).

This isn't the case for me testing just now with Git Bash. `ls` actually seems to be aliased to something like `ls -F --colour=auto` i.e. the default output is coloured and categorised, so `ls` and `ls -F` give the same output. If I run `\ls`, then I get a non-coloured, non-categorised output.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen for further discussion.
