### ISSUE TITLE
Empty Desktop folder in shell-novice-data.zip

### ISSUE THREAD

**Issue by cengel** [swcarpentry/shell-novice#592]
In the current https://swcarpentry.github.io/shell-novice/data/shell-novice-data.zip the `data-shell` folder contains an (empty) folder called `Desktop`. This is slightly confusing when demonstrating `ls -F Desktop/data-shell`. The `Desktop` folder contained in `data-shell` obviously will be listed, but it is of course not the same as the `Desktop` folder which contains `data-shell`.

**Comment by gcapes** [comment]
It's not the only empty folder with no apparent purpose (#648).

**Comment by gcapes** [comment]
And I noticed, it's also inconsistent with the output from `ls data-shell` in episode 2.
