### ISSUE TITLE
Bug: Navigation arrows do not appear properly on some browsers

### ISSUE THREAD

**Issue by colinbrislawn** [swcarpentry/shell-novice#596]
On Internet Explorer, these arrows do not appear:
![example](https://user-images.githubusercontent.com/10355152/28682551-4134f70c-72b2-11e7-83fd-f1816a74cd64.png)

This is super confusing for Windows users!

If there is a more appropriate place to post this, please let me know.
This could be related to https://github.com/swcarpentry/workshop-template/issues/104

**Comment by shwina** [comment]
I think https://github.com/swcarpentry/styles is the correct repository for this issue. @rgaiacs?

**Comment by colinbrislawn** [comment]
Oh yeah, that makes more sense. Looks like it was implemented over here: https://github.com/swcarpentry/styles/issues/78 

I'll move this Issue.

**Comment by shwina** [comment]
Thank you. I will close this issue.
