### ISSUE TITLE
Issue with "Unix Shell: Navigating Files and Directories" module and macOS

### ISSUE THREAD

**Issue by prynhart** [swcarpentry/shell-novice#597]
I worked through the Unix Shell module using a clean install of macOS Sierra on my MacBook.  One issue I noticed when following the lesson at https://swcarpentry.github.io/shell-novice/02-filedir/, was:

* A macOS environment is assumed under the "Slashes" subheading (because /Users is used as the home folder location)
* Later on in the same lesson the GNU/Linux version of ls (which isn't shipped with macOS) is assumed; in particular, the Darwin (macOS) version of "ls" doesn't accept the option "--help".  On a clean install of macOS the following will happen if "--help" is passed as a parameter:

$ ls --help
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]

Suggestions to fix:

1. Assume Linux from the start (i.e. change /Users to /home), also updating the graphic.
2. Ask macOS users to install GNU utils as third-party, e.g. brew install coreutils

**Comment by cengel** [comment]
Potentially related to [534](https://github.com/swcarpentry/shell-novice/issues/543) and [447](https://github.com/swcarpentry/shell-novice/issues/447)?

**Comment by gdevenyi** [comment]
Thanks, this is indeed a longstanding problem with OSX supplying BSD instead of GNU tools, patches to correct this are welcome, for now, limiting discussion to other issues.
