### ISSUE TITLE
06-script: Piping output from shell script into wc hangs on Mac

### ISSUE THREAD

**Issue by cengel** [swcarpentry/shell-novice#598]
The following line from http://swcarpentry.github.io/shell-novice/06-script/ does not work for my setup:

`$ bash do-stats.sh *[AB].txt | wc -l`

It does not produce any output and does not return the prompt, so apparently `wc` just sits and waits for input. 

`$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.`

MacOS 10.12.5

**Comment by gdevenyi** [comment]
@cengel are you running this in the directory with the necessary input files?

**Comment by cengel** [comment]
@gdevenyi - I do. `bash do-stats.sh *[AB].txt` works the way it should.

`$ pwd`
`/Users/cengel/Desktop/data-shell/north-pacific-gyre/2012-07-03`

`$ ls`
`NENE01729A.txt`
`NENE01729B.txt`		
... etc				
`do-stats.sh`			
`goodiff`
`goostats`

**Comment by colinmorris** [comment]
@cengel have you tried waiting a minute or so? `goostats`, which `do-stats.sh` calls in a loop, is designed to take a few seconds every time it's run. (This is mentioned in the [loops](http://swcarpentry.github.io/shell-novice/05-loop/) episode, but not the scripts episode))

We may want to add a warning about this in the text.

**Comment by cengel** [comment]
Wow, yes.. @colinmorris, patience pays off - it does work for me. Thanks for suggesting this.

**Comment by colinmorris** [comment]
Glad that worked! Since this seems to be resolved, I'm going to close this issue now, but feel free to open another issue (or PR) if you think the lesson would be improved by adding some kind of warning about this.
