### ISSUE TITLE
Link to haikus 

### ISSUE THREAD

**Issue by cengel** [swcarpentry/shell-novice#599]
fwiw - the original haiku page can be found through the [Wayback Machine](http://web.archive.org) here:
http://web.archive.org/web/20101211195815/http://www.salon.com/21st/chal/1998/02/10chal3.html

**Comment by gdevenyi** [comment]
Thanks @cengel what is this for?

**Comment by cengel** [comment]
@gdevenyi gdevenyi its for http://swcarpentry.github.io/shell-novice/07-find/ 

Very early on on the lesson it says: 

"Forever, or Five Years
We haven’t linked to the original haikus because they don’t appear to be on Salon’s site any longer. As Jeff Rothenberg said, “Digital information lasts forever — or five years, whichever comes first.”"

**Comment by gcapes** [comment]
It looks like Software Carpentry modified one of the haikus so as not to bash Windows. Original given below (my bold).

> Yesterday it worked
Today it is not working
**Windows** is like that 
-- Margaret Segall

I can't see any reason not to link to the originals now a link has been found?

**Comment by colinmorris** [comment]
This was addressed by #710
