### ISSUE TITLE
data-shell/data/animals.txt is truncated

### ISSUE THREAD

**Issue by bpteague** [swcarpentry/shell-novice#600]
The Pipes & Filters episode says that `data-shell/data/animals.txt` contains 500+ lines.  However, in the `shell-novice-data.zip` file I just downloaded, it only has 8 lines.  It would be much more fun and interesting if it was a "real" data set.

**Comment by laufers** [comment]
I will second this. In prepping for a workshop, it appears that the original animals.txt file is not the original file from which the learners cannot do the challenge.

**Comment by agrimstrup** [comment]
In the "Pipe Reading Comprehension" section of the Pipes & Filters episode, the contents of the animals.txt file is specifically given as:

2012-11-05,deer
2012-11-05,rabbit
2012-11-05,raccoon
2012-11-06,rabbit
2012-11-06,deer
2012-11-06,fox
2012-11-07,rabbit
2012-11-07,bear

This matches the contents of the file in data-shell/data/animals.txt.

**Comment by colinmorris** [comment]
This situation is similar to the one described in #720. A good solution might be similar to what @shwina proposed there. Tell the students we'll be working with a small subset of the 'real' data. 

(I wonder whether originally the starter data was larger in scale, and it was later reduced to be less intimidating, with not all the references in the text being updated?)

**Comment by gcapes** [comment]
Thanks for the catch!

However, as indicated in https://github.com/swcarpentry/shell-novice/issues/600#issuecomment-370090229 this looks to have been fixed now.
