### ISSUE TITLE
Cut command isn't introduced before being used in pipes and filters section.

### ISSUE THREAD

**Issue by jdagdelen** [swcarpentry/shell-novice#608]
The `cut` command and its options (`-d`, `-f`) aren't introduced before they are used in the pipes & filters section. They are also not included in the summary at the end of the section.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by colinmorris** [comment]
The `d` and `-f` options are explained now thanks to #685, but your other points still stand. We should definitely give a brief introduction of what cut is / what it's used for.

**Comment by bonnie22** [comment]
The `cut ` command is used to remove or "cut out" certain sections of each line in the file. The -d flag is used to define the delimiter. If left blank the default default delimiter is tab. The -f flag is used to select the field to cut out

**Comment by hannahburkhardt** [comment]
@gdevenyi would you mind closing this issue? I think I messed up the commit message so it didn't close automatically.
