### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by dakane1** [swcarpentry/shell-novice#612]
This is a really minor thing but is there any way to change the font for the lesson?  I had a number of issues distinguishing 1 (ones) from the letter l.  When I mentioned it to a few people they said they were having the same problem. Thanks

**Comment by rgaiacs** [comment]
@dakane1 Thanks for the issue. I created https://github.com/swcarpentry/styles/issues/168 to cover this issue and similar issue in the other lessons. I took the liberty to add more information to it.

I'm closing this issue to avoid duplication. Feel free to comment at https://github.com/swcarpentry/styles/issues/168. As soon as we have a resolution we can push a change to this lesson.
