### ISSUE TITLE
`filesystem` status?

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/shell-novice#62]
The `filesystem` folder looks kind of messy right now - not a clear structure in place.  Has there been discussion about what it should look like?  If so, can someone point me to it?  If not...let's discuss!

**Comment by timtomch** [comment]
I think the idea was to be able to demonstrate that there can be more than one user on a filesystem. However, in practice, the whole lesson is spent fiddling in the 'nelle' folder. As a result, and to reduce confusion, I now distribute a zipped file of only the 'nelle' folder to students.

If I need to demonstrate more filesystem stuff, I use my own.

But I'm ready to hear arguments against my approach...

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 07:00:49PM -0800, Thomas Guignard wrote:
> As a result, and to reduce confusion, I now distribute a zipped file
> of only the 'nelle' folder to students.

The approach I've been advocating for a while has been to put together
a Git repository with everything the students should have locally.
Then they can check it out (with its history) or download the zip
archive (e.g. [1]).  That's a bit awkward now with lessons that bundle
both the student-side content (e.g. the nelle filesystem) and
server-side content (e.g. compiled HTML versions of the Markdown
lesson source).  For previous discussion on this issue, see #41, #44,
swcarpentry/bc#299, swcarpentry/bc#646 and swcarpentry/bc#716, and
these list posts [2,3,4]).

[1]: https://github.com/swcarpentry/shell-novice/archive/gh-pages.zip
[2]: http://lists.software-carpentry.org/pipermail/gits_lists.software-carpentry.org/2013-June/000193.html
[3]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2013-September/000964.html
[4]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2014-April/001547.html

**Comment by ChristinaLK** [comment]
Thanks for the links @wking .  I think I'll try to clean up the current `nelle` directory (get rid of all the "backup" folders, which are just confusing), maybe remove the "user" layer and rename `filesystem`, `data` for template consistency.  Then we can tackle how people get the stuff.  :)

**Comment by gdevenyi** [comment]
Well, looks like PR #77 broke a bunch of lessons since they all refer to users/ which no longer exists.

We need to clean up the lessons to refer to the new structure or #77 should be reverted.

**Comment by ChristinaLK** [comment]
I can clean up the lessons tonight.

**Comment by ChristinaLK** [comment]
Actually, I think I'll change the directories back to more like they were.  I still don't like having such a long path from filesystem -> nelle, but that may not be able to be helped.
