### ISSUE TITLE
Nelle cancels the run, but now has extra `stats-` files which are matched

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#625]
I'll submit a PR as this has caught me twice now. We just need to delete the `stats-*` files before rerunning the loop.

**Comment by shwina** [comment]
Generally I get around this by using the pattern `NENE*.txt` to specify the list of files. I much prefer avoiding using `rm` with a wildcard as much as possible.

Does this sound reasonable?

**Comment by gcapes** [comment]
Yes, it sounds like a more robust approach. I'll rebase my branch now so you should get a different commit which fixes the issue in a different way.
Thanks
