### ISSUE TITLE
Add example of launching a GUI editor from the command line in "Which Editor?" section

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#628]
MY SUGGESTIONS:
This is my addition request for the http://swcarpentry.github.io/shell-novice/03-create/
I feel it will nice to add which I will be showing the use of GUI editors in Linux.
So I am suggesting a section like adding :
1) in section Which Editor?
We can access GUI text editors in Linux like gedit, nedit even through CLI . For this we can use the command gedit <filename> or nedit<filename>. Nedit offers a more programmer feel while gedit is a basic to intermediate text editor.
2) also in the section Listing Recursively and By Time

It would nice to add :
Is the difference between cp –r and cp –R?
They are equivalent in realism and perform recursive copy . This is often a confusion I have seen basic users have.

**Comment by colinmorris** [comment]
It looks like the "Listing Recursively and By Time" section mentioned in 2. no longer exists, so I've changed the title to describe suggestion 1. 

The "Which Editor?" callout box does mention GUI editors such as Gedit, and even implicitly mentions they can be launched from the command line ("If you start it from the shell"), but maybe it's worth giving an example of what this looks like?

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen.
