### ISSUE TITLE
directory hieararchy diagram learning objective not addressed

### ISSUE THREAD

**Issue by bradfordcondon** [swcarpentry/shell-novice#629]
One of the learning objectives for Lesson 3 is : Create a directory hierarchy that matches a given diagram.  However, I don't think the lesson includes a hierarchy diagram, nor does it ask the user to replicate one.  When I think of directory hierarchy diagram ,I think of something like below

```
home/
├── includes/
│   ├── input_data/
│   │   └── files/
│   │       ├── file_A.txt
│   │       ├── file_B.txt
│   │       └── file_C.txt
│   └── input_data_readme.txt
└── rest of my files
```
I would suggest providing a simple (simpler than the above and using the actual file structure for the lesson, apologies for just modifying an example from another project...) file tree and asking them to try replicating it as a final question to the exercise.  If you all agree I'd be happy to make a PR.

**Comment by zingale** [comment]
+1

**Comment by deppen8** [comment]
This is covered in Episode 3 "Reproduce a folder structure" exercise.
