### ISSUE TITLE
Change name of Dr. Horrible?

### ISSUE THREAD

**Issue by kellyrowland** [swcarpentry/shell-novice#635]
In the "notes" file, Nelle aspires to get a post-doc position, preferably with a "Dr. Horrible".

Elsewhere in the lesson, a more positive and lighthearted approach to academia is taken (see: creating draft.txt in the 'thesis' directory), so I would hope that the whole lesson would be consistent in this tone.

Dr. Excellent? Dr. Wonderful?

**Comment by gdevenyi** [comment]
A pop-culture reference:
https://en.wikipedia.org/wiki/Dr._Horrible%27s_Sing-Along_Blog

**Comment by kellyrowland** [comment]
Ah! Shame on me then.

**Comment by gdevenyi** [comment]
Go watch it, its amazing :+1: thanks for the concern :)
