### ISSUE TITLE
"Contact" links at the bottom of every page are broken

### ISSUE THREAD

**Issue by remram44** [swcarpentry/shell-novice#643]
```html
<a href="">Contact</a>
```

**Comment by gdevenyi** [comment]
@rgaiacs is this a template issue?

**Comment by remram44** [comment]
From what I can see, there's a mismatch between `contact` and `email`:

https://github.com/swcarpentry/shell-novice/blob/b64fd1e5deabe708ef67c15e832312f9e333654f/_includes/lesson_footer.html#L34

https://github.com/swcarpentry/shell-novice/blob/1b1c335e6d7f5fb5e6df76fb6f0e976ddb79a88a/_config.yml#L12

But I'm not too familiar with Jekyll, so 😅

**Comment by rgaiacs** [comment]
@gdevenyi yes. See https://github.com/swcarpentry/styles/issues/178.

@remram44 Thanks for the comment. We were both working at the same time. I can't fix it in styles now. Sorry. And need to fix it without rushing.

**Comment by remram44** [comment]
Indeed, better not break the lessons for a minor annoyance like this. Closing this in favor of the `styles` ticket. Thanks!

**Comment by gdevenyi** [comment]
Thanks for the careful eye @remram44
