### ISSUE TITLE
Stressing the importance of punctuation, especially spaces

### ISSUE THREAD

**Issue by VBOz** [swcarpentry/shell-novice#650]
Please delete the text below before submitting your contribution. 

--- Navigating Files and Directories
As a total novice, thinking about other total novices, it was not clear to me first off how important it was to be aware of how precise you need to be in typing commands including where a space was needed. Yes, you learn but it is such a stupid thing to have to ask, I'd have appreciated having it spelled out right up front ie there is a difference between ls-F and ls -F

 

---

**Comment by colinmorris** [comment]
That's a good thought. I'd definitely be open to looking at a pull request, if you have an idea of how to communicate this. Maybe a small callout box after the first use of a flag (the `ls -F` in episode 2)?

**Comment by gcapes** [comment]
Yes, it would be good to have this explicit earlier on. I certainly talk about this when teaching, but it's not actually in the material until later on (quoting variables to protect spaces in names). 
This has been addressed in PR #690 (awaiting a merge). @gdevenyi

**Comment by Lyndon18** [comment]
I agree with the original comment.

Back when I was doing a shell introduction course, I found the introducing the commands' basic structure (command option argument) was very helpful when introducing commands with common options. Could be useful to add a callout box for this too.

**Comment by deppen8** [comment]
Issue should have been resolved in #690. Closing as part of old issue cleanup.
