### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by VBOz** [swcarpentry/shell-novice#651]
Broken link for the "creating an Issue" in the text below

How to Contribute

The easiest way to get started is to file an issue to tell us about a spelling mistake, some awkward wording, or a factual error. This is a good way to introduce yourself and to meet some of our community members.

If you do not have a GitHub account, you can send us comments by email. However, we will be able to respond more quickly if you use one of the other methods described below.

If you have a GitHub account, or are willing to create one, but do not know how to use Git, you can report problems or suggest improvements by **creating an issue**. This allows us to assign the item to someone and to respond to it in a threaded discussion.

**Comment by rgaiacs** [comment]
@VBOz Thanks for the report.

The file is https://github.com/swcarpentry/shell-novice/blob/gh-pages/CONTRIBUTING.md. The link should be https://github.com/swcarpentry/shell-novice/issues/ instead of https://github.com/swcarpentry/FIXME/issues/. This is related with https://github.com/swcarpentry/styles/issues/175.

**Comment by gdevenyi** [comment]
@rgaiacs will this be fixed via a style pull or should we fix it?

**Comment by rgaiacs** [comment]
> will this be fixed via a style pull

No. Probably changes in https://github.com/swcarpentry/styles will re-create this issue. :-( This is why I want to discuss https://github.com/swcarpentry/styles/issues/175.

> should we fix it?

Yes, please.

**Comment by shwina** [comment]
Fixed in https://github.com/swcarpentry/shell-novice/commit/ddf72820e3172420717110c04ab8832489220b2a
