### ISSUE TITLE
goodiff is never used

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#655]
Two scripts are introduced in episode 1 of the lesson, but only one is ever used.

Perhaps `goodiff` should be dropped from the story if it isn't used (my preference because the lesson is long enough as it is), or included in the processing script in ep 6. It's not quite clear if `goodiff` needs to be run for all combinations of processed samples, but whatever the intention, it would add extra complication.

Thoughts?

**Comment by gcapes** [comment]
It looks like perhaps it was once part of the lesson because `redo-figure-2.sh` contains reference to it.

**Comment by shwina** [comment]
+1 to remove, but we do need to make sure all references to it are removed as well.

**Comment by gcapes** [comment]
Yep, of course -- is this a green light then, or should I wait for comments from the other maintainer?

**Comment by shwina** [comment]
@gdevenyi ?
