### ISSUE TITLE
gh-pages vs master

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/shell-novice#66]
This repository has two branches: `gh-pages` and `master` (96 commits behind `gh-pages`). This can be confusing to someone new to Software Carpentry (e.g. #28).

@gdevenyi, @ChristinaLK and @wking, Could we remove the `master` branch?

**Comment by ChristinaLK** [comment]
My understanding from @gdevenyi was that if we remove the master branch, we remove old pull requests from before the split.  Once we've closed those (hopefully soon!), I think we can delete `master`.  

For now there's a note on the README for new pull requests to be against `gh-pages`.

**Comment by gvwilson** [comment]
Let's try to close them all by the end of next week - if that means 
discarding some, so be it.

**Comment by ChristinaLK** [comment]
Only one outstanding PR left!  Almost there...

**Comment by gdevenyi** [comment]
Looks like we're all cleared up. There seems to be some stray branches that somehow were created by PRs? We can probably remove those too.

**Comment by wking** [comment]
On Wed, Mar 18, 2015 at 08:30:16AM -0700, Gabriel A. Devenyi wrote:
> There seems to be some stray branches that somehow were created by
> PRs? We can probably remove those too.

The *-patch-* stuff is probably from folks creating PRs using GitHub's
web UI.  Here's where the existing branches were used:

* lexnederbragt-patch-2, #90, merged
* lexnederbragt-patch-1, #86, open
* stephenturner-patch-1, #67, merged

I'd leave lexnederbragt-patch-1 alone until #86 is resolved, but
you're free to remove the other two.

**Comment by ChristinaLK** [comment]
Done!  Will delete the note in the README.
