### ISSUE TITLE
Suggestion for diff coverage

### ISSUE THREAD

**Issue by FredReiss** [swcarpentry/shell-novice#661]
After going through the bash/shell sessions, I noticed a lack of mention of diff or other file check/comparison techniques.  Is there any objection to adding some mention of diff as a useful tool to compare the contents of two files?  As part of the story narrative, one could diff two data files generated on different days by a common process, in order to determine what lines were added/changed between the two file generation times.

**Comment by shwina** [comment]
I agree. But what should be removed to make space for this addition to the lesson?

**Comment by gdevenyi** [comment]
I think we're at max here but shell-extras would love this

**Comment by gdevenyi** [comment]
Thanks for your contribution!
