### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by colinmorris** [swcarpentry/shell-novice#687]
Currently all code snippets seem to be annotated with `{: .bash}`.

But according to [this](http://swcarpentry.github.io/lesson-example/04-formatting/index.html) the class name to use to get syntax highlighting is actually `.language-bash`.

**Comment by rgaiacs** [comment]
@colinmorris Thanks for the issue.

This was documented http://swcarpentry.github.io/lesson-example/04-formatting/index.html but I think that I forgot to mention on the [release note](https://github.com/swcarpentry/styles/releases/tag/v9.3.0).
