### ISSUE TITLE
07-find : duplicated exercises

### ISSUE THREAD

**Issue by taupalosaurus** [swcarpentry/shell-novice#689]
In the lesson "Finding Things", exercises "Tracking a Species" and "Little women" are duplicated, once in the middle of the lesson and once at the end. As far as I can tell, they were moved to the middle of the lesson in commit c0655eb, and commit 7c31fd7 added them at the end again.
I don't want to submit a fix before being sure what is their right location!

**Comment by gdevenyi** [comment]
Good catch, looks like someone else's branch clobbered this.

Can you submit a PR to re-remove the end-of-lesson stuff?

**Comment by taupalosaurus** [comment]
@gdevenyi, yes, done!

**Comment by colinmorris** [comment]
Fixed with #694. Thanks!
