### ISSUE TITLE
Add path to working directory after the third exercise in "Loops"

### ISSUE THREAD

**Issue by vguerracanedo** [swcarpentry/shell-novice#695]
Exercise two and three are based on the material of the directory data-shell/molecules. After these exercises, the lecture is continued in a different directory (data-shell/creatures). It might be helpful to add a note of the directory where the followings section of the lecture is going to be based on.

**Comment by colinmorris** [comment]
Ah, I can see how that could be confusing.

We could definitely give a textual reminder when the main lecture continues ("returning to the `data-shell/creatures` directory..."), or within the exercises ("don't forget to return to the `creatures` directory when you're done").

Another alternative would be to, in the exercises, refer to molecules using relative paths, so they can stay in `creatures` the whole time. e.g. `for datafile in ../molecules/*.pdb`.

**Comment by gcapes** [comment]
I'll submit a PR. I think this has arisen due to rearranging the placement of the exercises without correcting the text accordingly.
