### ISSUE TITLE
Introduce Man pages

### ISSUE THREAD

**Issue by bboucek** [swcarpentry/shell-novice#698]
There should be an introduction to **man** pages for **shell-novice** at the beginning of the lesson.

**Comment by colinmorris** [comment]
Currently, `man` is introduced about halfway through [episode 02](https://swcarpentry.github.io/shell-novice/02-filedir/). This is right after we introduce `ls`, which is the first command they'll run that has any interesting options.

Is there a specific earlier point you'd suggest moving it to?

**Comment by bagustris** [comment]
I would like to suggest to link one of the word `man` in that episode 02 to [this](https://en.wikipedia.org/wiki/Man_page) wikipedia link. It also important to give learner motivation that almost (80%) of Unix shell coding problem can be solved by only reads the `man page` [1].

[1] http://www.readthefuckingmanual.com/

**Comment by elenavataga** [comment]
I believe section about navigating man pages would benefit from some extension:

"To navigate through the man pages, you may use the up and down arrow keys to move line-by-line, or try the “b” and spacebar keys to skip up and down by a full page. "
 
=> "Page up" and "page down" keys work with man pages  and it is the most intuitive choice (comparing with "b" and spacebar)

"To search for a character or word in the man pages, use “/” followed by the character or word you are searching for."
What about cases when there are more then single occurrence? It can be misleading when only the first match is visible.
Suggested edit:
=> "To search for a character or word in the man pages, use “/” followed by the character or word you are searching for,  press "n" to move to the next occurrence."

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen for discussion.
