### ISSUE TITLE
03-Working With Files and Directories - * used in solution before introduced

### ISSUE THREAD

**Issue by lauterbur** [swcarpentry/shell-novice#699]
The answer to the exercise in "Copy a folder structure sans files" uses a wildcard (*), but that is only introduced in the next section, 04-Pipes and Filters. I would suggest at least briefly introducing it previously, perhaps with ls. Perhaps with an example of wanting to see only the .dat files in a directory, using $ ls *.dat. This could have the added benefit of showing the importance of choosing consistent file names that make sense.

**Comment by colinmorris** [comment]
Good catch!

Episode 4 goes into wildcards at length, so I think I'd prefer to hold off on mentioning/using them until then.

What do you think about either removing the exercise, or moving it to episode 4? (Or rewriting it to not use wildcards?)

**Comment by lauterbur** [comment]
The answer to the "Organizing Directories and Files" uses a wildcard as well (mv *.dat analyzed). That's more easily rewritten - the solution could be 
$ mv fructose.dat sucrose.dat analyzed 
or $ mv fructose.dat analyzed
$ mv sucrose.dat analyzed

I think "Copy a folder structure sans files" would have to be moved to episode 4 for best effect. I don't see a good way of rewriting it, unless the files to be removed from the raw and processed directories were specified, which could get unwieldy/possibly confusing.

**Comment by OKaluza** [comment]
I would like to see this one solved but I'm going to confuse the issue by adding my 2c.

I disagree with holding off on mentioning wildcards and vote for introducing the wildcard in brief in episode 3, and expanding on it in 4 (or alternatively, just moving the full coverage to episode 3 where it fits better), reason being:
- The topic of 3 "Working with files and directories" would be remiss not to include one of the most commonly used features for working with files and directories; but the * wildcard is used far more than ? so it would be enough to just cover * until the next lesson
- Modifying the "Organizing Directories and Files" answer to avoid the wildcard would provide a *technically* correct answer, but no one would ever do it this way and it would be painful beyond two or three files. By offering both solutions, using wildcards and without you get to show how they are useful after getting students to think about how to solve a problem addressing multiple files, then follow with an explanation of the wildcard answer

Something like:

> **Use *wildcards* to save typing file names**
> 
> The **\*** in \*.dat is a wildcard that will match zero or more characters in a file name. When encountered by the shell, it is "expanded" to a list of all files that contain the characters you have typed along with anything else in place of the wildcard, so *.dat matches fructose.dat, sucrose.dat, and every file that ends with ‘.dat’.  
You will find this very useful as a way of operating on a large number of files at once and is covered in more detail in the next lesson.

Links to exercises in question
http://swcarpentry.github.io/shell-novice/03-create#organizing-directories-and-files
http://swcarpentry.github.io/shell-novice/03-create#copy-a-folder-structure-but-not-the-files
The later introduction of wildcards:
http://swcarpentry.github.io/shell-novice/04-pipefilter#wildcards

**Comment by gcapes** [comment]
I like this proposal. It wouldn't require any rewriting of episode 4 either.
I would however reword the explanation slightly, maybe to explain by example like in episode 4. The current wording is a bit confused.

**Comment by OKaluza** [comment]
I rewrote it with more examples and hopefully clearer wording:
> `*` is a **wildcard**. It matches zero or more characters, so `*.dat` matches every file in the directory that ends with '.dat', that being: `fructose.dat`, `sucrose.dat`. You can try it with `ls *.dat` and see the result is just these two files.
> `*` will match every file and subdirectory: `fructose.dat`, `sucrose.dat`, `analyzed`, `raw`, if you try `ls *` it will list not only the files `fructose.dat`, `sucrose.dat`, but also the contents of each of the matched directories `raw` and `analyzed`
> `ls s*` will match anything beginning with the letter 's', which is just: `sucrose.dat` 
> Whenever you want to operate on multiple files, you can avoid typing out the whole list using this feature, which is covered in detail in the next lesson 'Pipes and Filters'.

**Comment by gcapes** [comment]
Looks good to me. This text would just form part of the lesson, directly above the exercises? Or would it go in a callout, because it could be skipped depending on the choice of exercises chosen by the instructor?

**Comment by OKaluza** [comment]
Good point, I wrote as if it would be mentioned as an aside with the solution but as it's relevant to two exercises I guess it should be part of the main lesson above the exercises.

I also just realised looking at the example data, that the files mentioned in the exercise are not included, so it's no good asking the student to try those commands. I will rewrite it with examples that can be tried on provided data.

It will be easier to see how well it works if I just try writing this into the lesson and make a pull-request to hash out the details so I might give that a go.

**Comment by gcapes** [comment]
(as a non-maintainer of this lesson) that sounds like a good approach!

**Comment by OKaluza** [comment]
Hi @gcapes I haven't got a chance yet but intend to, feel free to take over if you want to sort it out, otherwise I should  get a moment sometime this week!

**Comment by gcapes** [comment]
Hi @OKaluza 

I've written up the callout box changes ready for a PR, but the more I think about it, the more I think it would be a neater solution to move the introduction of wildcards entirely in to episode 3 as you suggested in https://github.com/swcarpentry/shell-novice/issues/699#issuecomment-398637101. Splitting over two episodes doesn't really make sense. 

Perhaps I'll just submit the PR and we can iterate on that?

**Comment by OKaluza** [comment]
@gcapes sounds good to me, and yes I agree: probably a better solution to move it
