### ISSUE TITLE
Adding 'less' to unix lesson

### ISSUE THREAD

**Issue by marisalim** [swcarpentry/shell-novice#700]
It would be helpful to teach students the 'less' command in addition to (or instead of?) the 'cat' command for viewing contents of their text files. While the example teaching files are short, the students are likely to encounter lengthier files in their own work. Rather than printing all the file contents to screen, it is easier to look at chunks and scroll through the file with the 'less' command.

**Comment by gcapes** [comment]
This is already covered here: http://swcarpentry.github.io/shell-novice/04-pipefilter/

**Comment by marisalim** [comment]
Thanks for pointing this out! It wasn't taught at the workshop I was at, but glad to see it is in the lesson description.
