### ISSUE TITLE
Audit for movie villan mentions

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/shell-novice#701]

**Comment by deppen8** [comment]
@gdevenyi, I'm going to go ahead and close. I don't see any movie villains in the lesson, so I'm guessing this one is taken care of. 😄 

Of course feel free to reopen if I am missing something.

**Comment by slel** [comment]
Even though the issue is closed, might be worth fixing
the typo "villan" -> "villain" in the issue title.
