### ISSUE TITLE
directory diagram in 02-filedir uses "/" and "root" confusingly in top level folder

### ISSUE THREAD

**Issue by zingale** [swcarpentry/shell-novice#703]
In the directory hierarchy figure in http://swcarpentry.github.io/shell-novice/02-filedir/, the top directory is labeled "/" and underneath "root".  This is the only folder with two labels in that figure, and it can be a source of confusion.  On my linux system, 

`/`
and 
`/root`

are two different directories, one is the root (`/`) and the other is the home directory for the `root` user.  

If a student types `ls /root` as the figure might suggest, they may be trying to look into the `/root/` directory and get permission denied.

It would be good to make the figure consistent and have only a single label `/` in that figure for the root directory.

**Comment by colinmorris** [comment]
Agreed. Good catch.

If anyone's comfortable editing SVG files, the relevant ones are `filesystem.svg` and `home-directories.svg` in the `fig` directory. Pull request welcome!
