### ISSUE TITLE
Mention kernel and add very simple diagram

### ISSUE THREAD

**Issue by fouriejoubert** [swcarpentry/shell-novice#716]
It might worth considering adding just a short paragraph about the kernel, why it is there, what it does and then inserting a simple figure (example attached) to show how the layers fit together.

![architecture](https://user-images.githubusercontent.com/3425899/36586372-2c97e95c-188a-11e8-91e8-a46cc61c1ff9.png)

**Comment by rgaiacs** [comment]
> It might worth considering adding just a short paragraph about the kernel, why it is there, what it does

I disagree. We aren't teaching computer science. Understand all the layers will not benefit our learners.

> inserting a simple figure (example attached) to show how the layers fit together.

I think that the example figure could introduce some misconceptions to learners, for example, why do you mix some implementation, `sh`, `csh`, `ksh`, `bash`, with the abstract concept, shell?

**Comment by gdevenyi** [comment]
This is far outside the scope of a shell lesson. Thanks.
