### ISSUE TITLE
Clarify Windows install instructions

### ISSUE THREAD

**Issue by crivaldi** [swcarpentry/shell-novice#721]
Some users may be confused about installing native bash on windows 10 because this has changed to a ubuntu application through the windows store.  In addition, for very novice users, they might think this is the command prompt, and so be stuck for a while entering commands there to no avail (particularly if they think they are in a shell).
Hope this was helpful!

**Comment by colinmorris** [comment]
Hey @crivaldi , have you seen the Windows install instructions in [the setup section](https://swcarpentry.github.io/shell-novice/setup.html)? Our primary recommendation right now is the Bash shell that comes with Git for Windows (which I think has pretty good support across different Windows versions?).

If you think those instructions could be made clearer, we're definitely open to suggestions.

**Comment by shwina** [comment]
One thing that could be made clearer is that that Windows *does* come with a shell (CMD or 'Command Prompt') which has a completely different syntax than the Unix shell. However, the clarification must written very carefully, as now Windows does support bash..

**Comment by crivaldi** [comment]
Thanks for replies - I do agree that using git bash is great for the lesson - easiest thing by far.

My comment is directed at the instruction for users who wish to use an alternative for some reason (or those who simply wish to go back and install after the workshop). It's a little confusing to newcomers to have the words Bash, Ubuntu, Linux, shell, etc. Also, like @shwina mentioned, there is also a shell that comes in windows that can make this really confusing on top of all that. 

For example: 
> Other solutions are available for running Bash commands on Windows systems. There is now a Bash shell command-line tool available for Windows 10. Additionally....

Could be altered into something like: 
Other solutions are available for running Bash commands on Windows systems. There is now a Bash through Ubuntu command-line tool available for Windows 10 (note: this is different from the Command Prompt, which uses a different syntax than this lesson covers). Additionally....

**Comment by deppen8** [comment]
I think the current [setup instructions](https://carpentries.github.io/workshop-template/#shell) are pretty thorough for Windows, so closing this issue.
