### ISSUE TITLE
add a simple example to show error (stderr) redirection 

### ISSUE THREAD

**Issue by fdiblen** [swcarpentry/shell-novice#729]
Output redirection is nicely shown in 
https://swcarpentry.github.io/shell-novice/04-pipefilter

Both stdout and stderr terms are explained but the examples are only for stdout. It would be nice to add a simple example to show how errors can be redirected.

For example:
```
ls missing.dat 2> errors.txt
```

**Comment by colinmorris** [comment]
I wonder if this would be more appropriate for [shell-extras](http://swcarpentry.github.io/shell-extras/). I'm kind of dubious as to whether many learners would use this regularly in their workflow. (For me, it's the kind of thing I need to do once in a blue moon, and need to google the syntax for every time. I always forget whether it's `2>`, or `>2`, and get it confused with the ampersand syntax.)

I almost wonder whether we should cut the one paragraph we do have on stderr entirely. Afaik, it never comes up in any of the examples or exercises.

If we are going to talk about stderr, I wonder if we could do so using an example that forces the subject. Like, we run a command, and redirect its output to a file, but we still see some stuff printed to the terminal - what the heck?

**Comment by bagustris** [comment]
I agree to include this (stderr) for shell-extras. However, not only stderr, but also the concept of stdin and stdout should be introduced thereafter learning pipe. A good example that can be adopted is shown [here](https://github.com/kennyyu/bootcamp-unix/wiki/stdin,-stdout,-stderr,-and-pipes).

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen for discussion.
