### ISSUE TITLE
rename `master repository` in CONTRIBUTING

### ISSUE THREAD

**Issue by marwahaha** [swcarpentry/shell-novice#738]
`master repository` feels overloaded, since typically `master` refers to a branch name. I would love to rename it to the `swcarpentry repository` or the `originating repository` so it's clear to fork from `gh-pages`.

**Comment by gdevenyi** [comment]
I think this applies to SWC-styles repo

**Comment by gdevenyi** [comment]
@rgaiacs?

**Comment by rgaiacs** [comment]
@marwahaha this is a good suggestion.

> I think this applies to SWC-styles repo

Yes. See https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py#L18

I created https://github.com/swcarpentry/styles/issues/215 to keep track of this. Feel free to close this for now.

**Comment by gdevenyi** [comment]
Thanks.
