### ISSUE TITLE
Using Wildcards Challenge

### ISSUE THREAD

**Issue by goldmj** [swcarpentry/shell-novice#741]
The Unix Shell Episode: Pipes and Filters

In the Using Wildcards Challenge, I believe the **explanation** for example `1.` is incomplete or could have a clearer explaination?

1. `ls *t*ane.pdb`

`1.` shows all files that contain any number and combination of characters, followed by the letter `t`, another single character, and end with `ane.pdb`. This includes `octane.pdb` and `pentane.pdb`.

The text **another single character** does not fit the description for the wildcard `*`,  instead would be depicted as `?`. Since `*` matches zero or more characters (or **any number and combination of characters** as stated for the first `*`), this command would return `ethane.pdb` and `methane.pdb`, but also (as given) `octane.pdb` and `pentane.pdb`.

**Comment by gcapes** [comment]
Well spotted. I can submit a PR unless someone else is working on it already?

While we're rewording the explanations, I'm not sure that the current rephrasing of 
>zero or more characters

as
>any number and combination of characters

is particularly useful.

So I would propose something like
> zero or more characters followed by the letter `t`, followed by zero or more characters, followed by `ane.pdb`.
