### ISSUE TITLE
No mention of filename capitalization

### ISSUE THREAD

**Issue by navjotk** [swcarpentry/shell-novice#742]
The fact that capitalization of filenames is relevant on some platforms (e.g. Linux) but not on others (e.g. Windows/Mac) is not mentioned clearly anywhere. This could possibly be introduced either at the same time as the [capitalization of commands](http://swcarpentry.github.io/shell-novice/01-intro/) or when the filesystem is [being explored in detail](http://swcarpentry.github.io/shell-novice/02-filedir/).

**Comment by colinmorris** [comment]
FYI, #736 deals with a very similar topic.

**Comment by deppen8** [comment]
Closing in favor of #736
