### ISSUE TITLE
Episode 02-filedir: whoami not defined but listed as key point

### ISSUE THREAD

**Issue by abbiepopa** [swcarpentry/shell-novice#752]
In episode 02 (Navigating Files and Directories) the command "whoami" is listed as a key point, but isn't discussed anywhere earlier in the lesson. It seems odd to me for something to be introduced for the first time in a key point, also since users haven't been discussed in too much detail it might not be obvious to a novice what this command does. Perhaps it should be defined earlier, or removed from key points?

**Comment by gcapes** [comment]
Good catch! The early episodes have been rewritten and reordered slightly recently, so this will be a result of that.
