### ISSUE TITLE
Links to V4 lesson

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#758]
@katrinleinweber wrote

> Dear @gdevenyi, what's the status of this v4 site? https://github.com/swcarpentry/v4 seems abandoned. Over in swcarpentry/r-novice-inflammation#337 we are discussion referring to it anyway. Do you consider that advisable? Thanks for any hints here :-)

[here](https://github.com/swcarpentry/shell-novice/commit/13f6874d20bf0c50abb7a5c2c208e66ff5a4fb6c#commitcomment-28365817). I think the comment didn't get enough visibility so I'm creating a issue for it.

**Comment by gdevenyi** [comment]
v4 is "archived" but its the only place with regex still present.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
