### ISSUE TITLE
Acronym CLI not defined

### ISSUE THREAD

**Issue by ocereceda** [swcarpentry/shell-novice#759]
The CLI acronym in the "Introducing the Shell" section is not defined in the notes

> Is it difficult?
It isn’t difficult, but it is a different model of interacting than a GUI, and that will take some effort - and some time - to learn. A GUI presents you with choices and you select one. With a CLI the choices are combinations of commands and parameters, more like words in a language than buttons on a screen. They are not presented to you so you must learn a few, like learning some vocabulary in a new language. But a small number of commands gets you a long way, and we’ll cover those essential few today.

I would change the text to:

Is it difficult?
It isn’t difficult, but it is a different model of interacting than a GUI, and that will take some effort - and some time - to learn. A GUI presents you with choices and you select one. With a **command line interface** (CLI) the choices are combinations of commands and parameters, more like words in a language than buttons on a screen. They are not presented to you so you must learn a few, like learning some vocabulary in a new language. But a small number of commands gets you a long way, and we’ll cover those essential few today.

**Comment by B-Souty** [comment]
The expansion of CLI is already given earlier in the same document, in the Background section, I would suggest adding "(CLI)" there instead.

> This is what the shell provides - a simple language and a command-line interface to use it through.

I would change the text to:

"This is what the shell provides - a simple language and a command line interface (CLI) to use it through."

**Comment by rgaiacs** [comment]
swcarpentry/shell-novice#781 fixes this issue. Sorry that I wrote the pull request before see the issue.

**Comment by deppen8** [comment]
Looks resolved. Closing as part of old issue cleanup.
