### ISSUE TITLE
Misleading objectives in "working with files and directories"

### ISSUE THREAD

**Issue by ollisollie** [swcarpentry/shell-novice#760]
the objectives in the "Working with files and directories" lesson are:

> Objectives
> - Create a directory hierarchy that matches a given diagram.
> - Create files in that hierarchy using an editor or by copying and renaming existing files.
> - Delete specified files and/or directories.

The second objective indicates that during the lesson we are going to create files by using an editor or by copying and renaming. This is misleading as it does not indicate that the students will learn how to simply copy and move files without renaming them. Besides, the objectives do not mention anything about **moving** files.

I would rewrite the objectives as:

Objectives
Create a directory hierarchy that matches a given diagram.
Create files in that hierarchy using an editor or by copying and renaming existing files.
**Delete, copy and move specified files and/or directories.**

**Comment by darkrepetition** [comment]
Agreed, we touched on this point in our recent Carpentries Instructor Training: the learning objectives were not as clear for this lesson as for other lessons. I would like to use this lesson in the future. The third objective addresses all components of this lesson and would help clarifying expectations for learners.

**Comment by reid-a** [comment]
I think this can be a fairly subtle issue. 

I recently had a chance to assist with instruction of this lesson, and something that came up was the distinction between file _names_ and file _paths_ . Moving a file always changes the path somehow, but may not change the basename, e.g. if you move /path/to/foo to another directory, /new/path/to/foo.

Obviously there is also some tension between brevity and precision in the lesson objectives, which are necessarily a summary.

I think olliesollie's proposed rewrite is a good step.

**Comment by gdevenyi** [comment]
Fixed by #819
