### ISSUE TITLE
Wildcards shown at end of episode 3 but not introduced until episode 4

### ISSUE THREAD

**Issue by colinsauze** [swcarpentry/shell-novice#763]
The last quiz in episode 3 ("Copy a folder structure sans files") uses the * wildcard and asks what commands that use it do. But the concept of the * wildcard isn't taught until the start of episode 4. 

Its not easy to discover what * means through man pages or --help on any command and as far as I can tell the learners aren't supposed to be running these commands themselves on the data-shell directory? 

It would be best to move this question into episode 4 or change it to not use wildcards.

**Comment by colinmorris** [comment]
This is indeed pretty bad! We already have an issue tracking this in #699, so I'm going to close this in favour of that one.
