### ISSUE TITLE
Single quote vs Double quote

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#787]
The lesson has

> Let’s go into that directory with cd and run the command wc *.pdb. wc is the “word count” command: it counts the number of lines, words, and characters in files.

and

> On the other hand, p*.pdb only matches pentane.pdb and propane.pdb, because the ‘p’ at the front only matches filenames that begin with the letter ‘p’.

The "New Oxford Style Manual" says 

> People writing for the Internet should note that single quotation marks are regarded as easier to read on a screen than double ones. British practice is normally to enclose quotation marks, and to use double quotation marks for a quotation within a quotation:
>
> > 'Have you any idea,' he said, 'what "red mercury" is?'
>
> The order is often reversed in newspapers, and uniformly in US practice:
>
> > "Have you any idea," he sad, "what 'red mercury' is?"

@swcarpentry/shell-maintainers Can we define the style that we will going to use?

**Comment by gcapes** [comment]
Let's go with https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html#quotation-marks

i.e.  default to single quotes
