### ISSUE TITLE
Improve fill in the blanks questions

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#788]
I don't like how the "fill in the blanks" type of question is render.

![screenshot from 2018-05-10 16-47-35](https://user-images.githubusercontent.com/1506457/39879096-e27b8f4e-5471-11e8-9660-a87e7c0b06ca.png)

The use of `____` as the blank is not 100% clear to me. I would prefer to have something like

![screenshot from 2018-05-10 16-44-17](https://user-images.githubusercontent.com/1506457/39879138-f3fd014e-5471-11e8-918c-7a399367bd72.png)

In the previous screenshot, I have `<input>` to make clear to the reader were are the blanks. The limitation is that we can't use

```
$ cat sample.md 
> ~~~
> $ cp <input></input> .
> ~~~
````

since

````
$ kramdown sample.md 
<blockquote>
  <pre><code>$ cp &lt;input&gt;&lt;/input&gt; .
</code></pre>
</blockquote>
````

And I don't know of any way to tell kramdown to escape the HTML tags. I would like to suggest to use `&#9617;&#9617;&#9617;&#9617;` instead of `____` to represent the blanks.

![screenshot from 2018-05-10 17-10-46](https://user-images.githubusercontent.com/1506457/39880263-2557b312-5475-11e8-9e96-faf258dcee3a.png)

I know that the rendering doesn't look like blanks but is the [UTF-8 block elements](https://www.w3schools.com/charsets/ref_utf_block.asp that I found more suitable. We can reword the exercise to "fill the shade" instead of "fill the blanks".

**Comment by rgaiacs** [comment]
@ErinBecker what do you think about this from the pedagogical point of view?

**Comment by gcapes** [comment]
I've taught the lesson several times and it's always been clear to the learners. I think adding `&#9617` to the .md files is more confusing, and time consuming if someone wants to add or change a fill in the blanks exercise.


See here [google image results for fill in the blanks](https://www.google.co.uk/search?q=fill+in+the+blanks&num=20&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjfhoK3kP3aAhUED8AKHZ75ArAQ_AUICigB&biw=1920&bih=962) --- they're all lines (underscores).

So sorry, but this is a very strong vote against the change.
