### ISSUE TITLE
Ep3: Filesystem clarification for "More on Wildcards" exercise

### ISSUE THREAD

**Issue by nscatlin** [swcarpentry/shell-novice#793]
http://swcarpentry.github.io/shell-novice/03-create/index.html#more-on-wildcards

I think the exercise titled "More on Wildcards" could benefit from showing a filesystem diagram similar to the one found in "Relative Path Resolution" in Unix Shell: Navigating Files and Directories (Image found here:https://github.com/swcarpentry/shell-novice/blob/gh-pages/fig/filesystem-challenge.svg).

The exercise shows files within a current working directory and asks students how to use wildcards to cp files to other directories.  However, I think students might benefit from being reminded how the filesystem hierarchy looks.  This might, therefore improve their reasoning for copying files in their explicitly stated destination directories.

Another improvement could be to show the filesystem changes after the files are copied to a new directory for each scenario in the "Solutions" section.

**Comment by gcapes** [comment]
Great idea! Would you like to make a pull request?

**Comment by ChaochihL** [comment]
I don't have a diagram to add, but I have a suggestion. I think this exercise could benefit from having a directory (that is part of the data-shell example dataset) containing the files shown in the exercise. That way learners can come up with a possible solution and test out/confirm their guesses.

**Comment by gcapes** [comment]
I like both these suggestions, but the exercise would need to be changed to accommodate them. Currently the exercise assumes all the destination directories exist. For this to be runnable, we would need to create the files and destination directories.

There have been various discussions recently about reorganising the files this lesson uses e.g. #802 and I would be keen to have the discussion there about adding new files to the download.

Nonetheless we could modify the existing exercise to add a tree diagram to clarify the intent. I'll submit a PR for that.
