### ISSUE TITLE
03-create "Using rm Safely" removes a file we have not created

### ISSUE THREAD

**Issue by primerano** [swcarpentry/shell-novice#794]
At the point that this challenge is given the thesis directory has been removed and creating quotations.txt is a few steps away

Using rm Safely
What happens when we type rm -i thesis/quotations.txt? Why would we want this protection when using rm?

Rather than depend on the order we could change the lesson to have them create a file and try to remove it with rm -i.

Maybe something like
---------------
Using rm Safely

Let's create a file called delete_me.txt

touch delete_me.txt 

What happens when we type rm -i delete_me.txt? Why would we want this protection when using rm?

--------------

Thoughts?

**Comment by gcapes** [comment]
Good idea! The exercise should certainly be do-able at the place it appears in the lesson, and if it's independent of position, then so much the better.
