### ISSUE TITLE
Episode 1: "capitalization matters" is not true

### ISSUE THREAD

**Issue by loz-hurst** [swcarpentry/shell-novice#796]
> Also, capitalization matters: LS is different to ls.

This depends entirely on the filesystem being used, and whether that is case sensitive.  This is not true by default on Mac OS, for example (which actually is a Unix, Linux is not):

```
$ ls
data-shell
$ LS
data-shell
$ Ls
data-shell
$ lS
data-shell
$ which ls
/bin/ls
$ which LS
/bin/LS
$ ls -l /bin/ | grep -i ls
-rwxr-xr-x  1 root  wheel    38688 19 Jan 07:37 ls
```
(note: there is only 1 `ls` binary but it can be accessed via any capitalisation)

I intend to address this by adding the words "can" and "usually".

**Comment by r-barnes** [comment]
But capitalization does matter in file names, &c, and on other platforms. So the point that capitalization matters should be retained because, in most situations, it does.

**Comment by rgaiacs** [comment]
> This depends entirely on the filesystem being used

This is true but our lesson are guided by how we could provide the minimal amount of information to learners that will maximise their experience outside of the classroom and in most cases this means that we will be guided by the small denominator to the point that sometimes we will lie to learners. This is one of this cases. We could say

> If you are using macOS, capitalization does **not** matters. If you are using any distribution of Linux, capitalization does matter. But be careful if you are using macOS and ssh into a Linux machine or scp one file to a Linux machine because in that case capitalization does matter.

But all the if-clauses would just confuse learners.

@loz-hurst Thanks very much for the issue and the suggest to address it by adding the words "can" and "usually" but we will keep the simple form.
