### ISSUE TITLE
Episode 7: find-file-tree.svg is illegible

### ISSUE THREAD

**Issue by ddietz89** [swcarpentry/shell-novice#808]
The file structure graphic is illegible for the `find` diagram. I have to zoom in several times to be able to read the leafs on the tree.

**Comment by lxvii** [comment]
It looks like @cekees resolved this issue (#808) by amendment #816 but it is still showing as open

**Comment by gcapes** [comment]
That PR was closed without merging. I'll fix it in a new PR.
