### ISSUE TITLE
Code Boxes

### ISSUE THREAD

**Issue by jv2575** [swcarpentry/shell-novice#817]
Just  a suggestion. Perhaps keep the command and output in the same code box?

**Comment by iamc** [comment]
Keeping them separated makes it clear the logic of what is the input and what is the output. Furthermore as we have different colors for error messages.

However, I think the lateral colors for the in/out boxes are too similar and can be easily confused, and also cause problems for even slightly color-blinded people.

**Comment by rgaiacs** [comment]
Thanks for the contribution. I'm closing this in favour of https://github.com/carpentries/styles/issues/335 since this is a issue that cover all the lessons.
