### ISSUE TITLE
"All in one page" page is broken

### ISSUE THREAD

**Issue by remram44** [swcarpentry/shell-novice#818]
http://swcarpentry.github.io/shell-novice/aio.html

**Comment by remram44** [comment]
You can probably do something like this to fix the "reference" and "setup" pages: https://github.com/swcarpentry/sql-novice-survey/commit/ac32f40eff1d261df9a43d5631070c4c840f0cd0 (then you need to update the links)

**Comment by rgaiacs** [comment]
Thanks @remram44 to provide the solution during my time at EuroPython.

**Comment by gcapes** [comment]
That's done the job. Thanks!

**Comment by gcapes** [comment]
This looks to have been fixed now, so this issue can be closed.
