### ISSUE TITLE
Addition of contact information of senior instructors or video clips of well run workshops in instructor notes.

### ISSUE THREAD

**Issue by ca2783** [swcarpentry/shell-novice#822]
Maybe having a hyperlink to more senior instructor contact information or video clips of well run workshops placed in the instructor notes sections.  Can be helpful for those who feel like they need to hear from more experienced instructors on things that worked for them and things that didn't.  The video clips can help enforce how best to run a workshop with some visuals.

**Comment by deppen8** [comment]
While I think that this would be an interesting resource, it is a bit beyond the scope of this repo.
