### ISSUE TITLE
Has anyone considered using MobaXterm as a replacement for putty/bash etc.?

### ISSUE THREAD

**Issue by macklj** [swcarpentry/shell-novice#837]
Please delete the text below before submitting your contribution. 

---

Due to limitations with how a windows user can access the shell my organization has adopted MobaXterm (https://mobaxterm.mobatek.net).  I think it solves many of the frustrations that exist when attempting to use putty/xming/VMs for bash and other UNIX-like endeavors.

---

**Comment by iamc** [comment]
Yes, every time I set up a workshop I think again about it. It has **many** advantages compared against Windows command prompt + git bash. Say, you can have the always missed man pages, install any cygwin package you want, git et al included, and get the many bells and whistles included with it.

Specially if you are accessing remote machines is much more convenient.

The cons: so much functionality may be a bit overwhelming for a first approach to bash, I think it can be intimidating for newcomers. Also, is not OpenSource and it could stop being free anytime.
 
In fact I usually mention it at the end of the bash lesson as the tool to use if they want to proceed further and pass it on the references I provide.

**Comment by rkhyd** [comment]
Yes, Absolutely. MobaXterm is advanced in every way when compared to putty since it has integrated sftp browser for fileuploads and downlods.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen for discussion. I think adding a tool would be a big deal though and would certainly require some input from the curriculum committee.
