### ISSUE TITLE
Advice: Teach rmdir instead of rm -r to novices

### ISSUE THREAD

**Issue by jeremy9959** [swcarpentry/shell-novice#838]
I recommend teaching the commands``` rm``` and ```rmdir``` for handling files and directories, and not teaching novices the ```rm -r``` command.    New users of the shell will benefit from the protection you get from ```rmdir```.   Teaching the two commands also emphasizes the difference between files and directories.

**Comment by jttkim** [comment]
Minimising the risk of frustrating and potentially serious mistakes is surely a good idea, but the protection achieved by hiding the `-r` option to `rm` from novices is bound to be rather short lived, as many will find out about `rm -r` via Google and in stackexchange etc. From this perspective, mentioning `-r` and having that "With Great Power Comes Great Responsibility" callout in episode 3 is a good approach. That way, learners may recognise `rm -r` as a potentially hazardous tool when they encounter it in blogs, forum posts etc., and be less likely to cause themselves grief when experimenting or after somewhat naively adopting it.

As an aside, I would not want to overemphasise the difference between files and directories, as a directory is a special file after all.

**Comment by mellertd** [comment]
Would it make sense to present rmdir as an option, and explain the functional difference?

**Comment by jttkim** [comment]
@mellertd I can't think of any problem to include `rmdir`, other than the usual "too much content". Perhaps mentioning `rmdir` in a callout or exercise would be a way to add that without adding too much additional load.

It is an optional addition, as learners can be left to discover and find out about `rmdir` without putting them at too much risk of making costly mistakes. And if they don't find it, they perhaps don't need it, like myself -- I almost never use it.

**Comment by dvalters** [comment]
This got discussed before in #337, #336, and was removed in PR #384. (I just came across this issue looking for a instructor checkout issue to tackle!)

**Comment by gcapes** [comment]
My thoughts are that this doesn't really add much conceptually - it's just another command, so the *too much content argument* is strong here. The lesson already teaches how to delete both files and directories containing files.

**Comment by jeremy9959** [comment]
I originally opened this issue.  Personally I continue to believe that rm -r is a dangerous command and I don't think it should be taught as standard practices to novices.  But I am clearly in the minority here, so I will accept that judgement and close this issue.
