### ISSUE TITLE
Episode 3: Incorrect wording of learning objectives

### ISSUE THREAD

**Issue by jfuen001** [swcarpentry/shell-novice#839]
Unix Shell: Working with Files and Directories

Within the overview section, it may be useful to either clarify the use of "diagram" in the objective statement  "Create a directory hierarchy that matches a given diagram." this is unclear for learners and is not used throughout the lesson.

**Comment by aihudson** [comment]
Since there don't appear to be any diagrams in this episode, changing the objective to "Create a directory hierarchy" might be more accurate.

**Comment by gcapes** [comment]
Well spotted!

A PR to address this would be welcome!
