### ISSUE TITLE
Add ls -a example 

### ISSUE THREAD

**Issue by solevillar** [swcarpentry/shell-novice#847]
Adding a ls -a example would give the opportunity to explain that . points to the current directory and .. points to the parent directory and will help students understand how to navigate the file system with 
cd ..
./something
etc

**Comment by rgaiacs** [comment]
> Adding a ls -a example

I think we had one and as far as I check we have.

> The special directory `..` doesn't usually show up when we run `ls`.  If we want
> to display it, we can give `ls` the `-a` flag:
>
> ~~~
> $ ls -F -a
> ~~~
> {: .language-bash}
>
> ~~~
> ./   .bash_profile  data/       north-pacific-gyre/  pizza.cfg  thesis/
> ../  creatures/     molecules/  notes.txt            solar.pdf  writing/
> ~~~
> {: .output}
>
> `-a` stands for "show all";

@solevillar Thanks for the issue. Could you expand what you want to change? If the text that we have on episode 02 is good enough, could you close this issue?

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
