### ISSUE TITLE
Representations avaliable for questions.

### ISSUE THREAD

**Issue by smilefreak** [swcarpentry/shell-novice#85]
Hi, 

In my first lesson I put my questions in a R-presentation using Rstudio, and thought it was a  useful way to share the questions I used in my segment. 

The slides are here http://rpubs.com/smilefreak/59680, would this or even gists be useful for individual instructors to share their questions. The reason I suggest this is that scrolling to the challenges section on the webpage seems awkward, and sharing and presentation tools could really be leverage here I feel.

Thanks for your time.

**Comment by jduckles** [comment]
I like this, I would advocate a more generic way of doing this, using just `reveal.js` from a jekyll `_layout` like in the `/swcarpentry/slideshows`.

We might be able to add a `Makefile` target to look for the ` {.challenge}` class headers in each lesson to build the challenge slides from there.

@r-gaia-cs, I think you're the guy who would know what to do here, would it be acceptable to add a `Makefile` entry in `lesson-template` to build challenge slides as described above? Does that break anything? I'll take a stab at biting it off if you don't see any problems.

**Comment by r-gaia-cs** [comment]
> The slides are here http://rpubs.com/smilefreak/59680, would this or even gists be useful for individual instructors to share their questions. The reason I suggest this is that scrolling to the challenges section on the webpage seems awkward, and sharing and presentation tools could really be leverage here I feel.

@smilefreak What I normally do during workshops is write the challenges at the Etherpad (or if there is enough helpers ask one of them to write the challenges at the Etherpad when I explain it).

> would it be acceptable to add a Makefile entry in lesson-template to build challenge slides as described above?

I'm OK with have this entry.

> Does that break anything?

Nope.

> I'll take a stab at biting it off if you don't see any problems.

A good starting point will be https://github.com/r-gaia-cs/swc-lesson-template/tree/core-epub-and-pdf. If you need I can help you starting the changes.

**Comment by jduckles** [comment]
@r-gaia-cs any advice on the best way to extract the `{.challenge}` sections without introducing any dependencies? I'm thinking we'll need markdown or html files with just the `{.challenge}` sections, would it be safe to assume `grep` and/or `sed` or should I go for a python way to extract those?

**Comment by r-gaia-cs** [comment]
> @r-gaia-cs any advice on the best way to extract the `{.challenge}` sections without introducing any dependencies?

Pandoc converts Markdown to JSON and from JSON to what format you want.

Get the challenges is easy, for a start point check
https://github.com/r-gaia-cs/swc-lesson-template/blob/core-port-to-pandoc/tools/validation_helpers.py#L38.

You can loop at the first level of Pandoc AST and save the challenges that will
be send to Pandoc as one JSON.

**Comment by smilefreak** [comment]
So it seems like the conclusion is to extract challenges from the lessons. Then if you want to customize them for your lesson (e.g put two lessons per challenge section, to give an extension for the smarties), do that privately for your lesson.

Moving ahead then I will endeavour to push my challenges to the relevant repos.

Thanks.
