### ISSUE TITLE
Has anyone considered using linux terminal from microsoft online store, on windows systems?

### ISSUE THREAD

**Issue by davekk** [swcarpentry/shell-novice#851]
https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab

**Comment by gdevenyi** [comment]
Happy to receive a report on if the lesson can be successfully followed in such a environment.

**Comment by vwkoppejan** [comment]
Does this relate to the windows subsystem for linux? I use this a lot, also for swc.

I think most of the unix shell lessons  can be done, git will be challenging due to the file mounting system windows using. I'm currently (as in right now) taking the instructor training. Could this be something I can elaborate upon and use for my checkout?

**Comment by rgaiacs** [comment]
As far as I know, it only works in Windows 10 and many people are still using Windows 8 (need reference).

**Comment by vwkoppejan** [comment]
That's correct, wsl has been introduced as part of the windows 10, see below:

https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

**Comment by gdevenyi** [comment]
So, I'll rephrase the question slightly. Does the Windows 10 subsystem for linux have a low enough barrier to install, and have all the tools to go through a workshop? If it does, we can add it as an option for people to use.

I'm window-less since Steam released Proton so I can't test.

**Comment by vwkoppejan** [comment]
From the top of my head (needs references):

- You need admin rights to enable developer options in the windows settings which 
- You need the app store enabled (often not the case if the device is managed by a large ict organization). If not you can use power-shell
- Installing a linux distribution like ubuntu, suse or debian is pretty easy if you install it as an app.
- X support can be done using mobaxterm or paid software like x410.

It might not be something you want to handle on the morning of a workshop. Also, as I said earlier, the use of git in wsl has some very rough edges.

**Comment by trapido** [comment]
Here is my experience with Linux subsystem on Windows 10:

- Installation:
I followed the instructions from one of the [referenced sources](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10). The first part worked, but running bash.exe produced the following error: “Windows subsystem for Linux has no installed distributions”, so I had to install Ubuntu from the Microsoft Store.

- Exercises:
I think one of the biggest challenges for a novice shell user will be to figure out how to move between Linux and Windows file systems (this is explained in "[Install and Use the Linux Bash Shell on Windows 10](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)" and "[Using the Windows 10 Bash Shell](https://www.howtogeek.com/265900/everything-you-can-do-with-windows-10s-new-bash-shell/)" references, but both assume prior knowledge of Unix shell and seem too detailed).  I ended up copying the “data-shell” directory from Windows Desktop to my Linux home directory, which I think might be the easiest option. I did all the exercises and did not encounter any other issues.

- Conclusion:

Linux on Windows10 is a valid option and helps avoid some of the quirks of Git Bash on Windows. However, installation is complicated and the instructions are interspersed between several documents. I provided my steps below, if you think that might be helpful to share: 

1. Follow the steps in [this document](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10) (Note: you should have the administrator rights).
2. If you get an error when running bash.exe, go to [Microsoft App Store](https://www.microsoft.com/en-us/store/apps) and install Ubuntu from Canonical.
3. Once the installation is complete, create a default UNIX user account (i.e., enter the user name you would like to use).
4.	Enter the following commands:
$cd 
$cp -r /mnt/c/Users/<your_username>/Desktop/data-shell .

To open a terminal, run Ubuntu from the Windows start menu.

**Comment by vwkoppejan** [comment]
I still think there will be some challenges for the git lessons. 

git on wsl does not deal well with mounted file systems., see wsl issues [184](https://github.com/Microsoft/WSL/issues/184) and [2900](https://github.com/Microsoft/WSL/issues/2900) 

This is not a problem if wsl users clone a repo in their linux homes folder (or a path relative to it) but it might be if they copy a downloaded repo from another drive on their computer.

There are of course ways to fix the issues if they pop up but I think the offered solutions distract the users from the learning objectives of the lesson and might give them the wrong idea about git being very technical etc.

**Comment by gdevenyi** [comment]
Thanks @vwkoppejan and @trapido for the feedback. I think at this point WSL isn't ready for use in SWC. We will close this for now. Feel free to reopen if there is major movement on this front.
