### ISSUE TITLE
Expand content on other shells in episode 1

### ISSUE THREAD

**Issue by jtande** [swcarpentry/shell-novice#852]
The material is great and I thank all the contributors working on this project. Going through the introduction.
I feel we could improve this section of episode 1 that describes the shell. below is my suggestion:

The Shell
There are many Unix  shells of which the most popular is Bash, the Bourne Again SHell (so-called because it’s derived from a shell written by Stephen Bourne). Bash is the default shell on most modern implementations of Unix and in most packages that provide Unix-like tools for Windows. Issue the following  commands:
 echo $SHELL  ,  this returns the location of the default shell on your computer
echo  $0  , (0 is the numeral zero) this returns the shell currently running.
To start a particular shell, type its name at the command line. Type bash, for example, to start the bash shell.

The reason for this change is that quite often beginners start likely with the bash shell and when they
logon to a computer with a different default shell, they are confused. Knowing how to find a default shell, 
the current shell and switching shells is an important first step. I compare this to learning how to run an application . You need to know where to find the application, how to start it and also how to exit.

**Comment by colinmorris** [comment]
> The reason for this change is that quite often beginners start likely with the bash shell and when they
logon to a computer with a different default shell, they are confused

Do you think this is a common issue?

I would be reluctant to make this change because these would be the first shell commands learners would see, and they involve some magic that we would have to brush under the rug (what is "echo"? What does the dollar sign mean? Don't worry about it, we'll explain that stuff in a couple hours).

**Comment by gdevenyi** [comment]
Hi @jtande, thanks for opening these discussions.

I'm -1 for making these changes

The default shell on debian/*buntu/centos/redhat/osx is bash, other shells are pretty rare unless explicitly enabled by a user. This would add a lot of up-front complication and bring up questions that we might never answer (what are the differences between shells, why are there different ones, etc).

**Comment by gcapes** [comment]
Thanks for the contribution.
Learners have instructions on the required software for the course, so I think preparing them for any shell on any machine is out of scope of this lesson.
