### ISSUE TITLE
Inconsistent usage of head/tail in Episode 4 exercise "Appending Data"

### ISSUE THREAD

**Issue by jtande** [swcarpentry/shell-novice#853]
There was already an issue open about consistency. Thought the example works, it is important to be consistent when dispensing a lesson.

This concerns Episode 4 (Appending Data example, the solution part)
            Option 3 is correct. For option 1 to be correct we would only run
            the head command. For option 2 to be correct we would only run the
            tail command. For option 4 to be correct we would have to pipe the
            output of head into tail -2 by doing  head -3 animals.txt | tail -2>> animalsUpd.txt . 
            Though head -3 and tail -2 will return same output as head -n 2 and tail -n 2 it is 
            inconsistent with the command option argument synopsis that was predefined

**Comment by colinmorris** [comment]
Good catch! It looks like this is the only place where we use the `-#` short form for the `-n` flag. We should change the solution to use `-n` to match the rest of the lesson.

**Comment by gdevenyi** [comment]
This also is relevant for the GNU vs POSIX vs BSD (aka linux vs OSX) problems.

**Comment by gcapes** [comment]
I'm submitting a fix for this, but have another question. What does the new file name mean? >animals**Upd**.txt

**Comment by jtande** [comment]
>animalsUpd.txt this is just a garbage collection file. nothing important about it

**Comment by gcapes** [comment]
Thanks - I'll start a new issue for further discussion.
