### ISSUE TITLE
hollybik suggested improvements (and one typo) - Instructor Checkout

### ISSUE THREAD

**Issue by hollybik** [swcarpentry/shell-novice#854]
## Possible confusion with 'ls' command

The first few unix shell lesson subsections switch between `ls` and `ls -F` without ever really explaining why. Furthermore, the longer command `ls -F` is never fully explained (and the man page for ls doesn't provide helpful information on what this flag is doing in case users are trying to figure it out on their own). Issue #846 has raised this same point. 

## Typo in "Loops" subsection

If you type '>' or '$' yourself, it is an instruction from you that the shell to redirect output or get the value of a variable.

fix to read as: 
If you type '>' or '$' yourself, it is an instruction from you that the shell *should* redirect output or get the value of a variable.

## Increasing prominence of core command line navigation skills

Tab completion, moving around a line using 'Ctrl-a' and 'Ctrl-e', and using up/down arrow to view previous commands are three important concepts, but currently they are all buried in the middle of different Unix Shell sections. You have to read the lesson very carefully or you will miss the brief mention of these concepts. I would consider moving these skills up to the first "introducing the shell" section, since these are important core concepts. At minimum, I think they would be better covered up front at the beginning of one of the unix lesson subsections, and highlighted in a "key points" colored text box. Based on my workshop teaching experience, this is something that beginning command line users often get very confused about, and it benefits their confidence/skills to introduce these navigational tips early on in a workshop.

## Minor edits to "Finding things" subsection

In the "Finding things" subsection, there could be a quick reminder to `cd data-shell/writing` before running the `find` commands. After the `grep` exercises, users are likely to be in another directory or subdirectory.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by gcapes** [comment]
Thanks for the contribution!

There are some good ideas in here - could you please close this issue, and create new issues for each separate point? That would make it easier to discuss and create PRs for each idea.

Thanks!

**Comment by hollybik** [comment]
No problem - closing and making 4 separate issues, as requested.
