### ISSUE TITLE
Episode 5: Loops - suggested edit - Instructor checkout

### ISSUE THREAD

**Issue by jburkemhc** [swcarpentry/shell-novice#861]
Thanks for all your work making such great lessons for us!
In the section, "Doing a Dry Run", I think there is some confusion introduced (there was for me) in using the command 'analyze' in the text and in the exercise because 'analyze' is not an actual Unix command.  I think it would be clearer to use an actual Unix command or command set.  When the student opens one of the analyzed-*.pdb files after Version 1 in the exercise, the file is empty but it is not clear why.  
Thanks! And sorry if I'm missing something important here...

**Comment by gcapes** [comment]
Great issue, thanks!

This refers to this exercise: http://swcarpentry.github.io/shell-novice/05-loop/index.html#doing-a-dry-run

The exercise suggests trying both loops, but they aren't runnable as-is because `analyze` doesn't exist. I'm a bit stuck to think of a substitute set of commands right now but we should figure something out and make it runnable.

**Comment by speleolinux** [comment]
Hi all
Here is my suggestion for this issue.
Currently in this exercise we have:

    # Version 1
    $ for file in *.pdb 
    > do
    >   echo analyze $file > analyzed-$file
    > done

    # Version 2
    $ for file in *.pdb
    > do
    >   echo "analyze $file > analyzed-$file"
    > done

I would suggest this:

    # Version 1
    $ for datafile in *.pdb
    > do 
    >   echo cat $datafile >> all.pdb 
    > done

    # Version 2
    $ for datafile in *.pdb
    > do 
    >   echo "cat $datafile >> all.pdb"
    > done

Rationale: 

In the section "Saving to a File in a Loop - Part Two" we already have the example where we use the command: `cat $datafile >> all.pdb` so we are not introducing any new commands or concepts. We are reusing recent examples. 

Version 1 will not produce any screen output so it won't help Nelle to check that the command she wants to run is correct. In the file "all.pbd" she would have:

    cat aldrin.pdb
    cat ammonia.pdb
    ....

Version 2 will produce the following screen output:

    cat aldrin.pdb >> all.pdb
    cat ammonia.pdb >> all.pdb
    ....

This confirms to her that the commands that would run without the echo are correct. She would then run:
 
    $ for datafile in *.pdb
    > do 
    >   cat $datafile >> all.pdb
    > done

And the file all.pdb will contain a concatenation of all the PDB files.

**Comment by gcapes** [comment]
That looks great @speleolinux!
Any chance of a PR? :)

**Comment by speleolinux** [comment]
Hi

Yep, will do tomorrow when at work.

Mike Lake
eResearch UTS
9514 2238 (w)

________________________________________

**Comment by speleolinux** [comment]
PR is here https://github.com/swcarpentry/shell-novice/pull/1090

________________________________________
