### ISSUE TITLE
Better explanation of 'cut' command in Pipes and Filters session

### ISSUE THREAD

**Issue by JeanShuler** [swcarpentry/shell-novice#868]
Better explanation of cut command recommended and the cut command was not introduced prior to using it.  

---
In the cut -d , -f 2 animals.txt example there should be a better explanation of the "d" and -'f" option.
The cut command is used to cut sections from each line of files and then write the results to standard output. 
the 'd' option is  a delimiter so the comma (,) is the delimiter
the 'f' option is the 'field number" so the number 2 is the field number.

---

**Comment by hannahburkhardt** [comment]
First reported in #608
