### ISSUE TITLE
Include a non-.pdb file in 'molecules' directory to better illustrate behaviour of wildcard in wc *.pdb  

### ISSUE THREAD

**Issue by i-brnrd** [swcarpentry/shell-novice#869]
In 'Pipes & Filters'; one of the first tasks performed (after navigating to the 'molecules' directory) is wc *.pdb. 
As the previous lesson ends with Wildcards, it might be good to include another file within 'molecules' with different file type, to further illustrate the wildcard behaviour of *.pdb (and to avoid any confusion between this and *.*) 

**For instructor training**

**Comment by gcapes** [comment]
Thanks for the issue.
What would be the narrative for including a different file type - i.e. how does it fit into the 'story' of this example?
>  (and to avoid any confusion between this and .)

I'm sorry, I don't follow. Could you explain what the confusion would be?

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for discussing this, we can reopen.
