### ISSUE TITLE
Lesson 03-create needs sections

### ISSUE THREAD

**Issue by DSLituiev** [swcarpentry/shell-novice#879]
The first lesson has clear markdown headers, but [lesson 3](https://swcarpentry.github.io/shell-novice/03-create/index.html) does not. I suggest one can add headers to help navigating the content, e.g.:

```
# Creating files and directories
## See where we are
## Create a directory
## Creating text files
# Removing files and directories
# Moving files and directories
# Copying files and directories
# Operations with multiple files and directories
```

**Comment by colinmorris** [comment]
Fixed in #880. Thanks!

Though this made me realize that lessons 2, 4, 5, 6, and 7 also have no section headers (except one at the end for "Nelle's pipeline"). It could be worth updating those lessons in the same way.
