### ISSUE TITLE
small change between files/directories and creating things

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/shell-novice#88]
Per PR #82, any strong opinions about moving the note about `~` from 02-creating things to 01-files and dirs?  In my mind, that's the logical place for it since that's where we discuss paths.  On the other, 01 already has a lot going on and the `~` note might just be distracting.  Thoughts?

**Comment by gvwilson** [comment]
I think 01 is already crowded enough.

**Comment by TomKellyGenetics** [comment]
I think the coverage of ~ dir in 02 is sufficient. I was just making sure it's covered so participants understand what we're doing because I often use 'cd ~' when helping in workshops. When it's covered is simply a matter of preference for instructors.
