### ISSUE TITLE
Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/shell-novice#882]
Lesson: The Unix shell - loop lesson (05)
Position: At the end of the lesson.
Title of the new section: Saving time in the future
Text body: As far as we came with our scripting using shell, we may end up writing complex commands containing loops, pipes, etc. In order to save time, we would like to be able to retrieve one of the complex commands we already executed quickly. To do so, we can add a configuration of our system so that we only have to start typing the complex command and be able to complete it using the up/down arrow keys. This configuration should be added to the ~/.bashrc file.
Commands:
$ cd
$ nano .inputrc
Then add the following lines to your .bachrc file:
"\e[A": history-search-backward
"\e[B": history-search-forward
Close the file after saving the changes.
After you modified your ~/.inputrc , restart your shell
Test your up/down arrows

**Comment by sheraaron** [comment]
Correction Made. See below


Lesson: The Unix shell - loop lesson (05)
Position: At the end of the lesson.
Title of the new section: Saving time in the future
Text body: As far as we came with our scripting using shell, we may end up writing complex commands containing loops, pipes, etc. In order to save time, we would like to be able to retrieve one of the complex commands we already executed quickly. To do so, we can add a configuration of our system so that we only have to start typing the complex command and be able to complete it using the up/down arrow keys. This configuration should be added to the ~/.inputrc file.
Commands:
$ cd
$ nano .inputrc
Then add the following lines to your .inputrc file:
"\e[A": history-search-backward
"\e[B": history-search-forward
Close the file after saving the changes.
After you modified your ~/.inputrc , restart your shell
Test your up/down arrows

**Comment by gcapes** [comment]
Hi Sher,

Thanks for the contribution.

This looks to be a slight variation on an idea which is already covered in the **Other History Commands** callout
>Ctrl-R enters a history search mode “reverse-i-search” and finds the most recent command in your history that matches the text you enter next. Press Ctrl-R one or more additional times to search for earlier matches.

So great minds think alike :)

Thanks again.
