### ISSUE TITLE
Episode 2: incomplete solution to 'Listing recursively and by time'

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#892]
http://swcarpentry.github.io/shell-novice/02-filedir/index.html#listing-recursively-and-by-time

This was originally raised in #575.

>The directories are listed alphabetically at each level. The files/directories
in each directory are sorted by time of last change.

**Comment by fthommen** [comment]
> The directories are listed alphabetically at each level. The files/directories
>  in each directory are sorted by time of last change.

I might just not understand this (language wise) or then I cannot confirm this finding.  I find: Files and directories are sorted by time of last change at  and in each level.  Items with the same modification time are sorted alphabetically.

**Comment by gdevenyi** [comment]
+1 to @fthommen's finding.

**Comment by sstevens2** [comment]
I think this exercise is confusing.  Using the `-R` flag leaves some users sitting there while a bunch of files and folders print to the screen for a long time.  This also makes it difficult to compare with and without the `-t` option. @lmichael107 might be able to say more.
I vote we switch it to `-r` and learners can see that it reverses the order which is very useful.

**Comment by gcapes** [comment]
I think this is a great suggestion, and would welcome a PR to modify the exercise to include the `-r` option instead of `-R`.

**Comment by gcapes** [comment]
Fixed in #1038
