### ISSUE TITLE
Episode 7 "Finding Files With Different Properties" exercise too difficult/obscure?

### ISSUE THREAD

**Issue by colinmorris** [swcarpentry/shell-novice#893]
For reference, here's the question:

> The `find` command can be given several other criteria known as “tests” to locate files with specific attributes, such as creation time, size, permissions, or ownership. Use `man find` to explore these, and then write a single command to find all files in or below the current directory that were modified by the user `ahmed` in the last 24 hours.  
Hint 1: you will need to use three tests: `-type`, `-mtime`, and `-user`.  
Hint 2: The value for `-mtime` will need to be negative—why?

### Issue 1: I think this is too hard

I timed myself solving this problem, and it took me about 6 minutes. (For reference, the total exercise time for episode 7 is given as 20 minutes, and it has 6 exercises)

Most of that time was spent trying to figure out the modification time test through reading the man page and trial and error. `find`'s time-based tests are quite subtle, and figuring out the solution requires more than just reading the `-mtime` entry in the man page. That entry directs us to "See the comments for -atime", and from there, if you're lucky, you'll notice the explanation of the syntax/semantics of numeric arguments a few lines above.

### Issue 2: Niche-y

I'm sure I've written thousands of `find` commands in my life, but I don't think I've ever had reason to use the `-user` flag. In fact I can probably count on one hand the number of times I've used tests other than `-name` or `-type`.

In the amount of time this exercise takes, we could probably give the learner a brief introduction to the `-exec` flag which I think is an extremely practical feature by comparison. (Though I'd be just as happy simply removing this exercise without adding a replacement. See #133 and #179 for discussions of whether to include `-exec`.)

**Comment by gcapes** [comment]
I agree this is more of a sys-admin task than a novice shell user would find useful in their research. I would be in favour of simply dropping it without introducing `-exec`, for the reasons above and in the linked PRs.

PR to fix this issue would be welcomed!

**Comment by gdevenyi** [comment]
Link to code line: https://github.com/swcarpentry/shell-novice/blame/gh-pages/_episodes/07-find.md#L660

I agree this is definitely something that should shunt to shell-extras

**Comment by fthommen** [comment]
> I'm sure I've written thousands of find commands in my life, but I don't think I've ever had reason to use the -user flag. In fact I can probably count on one hand the number of times I've used tests other than -name or -type.

I haven't written thousands of find commands, but probably many hundred.  At least 20-30% of them use ``-user`` as for us it is quite common to find files belonging to specific users in a shared filespace.

However you decide on this, I suggest _not_ to introduce ``-exec``.  This option is too complex for novice users at the very end of a looong  day full of new concepts and commands ;-).

See also #952 regarding this exercise.

**Comment by mhamilt** [comment]
I still don't actually understand _Hint 2: The value for -mtime will need to be negative—why?_

[Explain shell seems to also find it tricky](https://explainshell.com/explain?cmd=find+.%2F+-type+f+-mtime+-1+-user+ahmed). In fact, I can't find any reference to negative number arguments for `-mtime` in the [`find` man page](https://ss64.com/bash/find.html).

At the very least, I don't think this can be classified as a useful hint.

**Comment by fthommen** [comment]
The `find` manpage doesn't mention it explicitely, but since it says `When find figures out how many 24-hour periods ago the file was last accessed, any fractional part is ignored, so to match -atime +1,  a  file  has  to have been accessed at least two days ago.` I find it a plausible analogy, that negative numbers are interpreted as "at most".  This could also be seen as an implicit  exercise showing that manpages can be incomplete, non-explicit and sometimes just wrong.

**Comment by mhamilt** [comment]
I think it may be worthwhile adding some explanatory text to that effect in the [solution](https://github.com/swcarpentry/shell-novice/blob/gh-pages/_episodes/07-find.md#solution-4). From the perspective of a novice, when there is difficulty in connecting a hint to the solution I can see that causing a bit of frustration and perhaps a little demotivating.
