### ISSUE TITLE
Episode 3: Copy folder exercise - poor example to be setting?

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#897]
#890 gave rise to this idea.
Re: `copy a folder structure but not the files`
http://swcarpentry.github.io/shell-novice/03-create/index.html#copy-a-folder-structure-but-not-the-files

I think it's a clunky horrible solution to the problem, and not a great workflow to be recommending -- imagine if there are lots of files to be copied only to then be deleted. How about rewording the question to challenge the learner to recreate the folder structure using `mkdir` commands?

This better matches the learning objective
> Create a directory hierarchy that matches a given diagram.

**Comment by jtande** [comment]
Though, I agree with gcapes, the example as set up does not work the way it is stated.  The way cp -r for a directory and subdirectories is copy the directories including the top most directory. This what a simulation looks like:
$ cp -r dir1 dir2
dir1 -> dir2/dir1
dir1/processed -> dir2/dir1/processed
dir1/processed/file1.txt -> dir2/dir1/processed/file1.txt
dir1/processed/file2.txt -> dir2/dir1/processed/file2.txt
dir1/raw -> dir2/dir1/raw
dir1/raw/file3.txt -> dir2/dir1/raw/file3.txt
dir1/raw/file4.txt -> dir2/dir1/raw/file4.txt

You can see that dir1 is copied first and the rest follows. It will be great if this can be fixed.
Thank you

**Comment by gcapes** [comment]
Thanks for the input @jtande.

However, look closely at your example and compare to the challenge. You have no trailing slash on your `dir1`, which is different to the lesson's example `cp -r dir1/ dir2`, hence the result is different.

**Comment by gdevenyi** [comment]
That is indeed not a great workflow, and rarely needed. I agree with a reword to challenge the mkdir usage.

Perhaps this is a place to intro "mkdir -p"

**Comment by gcapes** [comment]
Great, I'll put in a PR at some point over the next week.
