### ISSUE TITLE
Episode 7: Add reminder which directory to run commands in

### ISSUE THREAD

**Issue by hollybik** [swcarpentry/shell-novice#898]
In the "Finding things" subsection, there could be a quick reminder to `cd data-shell/writing` before running the `find` commands. After the `grep` exercises, users are likely to be in another directory or subdirectory.

(Previously mentioned up in issue #854 as part of instructor checkout - closed and reopened each point as separate issue)

**Comment by gdevenyi** [comment]
Thanks @hollybik for the suggestion! Newcomers and instructor checkout folks, this would be a nice quick contribution.
