### ISSUE TITLE
Increase prominence of core command line navigation skills

### ISSUE THREAD

**Issue by hollybik** [swcarpentry/shell-novice#899]
Tab completion, moving around a line using 'Ctrl-a' and 'Ctrl-e', and using up/down arrow to view previous commands are three important concepts, but currently they are all buried in the middle of different Unix Shell sections. You have to read the lesson very carefully or you will miss the brief mention of these concepts. I would consider moving these skills up to the first "introducing the shell" section, since these are important core concepts. At minimum, I think they would be better covered up front at the beginning of one of the unix lesson subsections, and highlighted in a "key points" colored text box. Based on my workshop teaching experience, this is something that beginning command line users often get very confused about, and it benefits their confidence/skills to introduce these navigational tips early on in a workshop.

(Previously mentioned up in issue #854 as part of instructor checkout - closed and reopened each point as separate issue)

**Comment by gcapes** [comment]
Thanks for the issue.

From experience, plenty of people don't get into the habit of using the tab key for auto-complete, so I would think your extra suggestions with `ctrl-a` and `ctrl-e` would be overload.

As for moving them into one place, I'm unsure about that too. I think it can be useful to have a long-ish command that needs retyping before the utility of using the up arrow to repeat previous commands is apparent.

What does anyone else think?

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for discussion, we can reopen.

**Comment by gdevenyi** [comment]
Merged into #1221
