### ISSUE TITLE
demotivational language

### ISSUE THREAD

**Issue by alancalder** [swcarpentry/shell-novice#909]
The Instructor Notes for the Unix Shell lesson do not meet the Carpentries
standards. Specifically, the paragraph discussing running a text editor

>Running a text editor from the command line can be the biggest stumbling
block during the entire lesson: many will try to run the same editor as
the instructor (which may leave them trapped in the awful nether hell
that is Vim), or will not know how to navigate to the right directory to
save their file, or will run a word processor rather than a plain text
editor. The quickest way past these problems is to have more knowledgeable
learners help those who need it.

has a problem in the realm of violating the Caprentries Code of Conduct
clause "Use welcoming and inclusive language." The parenthetic expression
>(which may leave them trapped in the awful nether hell that is Vim)

is disparaging and demotivational for users of Vim (or vi).

Also, the recommendation 
>The quickest way past these problems is to have
more knowledgeable learners help those who need it

may not be the best solution. Having less-knowledgeable students work with more advanced
students is one option and it may be the quickest way to get the class
moving, but I am not sure that is the most helpful approach. Having very
inexperienced students work with more advanced students is more of a
last resort way of allowing them to get something out of a lesson. I suggest
reconsidering this advice.

The file in question may be found at
https://github.com/swcarpentry/shell-novice/blob/gh-pages/_extras/guide.md

---

**Comment by gcapes** [comment]
Thanks for the issue.

I don't think I've read the guide for this lesson before, but this section certainly falls short in terms of language. 

I think we could replace this bullet point with a note that the instructor should be using the name editor as the learners (i.e. nano) to avoid such problems.
