### ISSUE TITLE
Configure/enable travis for checking PRs

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/shell-novice#911]
As per discussion here https://github.com/carpentries/styles/issues/387#issuecomment-457250459 it seems there's a preconfigured travis in the boilerplate we can enable checks on PRs.

This is a good idea.

**Comment by deppen8** [comment]
Idle thought: I wonder if this could be implemented in GitHub Actions instead.

**Comment by gdevenyi** [comment]
Yes definitely github actions now rather than Travis.

**Comment by fmichonneau** [comment]
The latest version of `styles` does have a GitHub Action that runs `make lesson-check-all` on PRs (and pushes to `gh-pages`): https://github.com/carpentries/styles/blob/gh-pages/.github/workflows/website.yml

I'll open a pull request to bring in these changes for you to review.

**Comment by deppen8** [comment]
I think this one is closed by the combination of #1236 and #1248. Feel free to reopen if you think there is more to add there @gdevenyi .
