### ISSUE TITLE
Ep3: Redundancy between "Using rm Safely" exercise and "With Great Power Comes Great Responsibility"

### ISSUE THREAD

**Issue by colinmorris** [swcarpentry/shell-novice#914]
This was mentioned by gcapes in #832. 

The "With Great Power Comes Great Responsibility" callout box introduces the `rm -i` flag as if it were a new thing, even though it was already introduced in the "Using rm Safely" exercise just a little earlier. 

I think we could consolidate these into one for the sake of brevity. They both cover roughly the same ground. Failing that, we should at least update the wording in "With Great Power" to say something like "once again, we can use the `-i` flag...".

**Comment by gdevenyi** [comment]
@gcapes brings up a good question.

1) Should we introduce new concepts in exercises
2) Should we rely on concepts introduced in an exercise

**Comment by gcapes** [comment]
1.  I don't see why not for something non-essential like this. I wouldn't want to have a key concept as exercise-only
2. No.
