### ISSUE TITLE
Adding clear command and shortcuts

### ISSUE THREAD

**Issue by HarshpreetChandok** [swcarpentry/shell-novice#921]
Hi all,
Adding clear command would be useful for beginners when it becomes little clumsy on the screen to check for commands with few errors here and there. Could also add shortcut Ctrl+L for the same.

Also, to enter the path to the file typically a student would  navigate to the destination folder, type pwd and get the path and then add name of the file. A shortcut could be:
echo $PWD/<filename.txt>
press tab and it would display the entire path with filename. This would reduce the number of steps and would give a chance to implement 2 logics at once. (tab completion, use of $PWD)

**Comment by gcapes** [comment]
Thanks for the contribution @HarshpreetChandok 

These are useful tips, but I think they fall outside the scope of this novice lesson, particularly the shell variables idea, which is in the [shell-extras lesson](http://swcarpentry.github.io/shell-extras/08-environment-variables/).

Thanks again for taking the time to contribute.
