### ISSUE TITLE
Ep2: poor wording referring to figure

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#923]
> Assuming a directory structure as in the above Figure
> (File System for Challenge Questions), if ...

*File System for Challenge Questions* is the name of the image in the markdown, but it's meaningless for navigating the lesson as a learner (or instructor).

I suggest we either reproduce the same figure in the exercise to keep it self-contained, or change the wording to something like
> Assuming a directory structure as in the above Figure
> , if ...

I'm leaning towards just reproducing the figure. What do you think?

**Comment by gdevenyi** [comment]
Easiest to reproduce it inside the box to make it explicit. Since it the same figure, we aren't duplicating files.

**Comment by gcapes** [comment]
Great, I'll send a PR at some point soon.
