### ISSUE TITLE
Best practices vs training

### ISSUE THREAD

**Issue by OH-AU** [swcarpentry/shell-novice#931]
There's a few places in the course that are common training exercise patterns, however in actual practice add extra overhead (this could be split into multiple ticket based on examples but I thought comments could point to other examples if this is considered a valid ticket) - would it be worth a comment suggesting alternative ways of doing things for these sections. Two that spring to mind:
1. sort and uniq - for a simple example; sort already contains a uniq option which for large files will decrease overhead (note that uniq has more features so it's use is still obviously relevant). 
cut -d, -f 2 animals.txt | sort | uniq -c | wc -l
could be
cut -d, -f 2 animals.txt | sort -u | wc -l
(bad example - animals.txt is too small to notice an time difference in sorting)
2. grep - in the solution there's an extra cut to remove the filename - grep can do that for you already.
grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt
could be
grep -h -w $1 -r $2 | cut -d , -f 1,3  > $1.txt

Tested on linux and mac - sort/uniq examples are fine; the grep behaviour in this regard IS different (BSD vs GNU) -  man grep:
mac: Never print filename headers (i.e. filenames) with output lines.
linux (SLES 12SP3): Suppress the prefixing of file names on output.  This is the default when there is only one file (or only standard input) to search.

**Comment by gcapes** [comment]
Hi @OH-AU, and thanks for the issue.

The aim of SWC lessons is to help learners build a better mental model of a subject area rather than necessarily showing the *best* way to achieve a particular task. Here I think practising pipes and filters trumps investigation of the various options to different commands.

We can add the difference in grep behaviour to the discussion at #798

**Comment by gdevenyi** [comment]
Hi,

I agree with @gcapes that there are many cases where there are more efficient methods. In fact, the answer is almost always "awk", but we don't even touch it, because it's the concepts we're trying to get across. Closing in favour of the grep discussion in #798
