### ISSUE TITLE
grep in Little Women (episode 7: Finding Things)

### ISSUE THREAD

**Issue by OH-AU** [swcarpentry/shell-novice#932]
To be ridiculously specific, the grep example in little women does not cover all cases (no pun originally intended) - Jo is mentioned a few extra times in headings as "JO"
A case insensitive search will yield slightly different results - it's arguable whether Titles/Headings should be included.
for sis in Jo Meg Beth Amy; do  echo $sis:;  grep -iow $sis LittleWomen.txt | wc -l; done
Jo:
    1362
Meg:
     686
Beth:
     467
Amy:
     652
for sis in Jo Meg Beth Amy; do  echo $sis:;  grep -ow $sis LittleWomen.txt | wc -l; done
Jo:
    1355
Meg:
     683
Beth:
     459
Amy:
     645
Not sure if either the examples or wording of the exercises should be made clearer.

**Comment by gdevenyi** [comment]
Thanks for catching this.

This might be an interesting extension to discussing the importance of cAPiTALIzation. :)

**Comment by colinmorris** [comment]
Interesting observation! There are already a lot of variables to consider in this question (not counting names if they appear as a substring of a larger word, counting them if they have punctuation or a clitic attached, counting multiple appearances on one line...), so I don't think I'd want to emphasize this as another strict condition for correctness. But could definitely imagine mentioning it in a postscript to the solution. e.g.

> Perceptive observers may have noticed that character names sometimes appear in all-uppercase in chapter titles (e.g. "MEG GOES TO VANITY FAIR"). If you wanted to count these as well, you could add the `-i` option for case-insensitivity. (Though in this case, it doesn't affect the answer to which sister is mentioned most frequently.)
