### ISSUE TITLE
Improving clarity within Script Reading Comprehension 06-script

### ISSUE THREAD

**Issue by hoytpr** [swcarpentry/shell-novice#933]
The Script Reading Comprehension could be interpreted that it wants one script with three parts, rather than three scripts to be written. It would be clearer if it was worded: "Explain what each of the following three scripts would do if they contained the following lines and were run as `Script1.sh *.pdb`, `Script2.sh *.pdb` and `Script3.sh *.pdb`".

**Rationale:** Up to this point in the lesson the learners have been combining scripts with pipes, and it might appear that they are being asked to build another longer script from pipes. In fact, if the three scripts are combined with pipes, they will give the exact answer shown for Script3. Rather than include the output of just the third script, we could present the answers for Script1 and Script2 with the salient learning outcomes.  for example: 

Script1.sh takes the input `*.pdb` but the input is irrelevant to the requested output, so all files with a period in their name are printed out. 

Script2.sh takes the input `*.pdb` and prints out the complete contents of the first three files with .pdb as a suffix (using the default alphabetical order).

Script3.sh uses `$@` to mean “All of the command-line arguments to the shell script.” which takes the input of `*.pdb` and creates a special variable for each file ending in .pdb ($1, $2, $3, $4, $5, $6) and prints them out. 

It then also prints `.pdb` because... ***(I have no idea!)***

**Comment by gcapes** [comment]
Thanks for the issue @hoytpr 
I agree that clarity of the question and standard of the solutions could be improved.

The final `.pdb` printed in script 3 is a distractor.

**Comment by hoytpr** [comment]
Thanks for creating the PR @gcapes! LGTM.
