### ISSUE TITLE
Prefer `option` over `flag`

### ISSUE THREAD

**Issue by drj11** [swcarpentry/shell-novice#938]
The Shell lessons (example, http://swcarpentry.github.io/shell-novice/01-intro/index.html) has the text "some flags (also called options or switches)" and then uses _flag_ throughout.

Not only is _flag_ somewhat historical, [POSIX documents them](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) as «known as "options" (or, historically, "flags")» (and then is not completely consistent in using "options", but mostly so). [had intended to add here: , but a flag can only be present or absent, the common meaning of flag makes nonsense of "flags having arguments"]

There is a lot of varying terminology in this area (flag/option/switch/parameter/etc), but I believe we are in a position to promote terminology that is both standard and existing.

**Comment by gcapes** [comment]
Thanks for the issue. My thoughts are that it is most important to be consistent (hence using one term exclusively after the introduction). I use `flags` hence the current state of the lesson but happy to change to `options` if there is consensus around that.

**Comment by drj11** [comment]
Consensus is great, but the man pages of all the commands mentioned in [the reference](http://swcarpentry.github.io/shell-novice/reference/) use OPTION over FLAG:

    $ for a in bash ls cat mv cp nano mkdir rm; do man $a | head -n 40 ; done | egrep -i -o 'option|flag' | tr A-Z a-z | sort | uniq -c
     39 option

Indicating there are 39 uses of `option` in the first 40 lines of each of those man pages. When including all of the man page, bash dominates and has 5 uses of `flag` but over 400 more of `option`.

I'm really happy that you're consistent, but I'm concerned that we're telling learners to use a term that is obsolescent and best and has sketchy support in other documents.

**Comment by gcapes** [comment]
Sure. Would you like to submit a PR to change all instances of `flag` to `option` (but retain the original note that switch/option/flag are used to refer to the same thing)?

**Comment by drj11** [comment]
Yes I would!

**Comment by gdevenyi** [comment]
:+1: I like the empirical approach.

**Comment by andrewbattista** [comment]
Adding in what I hope is a substantial comment here. Nomenclature and consistency is great and important, and the lessons should strive for this, but there could (and maybe should be) more meta-commentary on the instructor guide and in the lessons to indicate the fluidity with which people using these commands in real life colloquially switch back and forth. Personally, I think that modeling this behavior while teaching and calling attention to it is a better approach than always trying to use the official term.

**Comment by fthommen** [comment]
This might be a repetition of what @andrewbattista wrote (I'm not completely sure I understand everything he wrote): In this specific case IMHO "learning the variability" outrivals "consistency". In the wild the course attendants will encounter `option`, `flag`, `parameter`, `switch` you name it.  Even `argument` is sometimes used for what we refer as `option` here.  To prepare the attendants for this variabilty of vocabulary I tend to use all these terms throughout the course to make them realize, that they are all the same.

**Comment by gcapes** [comment]
I would urge caution with this approach @fthommen. Parameters and arguments are different, even though they are often used interchangeably https://github.com/swcarpentry/shell-novice/issues/623

**Comment by fthommen** [comment]
> I would urge caution with this approach @fthommen. Parameters and arguments are different, even though they are often used interchangeably

I am aware of that and I wouldn't mix the two, either.  My point was, that there are many terms for `option` and I would rather confront the participants with all of them, than sticking with a single option for `option`:-).  More sooner than later they will be confronted with the other terms anyway and would then immediately understand them.

**Comment by gcapes** [comment]
I'll make a PR for this using 'option' consistently. After the initial explanation, I don't think it's helpful to add cognitive load by interchangeably using multiple terms to refer to the same thing.
