### ISSUE TITLE
Add example showing users how to rename all filenames matching a specific pattern

### ISSUE THREAD

**Issue by mpizz002** [swcarpentry/shell-novice#942]
I think it would be helpful to include an example on how to rename all filenames matching a specific pattern within 3. Working With Files and Directories, near the lesson on listing filenames matching a pattern & organizing files and directories. Specifically, the commands I think would be helpful to include are: mmv and rename.

mmv [old pattern] \* [new pattern] \#1
rename 's/[old pattern]/[new pattern]/' *

**Comment by gcapes** [comment]
Thanks for the issue!

While these are both useful, neither are guaranteed to be available with a given implementation Bash. We want the lesson material to work regardless of where you're running Bash, without having to install anything else. As such this is out of scope for this lesson.

Thanks again for taking the time to contribute!
