### ISSUE TITLE
Episode 7 Undefined file type 'oldtool'

### ISSUE THREAD

**Issue by feoornik** [swcarpentry/shell-novice#943]
Under the directory tree explanation, the file type of 'oldtool' is not specified unlike all other files; haiku.txt, empty-draft.md, LittleWomen.txt, one.txt, and two.txt stated before it. Is the file type extension deliberately omitted?

**Comment by gcapes** [comment]
`format` and `stats` at the level above don't have file extensions either. These are listed under `tools` so I would think these are all executables, and as such wouldn't necessarily have a file extension.
