### ISSUE TITLE
Inconsistencies related to POSIX compliance

### ISSUE THREAD

**Issue by fthommen** [swcarpentry/shell-novice#946]
Even though the instructor guide suggests to stay within POSIX-compliant commands (see a related discussion at #927), some non-POSIX compliant options are used in the lesson, e.g. ``ls --help`` (in 02-filedir), ``cp -r`` (03-create, should be ``-R`` since POSIX.1-2017), ``grep -w`` and ``grep --help`` (07-find).  Maybe more.

As long as the instructor guide instructs us to be POSIX compliant, the lesson content should, too :-)

**Comment by gdevenyi** [comment]
Closing in favour of #927 

Please contribute do the discussion there.
