### ISSUE TITLE
Suggestion: Rearrange "Getting Help" topics in its own small episode

### ISSUE THREAD

**Issue by fthommen** [swcarpentry/shell-novice#947]
From my experience it is most helpful to teach the course participants right from the beginning how they can get help themselves.  I refer to pure commandline tools and not to internet searches (I tend to give shell courses in a commandline-only environment).  I suggest, that the topics
- ``-h`` / ``--help`` commandline options
- man pages (similar to http://swcarpentry.github.io/shell-extras/01-man-pages/)
  - subtopic: usage of a pager
- ``apropos`` / ``man -k``
- what can se find in ``/usr/share/doc``

are tought in a small _separate_ chapter before 02-filedir.  It shouldn't take more than around 5 - 10 minutes.  A part of this additionally required time could be taken from 02-filedir where some of these concepts are tought.  The other few minutes would have to be added to the overall course duration.

**Comment by colinmorris** [comment]
My concern with this is that it might put the cart before the horse. In such a lesson, you're going to want to look at the help for a few specific commands, right? Which commands would you use as examples? Will learners be able to make sense of the description of `ls` and its options without first understanding the concept of directory structures and the current working directory? If you're going to use any commands that interact with files as an example, you'll need to first have learners get as far as `cd`ing into `data-shell` so they have some files to interact with. There might be some commands learners can run and understand without the information in episode 2 (`date`?), but I'm not sure there are any non-contrived ones.

I'm skeptical at the moment, but I'd definitely be interested in hearing any more details about how you would structure such an episode, and what kinds of examples and exercises you were imagining.

**Comment by fthommen** [comment]
> I'm skeptical at the moment, but I'd definitely be interested in hearing any more details about how you would structure such an episode, and what kinds of examples and exercises you were imagining.

I would already have explained the general structure of a command (command - options/switches - arguments) and some helpful things right from the beginning (^C, clear, reset, echo) and then use ``man echo`` to explain the general structure of a manpage.  I don't think the participants have to understand what a command does to understand how its manpage is structured.  Using ``man echo`` I explain how to navigate the pager, search for text in the manpage and how to quit it.  Then I let them search for commands that do something with printing (``apropos print``) or compression (``apropos compress``).  Very early in the next lesson I would let them search for an option to ``ls`` which lists all files or which lists files recursively etc.  I use this kind of small help-yourself questions all over the lessons.

"Would" sounds hypothetical :-), but in fact that's how my current (non-software carpentry) course is done.

**Comment by gdevenyi** [comment]
A problem remains that not all terminal environments are feature complete. We still have the problem of missing man pages, and inconsistent coreutils vs bsdutils.

We will hold off on discussing this further until these other topics are resolved.

**Comment by fthommen** [comment]
IMHO the presence of a defined Linux/Unix environment could (should) be made a prerequisite for such a course (yes, I know of all collateral problems that can occur...).  The only problematic host environment being Windows.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this discussion, we can reopen.
