### ISSUE TITLE
Is the current content on < (redirecting input) useful?

### ISSUE THREAD

**Issue by colinmorris** [swcarpentry/shell-novice#954]
You can probably guess my opinion based on the loaded question.

In [Episode 4 on pipes and filters](http://swcarpentry.github.io/shell-novice/04-pipefilter/index.html) we have a callout box titled "Redirecting Input", followed by an exercise, "What Does `<` Mean?".

The callout shows how instead of doing `wc ammonia.pdb` we can do `wc < ammonia.pdb`. I feel like a natural reaction for a learner on encountering this is "okay, but why should I memorize two ways to do the same thing? What's wrong with the first way?". And I can't think of a good answer to that. "In the future you might need to use a command that reads from stdin and doesn't take a filename argument, and if you were to solve this problem with `cat myfile.txt | mycommand` then Unix snobs might scoff at you"?

The exercise that follows illustrates a difference between the approaches (the fact that `wc`'s output doesn't include the filename when redirecting stdin), but it seems like a pretty trivial one.

What about just removing this content? `<` seems like a relatively advanced tool that doesn't do much to expand the range of what learners can accomplish in the shell.

**Comment by gcapes** [comment]
I'd be quite happy to drop this.

**Comment by gdevenyi** [comment]
+1 for dropping.

I use cat all the time the "wrong" way.
