### ISSUE TITLE
Suggested Loops update

### ISSUE THREAD

**Issue by mozeran** [swcarpentry/shell-novice#971]
In the [Loops episode](http://swcarpentry.github.io/shell-novice/05-loop/index.html), the description of the first example is incorrect. (I'm guessing the example was previously modified but the explanation was not.) Here's what it says now:

> The interpreter runs the command `head` on `basilisk.dat`, and then prints the first three lines of `basilisk.dat`. For the second iteration, `$filename` becomes `unicorn.dat`. This time, the shell runs `head` on `unicorn.dat` and prints the first three lines of `unicorn.dat`.

This is what I would suggest changing it to:

> The interpreter runs the command `head` on `basilisk.dat`, pipes the first two lines to the `tail` command, and then prints the second line of `basilisk.dat`. For the second iteration, `$filename` becomes `unicorn.dat`. This time, the shell runs `head` on `unicorn.dat`, pipes the first two lines to the `tail` command, and then prints the second line of `unicorn.dat`.

**Comment by colinmorris** [comment]
Nice catch. Your proposed rewording looks good - PR welcome!

**Comment by gcapes** [comment]
Fixed in #973
