### ISSUE TITLE
Episode 4, "Which Pipe?" options not previously introduced

### ISSUE THREAD

**Issue by reid-a** [swcarpentry/shell-novice#979]
In the "Which pipe?" exercise, several of the options include `uniq -c` and `grep` as candidate solutions. This is the first occurrence in the lesson of the `grep` command at all, and while `uniq` has been introduced, the `-c` option has not yet been introduced for this command.

This caused some disorientation in learners.

I think `uniq -c` is fine if the `-c` option is explained earlier, but that this is too early for `grep`.

**Comment by gcapes** [comment]
Thanks for the contribution! 

Yes, certainly too early for grep. While learners should now know how to find out what options mean, this isn't the point of the exercise, so some explanation of the option should be given.

**Comment by reid-a** [comment]
I have put in a pull request with minor edits to fix this. I'm a bit surprised it can't be automatically merged, it's possible I've made an error in the pull-request workflow, the changes localized and seem straightforward to me.

**Comment by amanda-tan** [comment]
The maintainers need to check to make sure that your pull request makes sense before merging.

**Comment by reid-a** [comment]
Right -- I think I actually misread the initial message. Of course I understand it needs approval, but I thought I saw a message that said something about conflicts, and there should not be any of those. But, I can't find that message now, so probably I just jumped to a wrong conclusion from the first message.
