### ISSUE TITLE
[Episode 07] exercise solution contains unnecessary command

### ISSUE THREAD

**Issue by jdkent** [swcarpentry/shell-novice#989]
The solution for the [Tracking a Species](https://github.com/swcarpentry/shell-novice/blame/6c0a944eb4e7e0bc35de3773cede1fa00be5157b/_episodes/07-find.md#L330) should be:
```
grep -w $1 -r $2 | cut -d , -f 1,3  > $1.txt
```
not 
```
grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt
```
While both commands return the same answer, there are no colons in the text, so the `cut -d : -f 2` command does nothing but return all the text that was piped into it.
Removing this command will make the answer clearer.

**Comment by charris-pawsey** [comment]
I tried running both scripts in the suggested data-shell/data/animal-counts directory, using
`bash count-species.sh bear .`

The current script
`grep -w $1 -r $2 | cut -d : -f 2 | cut -d , -f 1,3  > $1.txt`
produced bear.txt with the following contents
`2012-11-07,1`

The proposed script
`grep -w $1 -r $2 | cut -d , -f 1,3  > $1.txt`
produced bear.txt with slightly different output
`./animals.txt:2012-11-07,1`

I think the extra command is needed to remove the filename pre-pended by grep when the -r flag is used.

**Comment by jdkent** [comment]
thanks for the reply!

I misread the directions, I did not use a directory as the second argument, I just used the filename, which produces different output:

`grep -w bear -r .` -> `./animals.txt:2012-11-07,bear,1`

`grep -w bear -r animals.txt` -> `2012-11-07,bear,1`

Sorry for the noise, I'll close this and the pull request.
