### ISSUE TITLE
Drop or clarify the purpose for the '$how ...' challenge from 04-loop.md

### ISSUE THREAD

**Issue by wking** [swcarpentry/shell-novice#99]
As I mentioned in #33 and #95, I don't understand what this challenge is trying to show, or why it belongs in the loop lesson.  Quoting from my #33 commit:

> Naming the last challenge is difficult, because it's not really about
> loops.  That challenge dates back to 8e77786 (Importing shell lesson
> for novices, 2013-11-11), which doesn't explain the pedagogical
> motivation for the challenge.  Maybe it's just a trick to keep
> students from being to focused on the purported topic when crafting
> their answers?  Maybe it's intentionally a throwback to more basic
> shell syntax couched in the decoration of the current topic?  Maybe
> it's a hint that you can do more with loops than vary arguments to a
> single command?  In any event, I'd prefer removing this challenge
> entirely, or reworking the content as an example (instead of a
> challenge).

If anyone does have a clear handle on why this challenge is useful, please share (and we can mention the motivation in `instructors.md`.  If we don't hear anyone motivating it in the next month, I'd recommend dropping the challenge.

**Comment by drj11** [comment]
Challenge has been dropped via https://github.com/swcarpentry/shell-novice/pull/121

This issue can be closed now.
