### ISSUE TITLE
Recursive option different between commands

### ISSUE THREAD

**Issue by lennertz** [swcarpentry/shell-novice#996]
in Unix shell lesson there is some emphasis on -R meaning recursive.  In all future lessons, as we move throughout different commands -r is (appropriately) uses for recursive eventhough -R is also acceptable.  Maybe we need to be more consistent or at least add some info on how options do change based on the commands and to check the help.

**Comment by gcapes** [comment]
Thanks for the issue. 
The `-R` option is used with `ls`, at which point we have a discussion about options and how to discover them via `man` and `--help`. There isn't a suggestion that the options are the same for different commands, but perhaps that could be made explicit somewhere in episode 2.

**Comment by gcapes** [comment]
Or perhaps this would be better mentioned in episode 3, on first use of `cp -r`. I think it might be information overload to introduce it in episode 2.

**Comment by gdevenyi** [comment]
An unfortunate instance of commands being developed separately and converging to similar functionality, sometimes the interfaces differ.

**Comment by colinmorris** [comment]
It looks like `/-[rR]/` is used in the following commands:
1. `ls -R`
1. `ls -r`
1. `cp -r`
1. `rm -r`
1. `sort -r`
1. `grep -r`

In 2 and 5, it does not signify 'recursive'. In all cases, the flags are explained where they're used (semi-exception for grep, but the exercise in which the flag is used explicitly asks the reader to look at `man grep`).

I don't think this should be too confusing (given that the flags are explained), and I have a couple (minor) issues with changing all recursive flags to `-R`:
- It could give the reader the false impression that flags will generally have consistent meanings across commands
- Technically `grep -r` and `grep -R` have slightly different functionality (related to symlinks)
- I get the impression that the lowercase `-r` flag is generally more commonly used with grep/rm/cp, so readers are more likely to encounter that form in the wild.

**Comment by gcapes** [comment]
Any outstanding action required for this?

We could mention somewhere that options don't necessarily have the same meaning for different commands. However, I'm not sure that this is really needed. What do others think?

**Comment by gcapes** [comment]
Closing stale issue
