### ISSUE TITLE
Combining flags example, combined flags vs flag parameters

### ISSUE THREAD

**Issue by shervinsahba** [swcarpentry/shell-novice#997]
I believe only one line in the [lesson](https://swcarpentry.github.io/shell-novice/02-filedir/index.html) addresses flag combination, giving `ls -Fa` as an example. (See related [PR](https://github.com/swcarpentry/shell-novice/pull/483) from 2016).

Could we incorporate flag combinations into an example or repeat their usage later? Practice would help users. For example, based on what users learn in this module one could demonstrate `ls -h -a -l -F` can be simplified to `ls -halF` or any other permutation of `halF`.

Users will undoubtedly come across these combinations if they search online, so they should distinguish them from string based flags like `--help`. Additionally, I am unsure if a distinction is made between standalone flags such as those above and flags that necessitate parameters like `cut -d , -f 1`, where combining d and f could throw errors.

Thoughts?

(PS. I'm new to collaborating on GitHub and still learning! I'd be happy to script something up if this seems like a worthwhile addition.)

**Comment by gcapes** [comment]
Hi @shervinsahba 
Thanks for the issue!

In a lesson which is already very full, what would you take out to make room for this?

My feeling is that combining single-letter options isn't a key learning objective, and the mention we have is enough. I seem to recall that at some point we went through the lesson to ensure that where examples used multiple options, each option had its own hyphen.

Regarding the `cut` example - I think this usage is explained quite well in the challenge.

Thoughts from the other maintainers?

**Comment by gcapes** [comment]
I'm taking the thumbs up and lack of further discussion as a green light to close this issue.

**Comment by gdevenyi** [comment]
Agree with @gcapes that a short mention is sufficient, as this is not a learning objective of these lessons.
