### ISSUE TITLE
[email feedback] include '/' in paths shown on diagrams

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/shell-novice#999]
Feedback received by email, I'm just the messenger:

> On the material for the bash shell, there are good diagrams in the sections "Home directory variation" and "slashes". 
>
> What is good about these diagrams is that they clearly show a / symbol at the root of the tree. This is important as most participants probably know little or nothing about the shell when they start.
>
> But in some of the diagrams the slash in the root directory is not shown, e.g. in the group quiz questions "Relative Path Resolution" and "ls Reading Comprehension". This will confuse the candidates.
>
> For clarity, I suggest you please amend those diagrams to include a / character at the top of the tree.

**Comment by gcapes** [comment]
We may not be able to discuss effectively given this was by email, but...

The diagrams in the exercises show relative paths, so the root `/` isn't needed.

This relative path diagram idea has already been introduced in episode 2, underneath the text
>Underneath `/Users`, we find one directory for each user with an account on Nelle’s machine, her colleagues imhotep and larry.

Where the level above (including `/`) has been greyed out.

I'd merge a PR extending the diagram to show the root directory, but I don't think it's needed.

**Comment by gdevenyi** [comment]
Agree with @gcapes that the point of relative paths is to avoid having to reference the tree root all time, especially for a very deep tree. In fact, it may be worth highlighting how awful a deep tree can be if it were an absolute path.
